### ISSUE TITLE
Flexget command line errors - No module named pytz 

### ISSUE THREAD

**Issue by gwgr** [SynoCommunity/spksrc#1423]
Not sure if this is the appropriate place to post so please close if not.  Just installed Python and Flexget on 415+ and was getting errors on command line:

[admin] /volume1/Downloads/.flexget $ /volume1/@appstore/flexget/env/bin/flexget --test execute
2015-01-02 15:29 CRITICAL plugin                        Plugin `flexget.plugins.daemon.scheduler` failed to import dependencies
2015-01-02 15:29 ERROR    plugin                        No module named pytz
Traceback (most recent call last):
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugin.py", line 390, in _load_plugins_from_dirs
    __import__(module_name)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/daemon/scheduler.py", line 5, in <module>
    import pytz
ImportError: No module named pytz

Found that I had to install the following packages to allow it to run error free

[root] ~ $ /volume1/@appstore/flexget/env/bin/easy_install pytz
[root] ~ $ /volume1/@appstore/flexget/env/bin/easy_install tzlocal
[root] ~ $ /volume1/@appstore/flexget/env/bin/easy_install apscheduler

Hope this helps someone!

**Comment by Dr-Bean** [comment]
Or try `/usr/local/flexget/env/bin/pip install pytz`. I'll take a look at adding it to the package, the Flexget version needed an update anyway.

**Comment by Dr-Bean** [comment]
I've published Flexget 20150206-3 on the repository. It's updated to the latest available version (released today, I believe), and contains the above modules.

Note: webinterface plugin is still borked, don't even try it ;)
