### ISSUE TITLE
FlexGet schedule error

### ISSUE THREAD

**Issue by Martijn085** [SynoCommunity/spksrc#1638]
I have added some tasks in FlexGet, this looks all fine but when i add a schedule for any task, FlexGet will give an error when i go to http://nas-ip:8290/configure/ or http://nas-ip:8290/schedule/

Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

This is my log file:

2015-04-10 13:45 ERROR    flexget.ui.webui                 Exception on /configure/ [GET]
Traceback (most recent call last):
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/ui/plugins/configure/configure.py", line 16, in index
    return render_template('configure/configure.html')
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/ui/plugins/configure/templates/configure/configure.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/ui/templates/layout.html", line 44, in top-level template code
    {% block menu %}
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/ui/plugins/configure/templates/configure/configure.html", line 31, in block "menu"
    {% for a_name in manager.config[category].iterkeys() %}
UndefinedError: 'list object' has no attribute 'iterkeys'

**Comment by Dr-Bean** [comment]
I guess you're using the web ui. Take note of the hugh orange block with the warning in it. I expect it has something to do with that ;)

In all seriousness, the web interface has multiple issues. Don't use it. 

If anything, you can report the problems on the Flexget issue tracker (although I don't think it'll be solved anytime soon, the devs have other priorities)

**Comment by Martijn085** [comment]
I know the webui is not supported, but the scheduler should run, right? This one does nothing. I have tested it to run all tasks every 5 minutes but it does nothing.

**Comment by Dr-Bean** [comment]
That's a different issue, because to me that seems unrelated to the webui not functioning, right?

Anyway, the package is still in beta, so yes, it's possible things don't work correctly. Currently, we daemonize the webui (although, we might need to rethink that one...). It's possible that it's necessary to daemonize the scheduler separately, I believe I mentioned that in here: https://github.com/SynoCommunity/spksrc/issues/1508. Can you test that, and let us know?

**Comment by Martijn085** [comment]
You are right it`s something completely different. I will test the option you have given at https://github.com/SynoCommunity/spksrc/issues/1508 and will come back on this.
