### ISSUE TITLE
Deluge require python-libtorrent

### ISSUE THREAD

**Issue by hitechbeijing** [SynoCommunity/spksrc#1681]
deluge require python-libtorrent, but spksrc is not privide.

**Comment by Diaoul** [comment]
Here it is: https://github.com/SynoCommunity/spksrc/tree/master/cross/libtorrent

**Comment by Diaoul** [comment]
If you want it in Python SPK you need to recompile it after adding cross/libtorrent to DEPENDS.

**Comment by hitechbeijing** [comment]
The makefile write that "include $(WORK_DIR)/python-cc.mk"
so, how can i find it?

**Comment by Diaoul** [comment]
This can be compiled as a dependency only, see my comment above.

**Comment by bonebox** [comment]
When I add `cross/libtorrent` to DEPENDS, I get the following error: 

`Make[2]: *** No rule to make target '/spksrc/spk/deluge/work/python-cc.mk'. Stop.`

**Comment by bonebox** [comment]
I was able to get further by commenting out the reference to python-cc.mk in the libtorrent Makefile, but now the build is failing with the following.  I did a `PKG_CONFIG_PATH=/usr/lib/pkgconfig` which is where libffi.pc is located, but it still fails with this error.

```
Requirement already up-to-date: pip in /home/debian/source/spksrc/native/python/work-native/install/usr/local/lib/python2.7/site-packages
Collecting cffi==0.9.1
  Using cached cffi-0.9.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): pycparser in ./work-native/install/usr/local/lib/python2.7/site-packages (from cffi==0.9.1)
Installing collected packages: cffi
  Running setup.py install for cffi
    Complete output from command /home/debian/source/spksrc/native/python/work-native/install/usr/local/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-TAR80O/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-wQcPxV-record/install-record.txt --single-version-externally-managed --compile:
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-i686-2.7
    creating build/lib.linux-i686-2.7/cffi
    copying cffi/ffiplatform.py -> build/lib.linux-i686-2.7/cffi
    copying cffi/vengine_cpy.py -> build/lib.linux-i686-2.7/cffi
    copying cffi/commontypes.py -> build/lib.linux-i686-2.7/cffi
    copying cffi/model.py -> build/lib.linux-i686-2.7/cffi
    copying cffi/__init__.py -> build/lib.linux-i686-2.7/cffi
    copying cffi/cparser.py -> build/lib.linux-i686-2.7/cffi
    copying cffi/backend_ctypes.py -> build/lib.linux-i686-2.7/cffi
    copying cffi/verifier.py -> build/lib.linux-i686-2.7/cffi
    copying cffi/gc_weakref.py -> build/lib.linux-i686-2.7/cffi
    copying cffi/api.py -> build/lib.linux-i686-2.7/cffi
    copying cffi/vengine_gen.py -> build/lib.linux-i686-2.7/cffi
    copying cffi/lock.py -> build/lib.linux-i686-2.7/cffi
    running build_ext
    building '_cffi_backend' extension
    creating build/temp.linux-i686-2.7
    creating build/temp.linux-i686-2.7/c
    /home/debian/source/spksrc/toolchains/syno-armadaxp-5.1/work/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/home/debian/source/spksrc/toolchains/syno-armadaxp-5.1/work/arm-marvell-linux-gnueabi/arm-marvell-linux-gnueabi/libc/include -mcpu=marvell-pj4 -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=hard -DSYNO_MARVELL_ARMADA370 -DSYNO_PLATFORM=MARVELL_ARMADA370 -I/home/debian/source/spksrc/spk/deluge/work/install//usr/local/deluge/include -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -I/home/debian/source/spksrc/toolchains/syno-armadaxp-5.1/work/arm-marvell-linux-gnueabi/arm-marvell-linux-gnueabi/libc/include -mcpu=marvell-pj4 -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=hard -DSYNO_MARVELL_ARMADA370 -DSYNO_PLATFORM=MARVELL_ARMADA370 -I/home/debian/source/spksrc/spk/deluge/work/install//usr/local/deluge/include -fPIC -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/home/debian/source/spksrc/native/python/work-native/install/usr/local/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-i686-2.7/c/_cffi_backend.o
    c/_cffi_backend.c:13:17: fatal error: ffi.h: No such file or directory
    compilation terminated.
    error: command '/home/debian/source/spksrc/toolchains/syno-armadaxp-5.1/work/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-gcc' failed with exit status 1
    
    ----------------------------------------
    Command "/home/debian/source/spksrc/native/python/work-native/install/usr/local/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-TAR80O/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-wQcPxV-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-TAR80O/cffi
make[5]: *** [myPostInstall] Error 1
make[5]: Leaving directory `/home/debian/source/spksrc/native/python'
make[4]: *** [depend_target] Error 2
make[4]: Leaving directory `/home/debian/source/spksrc/cross/python'
make[3]: *** [depend_target] Error 2
make[3]: Leaving directory `/home/debian/source/spksrc/cross/boost'
make[2]: *** [depend_target] Error 2
make[2]: Leaving directory `/home/debian/source/spksrc/cross/libtorrent'
make[1]: *** [depend_target] Error 2
make[1]: Leaving directory `/home/debian/source/spksrc/spk/deluge'
make: [arch-armadaxp] Error 2 (ignored)
```

**Comment by Dr-Bean** [comment]
Don't you just need to start the make process twice? First time, `make` creates `python-cc.mk`, second time, `make` can use `python-cc.mk`.

**Comment by bonebox** [comment]
No, it continues to give that error no matter how many times you run `make`.

**Comment by Diaoul** [comment]
Go in `native/python then do `make clean` then `make`. If that crashes make sure you've installed all dependencies mentionned in the README (and/or Dockerfile, that should be the same anyway).
If that works continue with `spk/python`.

**Comment by bonebox** [comment]
The native/python made successfully.  But spk/python fails with the following.  I have installed all the dependencies in the README.

```
make[2]: Entering directory `/home/debian/source/spksrc/cross/bcrypt'
===>  Compiling for bcrypt
running build_ext
Traceback (most recent call last):
  File "setup.py", line 255, in <module>
    **keywords_with_side_effects(sys.argv)
  File "/home/debian/source/spksrc/spk/python/work-armadaxp-5.1/Python-2.7.9/Lib/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/home/debian/source/spksrc/spk/python/work-armadaxp-5.1/Python-2.7.9/Lib/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/debian/source/spksrc/spk/python/work-armadaxp-5.1/Python-2.7.9/Lib/distutils/dist.py", line 971, in run_command
    cmd_obj.ensure_finalized()
  File "/home/debian/source/spksrc/spk/python/work-armadaxp-5.1/Python-2.7.9/Lib/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "/home/debian/source/spksrc/spk/python/work-armadaxp-5.1/install/usr/local/python/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 105, in finalize_options
    _build_ext.finalize_options(self)
  File "/home/debian/source/spksrc/spk/python/work-armadaxp-5.1/Python-2.7.9/Lib/distutils/command/build_ext.py", line 140, in finalize_options
    ('plat_name', 'plat_name'),
  File "/home/debian/source/spksrc/spk/python/work-armadaxp-5.1/Python-2.7.9/Lib/distutils/cmd.py", line 298, in set_undefined_options
    src_cmd_obj.ensure_finalized()
  File "/home/debian/source/spksrc/spk/python/work-armadaxp-5.1/Python-2.7.9/Lib/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "setup.py", line 36, in finalize_options
    self.distribution.ext_modules = get_ext_modules()
  File "setup.py", line 21, in get_ext_modules
    from bcrypt import _ffi
  File "/home/debian/source/spksrc/spk/python/work-armadaxp-5.1/bcrypt-1.1.0/bcrypt/__init__.py", line 97, in <module>
    _ffi = FFI()
  File "/home/debian/source/spksrc/spk/python/work-armadaxp-5.1/install/usr/local/python/lib/python2.7/site-packages/cffi/api.py", line 56, in __init__
    import _cffi_backend as backend
ImportError: /home/debian/source/spksrc/spk/python/work-armadaxp-5.1/install/usr/local/python/lib/python2.7/site-packages/_cffi_backend.so: cannot open shared object file: No such file or directory
make[2]: *** [compile_python_module] Error 1
make[2]: Leaving directory `/home/debian/source/spksrc/cross/bcrypt'
make[1]: *** [depend_target] Error 2
make[1]: Leaving directory `/home/debian/source/spksrc/spk/python'
make: [arch-armadaxp] Error 2 (ignored)
```
```
debian@debian:~/source/spksrc/spk/python$ find /home/debian/source/spksrc/ -name _cffi_backend.so
/home/debian/source/spksrc/spk/python/work-armadaxp-5.1/install/usr/local/python/lib/python2.7/site-packages/_cffi_backend.so
/home/debian/source/spksrc/spk/python/work-armadaxp-5.1/cffi-0.9.1/build/lib.linux-i686-2.7/_cffi_backend.so
```

**Comment by bonebox** [comment]
I changed the last line of the libtorrent Makefile to point to `../python/work-armadaxp-5.1/python-cc.mk` and was able to continue.  I had several build failures that I worked through, and managed to build libtorrent successfully and made it most of the way through the deluge make, but now it is failing with a lot of `stripping lib/<library>.so ... failed!` errors.  There is no `lib` subdirectory off the deluge directory, which I think may be the problem.  Any ideas?

**Comment by bonebox** [comment]
Also a lot of `stripping bin/<file> ... failed!` errors.  It appears the files it's looking for are in `spk/deluge/work/staging` and also in `spoke/deluge/install/usr/local/deluge`.  Is there a way to point it to the correct path, and which one is the correct one?

**Comment by bonebox** [comment]
Also getting this error:
```
Stripping @PYTHON_SITE_PACKAGES@/libtorrent.so... chmod: cannot access `/home/user1/source/spksrc/spk/deluge/work/staging/@PYTHON_SITE_PACKAGES@/libtorrent.so': No such file or directory
```
 Doesn't appear it's expanding the path properly.

**Comment by bonebox** [comment]
Well, after a lot of hair-pulling, I have Deluge running successfully on my DS414.  I couldn't get it installed as a package (it couldn't find libtorrent therefore said it wasn't available on my architecture, lots of incorrect paths, other problems), but I uploaded the tarball and was able to get it set up manually after some additional installations, path changes, etc.

**Comment by hitechbeijing** [comment]
Hi, I have try to make the libtorrent as your setting, but it has some problem in make boost. But, it have a good news this afternoon(in my time zone), Synology has publish DSM 5.2 and it also publish a package which named python module,  so we could install deluge in Synology NAS success. Now, the problem is the deluge package could not start, am try to work for the start-stop script. If any news I will tell you and if you have any idea I hope you can share with me. Many thanks for your help.








发自 Windows 邮件





发件人: Jeremy Bone
发送时间: ‎2015‎年‎5‎月‎13‎日, ‎星期三 ‎4‎:‎48
收件人: SynoCommunity/spksrc
抄送: HS





I changed the last line of the libtorrent Makefile to point to ../python/work-armadaxp-5.1/python-cc.mk and was able to continue. I had several build failures that I worked through, and managed to build libtorrent successfully and made it most of the way through the deluge make, but now it is failing with a lot of stripping lib/<library>.so ... failed! errors. There is no lib subdirectory off the deluge directory, which I think may be the problem. Any ideas?

**Comment by Diaoul** [comment]
I'll take a look into deluge this week.

**Comment by bonebox** [comment]
@hitechbeijing Yeah, one of the failures I had was with boost.  I resolved it by manually editing the `user-config.jam` file and updating the `using python` line to point to the correct python binary and libs.

The package stuff is pretty broken, I found.  One of the reasons it won't start is because it references `start-stop-daemon` which isn't part of a standard Synology build.  It looks like the script was probably taken from the example on the Deluge website and not actually updated to work on a Synology NAS.

**Comment by Diaoul** [comment]
@bonebox: start-stop-status is provided by busybox when building the package. Deluge worked quite well when initially released but wasn't pushed further because libtorrent wouldn't compile on most arches (ppc & some arm) due to old compiler versions and I didn't want to introduce multiple versions of python (one with libtorrent, the other without) for users.

If you do some manual install and grab some stuff from the package you will indeed end up with broken stuff, but don't blame the packaging.

**Comment by bonebox** [comment]
I'm not blaming the packaging per se, but bottom line is it won't install on my Syno if I don't already have libtorrent installed.  There are certainly build issues.
