### ISSUE TITLE
Horde_Translation_Exception

### ISSUE THREAD

**Issue by sebastiendamaye** [SynoCommunity/spksrc#1685]
Hi,

I've installed your Horde package and it's working fine. But when it comes to using ActiveSync, it's becoming a nightmare... As mentionned in Horde's ActiveSync webpage, you must first define aliases as follows so that your device (e.g. mobile) can connect using Exchange-like settings:

```
Alias /Microsoft-Server-ActiveSync /volume1/web/horde/rpc.php
Alias /autodiscover/autodiscover.xml /volume1/web/horde/rpc.php
Alias /Autodiscover/Autodiscover.xml /volume1/web/horde/rpc.php
Alias /AutoDiscover/AutoDiscover.xml /volume1/web/horde/rpc.php
```

I've added these aliases to httpd-ssl.conf-user. I know it's working because I've used such a conf while installing Horde myself (not via your package) on another NAS.

When I'm connecting to https://mydomain.tld/Microsoft-Server-ActiveSync, it shows the following error message:

```
Warning: require_once(Horde/Autoloader/Default.php): failed to open stream: No such file or directory in /volume1/web/horde/lib/core.php on line 49 Fatal error: require_once(): Failed opening required 'Horde/Autoloader/Default.php' (include_path='/volume1/web/horde/lib:.:/var/packages/PEAR/target') in /volume1/web/horde/lib/core.php on line 49 
```

What I did at this stage is to add /volume1/@appstore/.pear (this is where I've found Horde/Autoloader/Default.php) to my path in /etc/php/conf.d/user-settings.ini:

```
display_errors = On
open_basedir = /etc.defaults:/etc:/usr/syno/synoman:/tmp:/var/services/tmp:/var/services/web:/var/services/homes
apc.enabled = 1
opcache.enable = 1
opcache.enable_cli = 1
;PEAR Package start (don't remove this line)
include_path = .:/var/packages/PEAR/target:/volume1/@appstore/.pear
;PEAR Package end (don't remove this line)
```

I've also added these paths to my PHP open_basedir (via the GUI):

```
/volume1/@appstore/.pear:/volume1/@appstore/PEAR
```

Now, the error message is:

```
exception 'Horde_Translation_Exception' with message 'Could not found find any locale directory for Horde_Core domain.' in /volume1/@appstore/.pear/Horde/Translation/Autodetect.php:51
Stack trace:
#0 /volume1/@appstore/.pear/Horde/Translation.php(93): Horde_Translation_Autodetect::loadHandler('Horde_Translati...')
#1 /volume1/@appstore/.pear/Horde/ErrorHandler.php(101): Horde_Translation::t('A fatal error h...')
#2 [internal function]: Horde_ErrorHandler::fatal(Object(Horde_Translation_Exception))
#3 {main}
```

Any idea how to make this work?
Many thanks for your help.
##

**Comment by ayevee** [comment]
I have the following section in .htaccess (works fine):
```
<IfModule mod_rewrite.c>
RewriteEngine on
RewriteRule .* - [E=HTTP_MS_ASPROTOCOLVERSION:%{HTTP:Ms-Asprotocolversion}]
RewriteRule .* - [E=HTTP_X_MS_POLICYKEY:%{HTTP:X-Ms-Policykey}]
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

RewriteRule ^Microsoft-Server-ActiveSync /horde/rpc.php [PT,L,QSA]
</IfModule>
```
