### ISSUE TITLE
Missing bsddb3 dependence for Subliminal 0.7.5-12 Beta

### ISSUE THREAD

**Issue by grosenbaum** [SynoCommunity/spksrc#1702]
Hi all,

On my DS 413 with DSM 5.2, I'm using SynoCommunity packages:
* `Subliminal 0.7.5-12`
* `Python 2.7.9-13`

Running Subliminal CLI works until it rises this error:

```
Traceback (most recent call last):
  File "/usr/local/subliminal/env/lib/python2.7/site-packages/subliminal/api.py", line 256, in download_best_subtitles
    provider_subtitles = provider.list_subtitles(video, provider_video_languages)
  File "/usr/local/subliminal/env/lib/python2.7/site-packages/subliminal/providers/tvsubtitles.py", line 178, in list_subtitles
    return [s for s in self.query(video.series, video.season, video.episode) if s.language in languages]
  File "/usr/local/subliminal/env/lib/python2.7/site-packages/subliminal/providers/tvsubtitles.py", line 162, in query
    show_id = self.find_show_id(series)
  File "/usr/local/subliminal/env/lib/python2.7/site-packages/dogpile/cache/region.py", line 1040, in decorate
    should_cache_fn)
  File "/usr/local/subliminal/env/lib/python2.7/site-packages/dogpile/cache/region.py", line 651, in get_or_create
    async_creator) as value:
  File "/usr/local/subliminal/env/lib/python2.7/site-packages/dogpile/core/dogpile.py", line 158, in __enter__
    return self._enter()
  File "/usr/local/subliminal/env/lib/python2.7/site-packages/dogpile/core/dogpile.py", line 91, in _enter
    value = value_fn()
  File "/usr/local/subliminal/env/lib/python2.7/site-packages/dogpile/cache/region.py", line 604, in get_value
    value = self.backend.get(key)
  File "/usr/local/subliminal/env/lib/python2.7/site-packages/dogpile/cache/backends/file.py", line 220, in get
    with self._dbm_file(False) as dbm:
  File "/usr/local/python/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/subliminal/env/lib/python2.7/site-packages/dogpile/cache/backends/file.py", line 215, in _dbm_file
    "w" if write else "r")
  File "/usr/local/python/lib/python2.7/anydbm.py", line 84, in open
    mod = __import__(result)
  File "/usr/local/python/lib/python2.7/dbhash.py", line 7, in <module>
    import bsddb
  File "/usr/local/python/lib/python2.7/bsddb/__init__.py", line 67, in <module>
    import _bsddb
ImportError: No module named _bsddb
```

I try then to install the missing package but it doesn't work:

```
# /volume1/@appstore/python/bin/pip install bsddb3
Collecting bsddb3
  Using cached bsddb3-6.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Can't find a local Berkeley DB installation.
    (suggestion: try the --berkeley-db=/path/to/bsddb option)

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-V3e4mj/bsddb3
```
Any ideas ?
Thanks
Gilles

**Comment by Dr-Bean** [comment]
What was the command you were running?

**Comment by grosenbaum** [comment]
I'm using the Subliminal CLI in a shell script managed by the syno crontab.
The command should be:
```
/volume1/@appstore/python/bin/subliminal /volume1/video/series -l en
```

**Comment by Dr-Bean** [comment]
If you're using the Subliminal package, then that command is not correct. Seems more like a local installation of Subliminal.

I would expect something more along the lines of `/volume1/@appstore/subliminal/env/bin/subliminal`, and then whatever arguments you want to pass on. Please check the CLI documentation of subliminal here: http://subliminal.readthedocs.org/en/latest/api/cli.html

**Comment by grosenbaum** [comment]
Hi @Dr-Bean 
Thx for your answer but my bad, wrong NAS then wrong path :)
I use this command:

```shell
/volume1/@appstore/subliminal/env/bin/subliminal -v /volume1/video/series/Elementary/Season.03/ -l en fr
```
And the response is:

```
NFO     [subliminal.video] Scanning directory u'/volume1/video/series/Elementary/Season.03'
INFO     [subliminal.video] Scanning video u'Elementary.S03E01.720p.HDTV.X264-DIMENSION.mkv' in u'/volume1/video/series/Elementary/Season.03'
INFO     [subliminal.video] Scanning video u'Elementary.S03e06.Terra.Pericolosa.DLmux.Ita.Eng.Aac.mkv' in u'/volume1/video/series/Elementary/Season.03'
ERROR    [subliminal.video] Embedded subtitle track name u'Sub' is not a valid language
INFO     [subliminal.api] Listing subtitles with provider 'opensubtitles' for video <Episode [u'Elementary', 3x1]> with languages set([<Language [fr]>, <Language [en]>])
INFO     [subliminal.api] Found 0 subtitle(s) on opensubtitles
INFO     [subliminal.api] Listing subtitles with provider 'thesubdb' for video <Episode [u'Elementary', 3x1]> with languages set([<Language [fr]>, <Language [en]>])
INFO     [subliminal.api] Found 1 subtitle(s) on thesubdb
INFO     [subliminal.api] Listing subtitles with provider 'podnapisi' for video <Episode [u'Elementary', 3x1]> with languages set([<Language [fr]>, <Language [en]>])
INFO     [subliminal.api] Found 3 subtitle(s) on podnapisi
INFO     [subliminal.api] Listing subtitles with provider 'addic7ed' for video <Episode [u'Elementary', 3x1]> with languages set([<Language [fr]>, <Language [en]>])
ERROR    [subliminal.api] Unexpected error in provider 'addic7ed'
Traceback (most recent call last):
  File "/usr/local/subliminal/env/lib/python2.7/site-packages/subliminal/api.py", line 256, in download_best_subtitles
    provider_subtitles = provider.list_subtitles(video, provider_video_languages)
  File "/usr/local/subliminal/env/lib/python2.7/site-packages/subliminal/providers/addic7ed.py", line 150, in list_subtitles
    return [s for s in self.query(video.series, video.season)
  File "/usr/local/subliminal/env/lib/python2.7/site-packages/subliminal/providers/addic7ed.py", line 123, in query
    show_ids = self.get_show_ids()
  File "/usr/local/subliminal/env/lib/python2.7/site-packages/dogpile/cache/region.py", line 1040, in decorate
    should_cache_fn)
  File "/usr/local/subliminal/env/lib/python2.7/site-packages/dogpile/cache/region.py", line 651, in get_or_create
    async_creator) as value:
  File "/usr/local/subliminal/env/lib/python2.7/site-packages/dogpile/core/dogpile.py", line 158, in __enter__
    return self._enter()
  File "/usr/local/subliminal/env/lib/python2.7/site-packages/dogpile/core/dogpile.py", line 91, in _enter
    value = value_fn()
  File "/usr/local/subliminal/env/lib/python2.7/site-packages/dogpile/cache/region.py", line 604, in get_value
    value = self.backend.get(key)
  File "/usr/local/subliminal/env/lib/python2.7/site-packages/dogpile/cache/backends/file.py", line 220, in get
    with self._dbm_file(False) as dbm:
  File "/usr/local/python/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/subliminal/env/lib/python2.7/site-packages/dogpile/cache/backends/file.py", line 215, in _dbm_file
    "w" if write else "r")
  File "/usr/local/python/lib/python2.7/anydbm.py", line 84, in open
    mod = __import__(result)
  File "/usr/local/python/lib/python2.7/dbhash.py", line 7, in <module>
    import bsddb
  File "/usr/local/python/lib/python2.7/bsddb/__init__.py", line 67, in <module>
    import _bsddb
ImportError: No module named _bsddb
....
```

**Comment by Dr-Bean** [comment]
Add `-c CACHE_FILE` as argument, as per the earlier linked documentation. So in practice, something like `-c /usr/local/subliminal/cache/cachefile.dbm` should do.

**Comment by grosenbaum** [comment]
Works great, thx.
Gilles

**Comment by dyoann** [comment]
Thanks it worked too ... does the "default: ~/.config/subliminal.cache.dbm" not working anymore ?

**Comment by Dr-Bean** [comment]
Probably, as long as that dir exists for the user you're running as. It's not available by default for Synology users, and it's not created by Subliminal. So, easiest thing to do is to specify where to put it.
