### ISSUE TITLE
Deluge - unable to load plugin YaRSS2

### ISSUE THREAD

**Issue by BlueRay86** [SynoCommunity/spksrc#1971]
Hi, 

   I'm trying to add YaRSS2 plugin (YaRSS2-1.4.3-py2.7.egg) on Deluge 1.3.12-4. I can add the plugin in the Deluge Web, I can see it in the plugin list but I can not enable it. In the core.conf file it shows as enabled : 

 "enabled_plugins": [
    "YaRSS2"
  ], 

  but in the log when trying to enable the plugin I have the following error : 

[ERROR   ] 15:06:34 rpcserver:304 Exception calling RPC request: 'CorePlugin.YaRSS2'
Traceback (most recent call last):
  File "/usr/local/deluge/env/lib/python2.7/site-packages/deluge-1.3.12-py2.7.egg/deluge/core/rpcserver.py", line 299, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
  File "/usr/local/deluge/env/lib/python2.7/site-packages/deluge-1.3.12-py2.7.egg/deluge/core/core.py", line 528, in enable_plugin
    self.pluginmanager.enable_plugin(plugin)
  File "/usr/local/deluge/env/lib/python2.7/site-packages/deluge-1.3.12-py2.7.egg/deluge/core/pluginmanager.py", line 82, in enable_plugin
    super(PluginManager, self).enable_plugin(name)
  File "/usr/local/deluge/env/lib/python2.7/site-packages/deluge-1.3.12-py2.7.egg/deluge/pluginmanagerbase.py", line 151, in enable_plugin
    component.start([instance.plugin._component_name])
  File "/usr/local/deluge/env/lib/python2.7/site-packages/deluge-1.3.12-py2.7.egg/deluge/component.py", line 290, in start
    if self.components[name]._component_depend:
KeyError: 'CorePlugin.YaRSS2'

Any idea on how to solve this ?

**Comment by Dr-Bean** [comment]
Not a package issue. In short, that plugin doesn't have a webinterface. You can install and configure it via the GTKUI.
See http://dev.deluge-torrent.org/wiki/Plugins/YaRSS2#Installingtheplugin
