### ISSUE TITLE
Unable to start Headphones

### ISSUE THREAD

**Issue by Elfman72** [SynoCommunity/spksrc#1985]
Brand new DS1815+ running DSM 5.2.  Installed Headphones package but unable to start it.  Fails with the message "Failed to run the package service."  Being new to Synology, I apologize if this is not the appropriate place to post for this.  I have successfully installed and run several other Synocommunity packages (SAB, Sonarr, CP)  However, Headphones will not start.  Do I need to Putty into the box and look at the log files?  I have never done so and would appreciate some quick help in this regard.  Thanks again.

**Comment by Dr-Bean** [comment]
I can't reproduce it on a clean install. (assuming you did exactly what I expect: install Git, Python, then Headphones, nothing else).

Check if the log for Headphones in Package Center tells anything. Alternatively, try the Headphones-Custom package, see what that does. By default, it should do exactly the same as the original Headphones, so no need to make changes during the wizard.

**Comment by Elfman72** [comment]
Thanks for the reply.

I may have not done it in that exact order since I did install other synocommunity packages.  I think I installed SAB first.  Also, I didn't manually install Git or Python but let the dependent packages install them for me.

Checking the Package center logs simply shoes successful install (and uninstall since I tried re-installing).  I did try the Headphones custom and left it on the default branch with the same result "Failed to run the package service" message.  So I'm not sure what to try next and really appreciate the help.

**Comment by Dr-Bean** [comment]
Nothing wrong with installing other packages, I mainly meant to verify you didn't manually create a headphones user before installation or edit any files afterwards, something like that.

Log in with Putty or any other ssh client (use `root`, use the password of the admin user to log in), and execute:
```
/var/packages/headphones/scripts/start-stop-status start
```
If that says nothing, the package should have started, so I assume it'll return an error. Paste that here. While you're there, you may also try this command, which may return a more detailed error:
```
su headphones -c "PATH=/usr/local/headphones/bin:/usr/local/headphones/env/bin:/usr/local/python/bin:/usr/local/git/bin:${PATH} /usr/local/headphones/env/bin/python /usr/local/headphones/share/Headphones/Headphones.py --daemon --pidfile /usr/local/headphones/var/headphones.pid --config /usr/local/headphones/var/config.ini --datadir /usr/local/headphones/var/"
```

**Comment by Elfman72** [comment]
So it looks like it doesn't  like my timezone for some reason.  Strange.

Here is the code for the first command:
```Starting Headphones ...
Traceback (most recent call last):
  File "/usr/local/headphones/share/Headphones/Headphones.py", line 23, in <module>
    from headphones import webstart, logger
  File "/volume1/@appstore/headphones/share/Headphones/headphones/__init__.py", line 67, in <module>
    SCHED = BackgroundScheduler()
  File "/usr/local/headphones/share/Headphones/lib/apscheduler/schedulers/base.py", line 61, in __init__
    self.configure(gconfig, **options)
  File "/usr/local/headphones/share/Headphones/lib/apscheduler/schedulers/base.py", line 95, in configure
    self._configure(config)
  File "/usr/local/headphones/share/Headphones/lib/apscheduler/schedulers/background.py", line 27, in _configure
    super(BackgroundScheduler, self)._configure(config)
  File "/usr/local/headphones/share/Headphones/lib/apscheduler/schedulers/base.py", line 576, in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
  File "/usr/local/headphones/share/Headphones/lib/tzlocal/unix.py", line 108, in get_localzone
    _cache_tz = _get_localzone()
  File "/usr/local/headphones/share/Headphones/lib/tzlocal/unix.py", line 91, in _get_localzone
    return pytz.timezone(etctz.replace(' ', '_'))
  File "/usr/local/headphones/share/Headphones/lib/pytz/__init__.py", line 180, in timezone
    raise UnknownTimeZoneError(zone)
pytz.exceptions.UnknownTimeZoneError: 'Timezone/Pacific'```

And here is the error from the second command(Looks to be the same timezone issue):

```Traceback (most recent call last):
  File "/usr/local/headphones/share/Headphones/Headphones.py", line 23, in <module>
    from headphones import webstart, logger
  File "/volume1/@appstore/headphones/share/Headphones/headphones/__init__.py", line 67, in <module>
    SCHED = BackgroundScheduler()
  File "/usr/local/headphones/share/Headphones/lib/apscheduler/schedulers/base.py", line 61, in __init__
    self.configure(gconfig, **options)
  File "/usr/local/headphones/share/Headphones/lib/apscheduler/schedulers/base.py", line 95, in configure
    self._configure(config)
  File "/usr/local/headphones/share/Headphones/lib/apscheduler/schedulers/background.py", line 27, in _configure
    super(BackgroundScheduler, self)._configure(config)
  File "/usr/local/headphones/share/Headphones/lib/apscheduler/schedulers/base.py", line 576, in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
  File "/usr/local/headphones/share/Headphones/lib/tzlocal/unix.py", line 108, in get_localzone
    _cache_tz = _get_localzone()
  File "/usr/local/headphones/share/Headphones/lib/tzlocal/unix.py", line 91, in _get_localzone
    return pytz.timezone(etctz.replace(' ', '_'))
  File "/usr/local/headphones/share/Headphones/lib/pytz/__init__.py", line 180, in timezone
    raise UnknownTimeZoneError(zone)
pytz.exceptions.UnknownTimeZoneError: 'Timezone/Pacific'```

**Comment by Dr-Bean** [comment]
Oh right. We've seen that one before: https://github.com/SynoCommunity/spksrc/issues/1846

**Comment by Elfman72** [comment]
Done and done.  Setting to GMT-0:00, starting the package, then rolling back my timezone seemed to work.

Thanks so much for your help!
