### ISSUE TITLE
Octoprint won't start on synology DS214+

### ISSUE THREAD

**Issue by roja75** [SynoCommunity/spksrc#2386]
_For new Package Requests, see the guidelines_  
### Setup

_Package Name:_ Octoprint
_Package Version:_ 20160321_4

_NAS Model:_ DS214+
_NAS Architecture:_ synology_armadaxp_ds214+
_DSM version:_ 6.0.1-7393
### Expected behavior

package failed to run
### Actual behavior

Start octoprint
### Steps to reproduce

_1._ install package
_2._ execute octoprint
_3._ pop up "could not run the service package.''
#### Package log

_Check Package Center or `/usr/local/{package}/var/`_

``````
Insert the package log here
```non available
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
``````

Insert log here
```none available

**Comment by madvtak** [comment]
https://github.com/SynoCommunity/spksrc/issues/2207

Post in [here](https://github.com/SynoCommunity/spksrc/issues/2207), duplicate.

**Comment by tareko** [comment]
I am similarly also facing this issue.

I was able to move a bit forward by trying 'run' and then using pip to install the following dependencies:

```pip install sockjs-tornado flask-login flask-principal flask-babel flask-assets watchdog```

However, I am now stuck with the following error:

```
r@r:/usr/local/octoprint/share/OctoPrint# ./run 
/volume1/@appstore/octoprint/share/OctoPrint/src/octoprint/server/__init__.py:11: ExtDeprecationWarning: Importing flask.ext.login is deprecated, use flask_login instead.
  from flask.ext.login import LoginManager, current_user
/volume1/@appstore/octoprint/share/OctoPrint/src/octoprint/server/__init__.py:12: ExtDeprecationWarning: Importing flask.ext.principal is deprecated, use flask_principal instead.
  from flask.ext.principal import Principal, Permission, RoleNeed, identity_loaded, UserNeed
/volume1/@appstore/octoprint/share/OctoPrint/src/octoprint/server/__init__.py:13: ExtDeprecationWarning: Importing flask.ext.babel is deprecated, use flask_babel instead.
  from flask.ext.babel import Babel, gettext, ngettext
/volume1/@appstore/octoprint/share/OctoPrint/src/octoprint/server/__init__.py:14: ExtDeprecationWarning: Importing flask.ext.assets is deprecated, use flask_assets instead.
  from flask.ext.assets import Environment, Bundle
Traceback (most recent call last):
  File "./run", line 21, in <module>
    import octoprint
  File "/volume1/@appstore/octoprint/share/OctoPrint/src/octoprint/__init__.py", line 4, in <module>
    from octoprint.server import Server
  File "/volume1/@appstore/octoprint/share/OctoPrint/src/octoprint/server/__init__.py", line 16, in <module>
    from watchdog.observers import Observer
  File "/usr/lib/python2.7/site-packages/watchdog/observers/__init__.py", line 63, in <module>
    from .inotify import InotifyObserver as Observer
  File "/usr/lib/python2.7/site-packages/watchdog/observers/inotify.py", line 74, in <module>
    from .inotify_buffer import InotifyBuffer
  File "/usr/lib/python2.7/site-packages/watchdog/observers/inotify_buffer.py", line 20, in <module>
    from watchdog.observers.inotify_c import Inotify
  File "/usr/lib/python2.7/site-packages/watchdog/observers/inotify_c.py", line 50, in <module>
    libc = _load_libc()
  File "/usr/lib/python2.7/site-packages/watchdog/observers/inotify_c.py", line 34, in _load_libc
    libc_path = ctypes.util.find_library('c')
  File "/usr/lib/python2.7/ctypes/util.py", line 242, in find_library
    raise RuntimeError("can not find library %s" % name)
RuntimeError: can not find library
```

**Comment by monochromec** [comment]
Same happens with pyinotify. 

Strongly suggest to use a more up-to-date version (such as the one in Debian's libpython2.7-stdlib, version 2.7.9-2+deb8u1).

**Comment by Safihre** [comment]
Updates (like proper DSM6 support) will be handled in #3128.
