### ISSUE TITLE
Syncthing 0.13.4-9 (internal v0.13.8) panic at startup

### ISSUE THREAD

**Issue by ugumba** [SynoCommunity/spksrc#2400]
### Setup
Syncthing 0.13.4-9
DS414
MARVELL Armada XP MV78230
DSM 6.0.1-7393 Update 1

### Expected behavior
Syncthing starts and synchronizes happily

### Actual behavior
Syncthing panics within 10 seconds - see log below.

### Steps to reproduce
Unknown - I believe this started crashing after a syncthing executable upgrade.

#### Package log
[empty]

#### Other logs
root@NAS:/var/packages/syncthing/target/var# cat panic-20160708-194453.log
[NRPZH] 19:44:41 INFO: syncthing v0.13.8 "Copper Cockroach" (go1.6.2 linux-arm) unknown-user@lx-buildslave.syncthing.net 2016-06-26 10:48:18 UTC
[NRPZH] 19:44:41 INFO: My ID: NRPZHG3-[xxxxxxxx   removed    xxxxxxx]
[NRPZH] 19:44:42 INFO: Single thread hash performance is ~13 MB/s
...
Panic at 2016-07-08T19:44:53+02:00
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x4 pc=0x366bc8]

goroutine 1 [running]:
panic(0x62a920, 0x10d1e030)
        /usr/local/go/src/runtime/panic.go:481 +0x330
sync/atomic.addUint64(0x10d0becc, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/sync/atomic/64bit_arm.go:31 +0x68
github.com/syncthing/syncthing/lib/db.readWriteTransaction.flush(0x1184f4d0, 0x10d0bec0, 0x1137b640)
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/db/leveldb_transactions.go:74 +0xbc
github.com/syncthing/syncthing/lib/db.readWriteTransaction.close(0x1184f4d0, 0x10d0bec0, 0x1137b640)
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/db/leveldb_transactions.go:59 +0x2c
github.com/syncthing/syncthing/lib/db.(*Instance).checkGlobals(0x10d0bec0, 0x11bda870, 0x4, 0x8, 0x10f73de4)
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/db/leveldb_dbinstance.go:643 +0x870
github.com/syncthing/syncthing/lib/db.NewFileSet(0x10ec2fe8, 0x4, 0x10d0bec0, 0x10d313dc)
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/db/set.go:104 +0x268
github.com/syncthing/syncthing/lib/model.(*Model).AddFolder(0x10d66160, 0x10ec2fe8, 0x4, 0x0, 0x0, 0x10f5d480, 0x1e, 0x0, 0x10d84500, 0x5, ...)
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/model/model.go:1378 +0xf8
main.syncthingMain(0x7efefe06, 0x19, 0x0, 0x0, 0x0, 0x0, 0x0, 0x6a4088, 0x1, 0x0, ...)
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:688 +0x18f8
main.main()
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:364 +0x748

**Comment by ugumba** [comment]
OK, no bigge.  Reverting to "syncthing.old" (which was 0.13.7) worked.
In turn, this autoupgraded to 0.13.10, which also seems to work fine.
If anyone's stuck on this, ssh in and 

cd /var/packages/syncthing/target/bin
mv syncthing.old syncthing
/var/packages/syncthing/scripts/start-stop-status start
