### ISSUE TITLE
HAProxy failed to start DSM 6

### ISSUE THREAD

**Issue by jdm2017** [SynoCommunity/spksrc#2712]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_HAProxy
_Package Version:_1.5.14-19

_NAS Model:_DS216j
_NAS Architecture:_Armada 385
_DSM version:_DSM 6.1-15047 Update 1

### Expected behavior
I installed the app HAProxy and Python package as requested, but will fail to start/run. No data stored when I go to view log. 

### Actual behavior
Status: Stopped
Error message: Failed to run the package service.

### Steps to reproduce
_1._Install Python version 2.7.13-16 ( this is the one HAProxy will automatically install)
_2._ Install HAProxy
_3._ Start the service

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
No logs available
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
No logs available

Insert log here
```
root@xxxx~# /var/log/synopkg.log
-ash: /var/log/synopkg.log: Permission denied
root@xxxx:~# /var/log/messages
-ash: /var/log/messages: Permission denied

**Comment by jdm2017** [comment]
<img width="847" alt="capture" src="https://cloud.githubusercontent.com/assets/26392456/24148653/c49e0994-0e0d-11e7-9f2c-9e8f601fcdaa.PNG">

**Comment by jdm2017** [comment]
<img width="551" alt="capture" src="https://cloud.githubusercontent.com/assets/26392456/24148710/e7ed8cd0-0e0d-11e7-8cbe-fb70a988a003.PNG">

**Comment by jdm2017** [comment]
<img width="844" alt="capture" src="https://cloud.githubusercontent.com/assets/26392456/24148738/0b1d6086-0e0e-11e7-8869-a40dc9b09105.PNG">

**Comment by chigy110** [comment]
Exakt Same Problem here:

Setup

_Package Name:_ HAProxy
_Package Version:_ 1.5.14-19

_NAS Model:_ DS916+
_NAS Architecture:_ INTEL Pentium N3710
_DSM version:_ DSM 6.1-15047 Update 2

**Comment by OBenned** [comment]
#2661

**Comment by tarzanek** [comment]
some logs from synopkg : 
```
2018/09/07 09:36:43     install haproxy 1.5.14-19 Begin postinst
Traceback (most recent call last):
  File "/usr/local/python/bin/virtualenv", line 11, in <module>
    sys.exit(main())
  File "/var/packages/python/target/lib/python2.7/site-packages/virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "/var/packages/python/target/lib/python2.7/site-packages/virtualenv.py", line 945, in create_environment
    download=download,
  File "/var/packages/python/target/lib/python2.7/site-packages/virtualenv.py", line 901, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/var/packages/python/target/lib/python2.7/site-packages/virtualenv.py", line 797, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /usr/local/haproxy/env/bin/python - setuptools pip wheel failed with error code 1
Traceback (most recent call last):
  File "/usr/local/haproxy/app/setup.py", line 2, in <module>
    from application import db, direct
  File "/volume1/@appstore/haproxy/app/application/direct.py", line 3, in <module>
    from pyextdirect.configuration import (create_configuration, expose, LOAD,
ImportError: No module named pyextdirect.configuration
```

and later on it causes:
```
2018/09/07 09:37:02     (system) trigger haproxy 1.5.14-19 Begin start-stop-status start
Starting HAProxy ...
[ALERT] 249/093702 (14316) : Could not open configuration file /usr/local/haproxy/var/haproxy.cfg : No such file or directory
```

**Comment by tarzanek** [comment]
```
wget https://bootstrap.pypa.io/get-pip.py
python get-pip.py
pip install pyextdirect
ln -s /usr/lib/python2.7/site-packages/pyextdirect /volume1/\@appstore/python/lib/python2.7/site-packages/
```
after this dirty hack you can get
```
[ALERT] 249/100235 (15468) : Proxy 'https': no SSL certificate specified for bind ':5443' at [/usr/local/haproxy/var/haproxy.cfg:34] (use 'crt').
```

**Comment by tarzanek** [comment]
```
cat /usr/syno/etc/certificate/system/default/privkey.pem >> /usr/local/haproxy/var/crt/default.pem
cat /usr/syno/etc/certificate/system/default/fullchain.pem >> /usr/local/haproxy/var/crt/default.pem
```
got the ssl working

**Comment by tarzanek** [comment]
neverthless, config UI doesn't really work because:
```
2018-09-07T10:09:39+02:00 nas synoscgi_SYNO.Core.Package.Control_1_start[26825]: servicecfg_internal_lib.c:187 Failed to start job [pkgctl-haproxy][0xD900 manager.cpp:204]
2018-09-07T10:09:39+02:00 nas [ 7780.775455] init: pkgctl-haproxy pre-start process (27472) terminated with status 1
2018-09-07T10:09:40+02:00 nas synoscgi_SYNO.Core.Package.Control_1_start[26825]: service_initjob_action.c:27 InitJobStart failed, [0xD900 manager.cpp:204]
2018-09-07T10:09:40+02:00 nas synoscgi_SYNO.Core.Package.Control_1_start[26825]: pkgstartstop.cpp:367 Failed to start pkgctl-haproxy (err=-1) [0xD900 manager.cpp:204]
```

**Comment by tarzanek** [comment]
manual config of /usr/local/haproxy/var/haproxy.cfg
works

**Comment by cdalvaro** [comment]
Please, add support for Synology DS918+ architecture

**Comment by kamahat** [comment]
> it also seems that in DSM 6.x **Control Panel / Application Portal / Reverse Proxy** can handle a lot of stuff that haproxy would do

Ha-proxy offer other services that just a http/s proxy : Active/Active proxy,  proxy for non http protocl like MQTT

**Comment by mreid-tt** [comment]
hey @jdm2017 — I’ve made a pass at modernizing the HAProxy package in #6951. If you have some time, you can download and install it from the build artifacts and share any feedback. Instructions for installing pre-release packages are available in our [wiki](https://github.com/SynoCommunity/spksrc/wiki/Frequently-Asked-Questions#download-development-and-pre-release-packages-created-by-github-build-action).
