### ISSUE TITLE
Sickbeard_custom suddenly stopped working

### ISSUE THREAD

**Issue by Tiwas** [SynoCommunity/spksrc#2725]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_sickbeard_custom
_Package Version:_20151220-4

_NAS Model:_DS412+
_NAS Architecture:_Intel Atom D2700
_DSM version:_DSM 6.1-15047 Update 2

### Expected behavior
Tell us what should happen

### Actual behavior
Sickbeard has been working for a pretty long time. Suddenly it stopped working after it seems the NAS restarted for some reason (I didn't lose file access, so it wasn't a complete restart).

Package fails to start. Manual GUI start says "Unable to start package service". Manual start from command line says:

> root@DiskStation:/usr/local/sickbeard-custom/var#  /usr/local/python/bin/python /usr/local/sickbeard-custom/var/SickBeard/SickBeard.py --pidfile /usr/local/sickbeard-custom/var/sickbeard-custom.pid --config /usr/local/sickbeard-custom/var/config.ini --datadir /usr/local/sickbeard-custom/var/ --daemon --nolaunch
> Traceback (most recent call last):
>   File "/usr/local/sickbeard-custom/var/SickBeard/SickBeard.py", line 494, in <module>
>     SickRage().start()
>   File "/usr/local/sickbeard-custom/var/SickBeard/SickBeard.py", line 242, in start
>     sickbeard.initialize(consoleLogging=self.console_logging)
>   File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/__init__.py", line 1100, in initialize
>     helpers.manage_torrents_url(reset=True)
>   File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1897, in manage_torrents_url
>     sickbeard.CLIENT_WEB_URLS['torrent'] = ('', torrent_ui_url)[test_exists(torrent_ui_url)]
>   File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1886, in test_exists
>     h = requests.head(url)
>   File "/usr/local/sickbeard-custom/var/SickBeard/lib/requests/api.py", line 93, in head
>     return request('head', url, **kwargs)
>   File "/usr/local/sickbeard-custom/var/SickBeard/lib/requests/api.py", line 53, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/usr/local/sickbeard-custom/var/SickBeard/lib/requests/sessions.py", line 454, in request
>     prep = self.prepare_request(req)
>   File "/usr/local/sickbeard-custom/var/SickBeard/lib/requests/sessions.py", line 388, in prepare_request
>     hooks=merge_hooks(request.hooks, self.hooks),
>   File "/usr/local/sickbeard-custom/var/SickBeard/lib/requests/models.py", line 293, in prepare
>     self.prepare_url(url, params)
>   File "/usr/local/sickbeard-custom/var/SickBeard/lib/requests/models.py", line 353, in prepare_url
>     raise MissingSchema(error)
> requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?

sickrage.log doesn't contain anything about any error, only repeating the following for each restart attempt

> 2017-03-31 23:56:22 DEBUG    MAIN :: Parsed Show.Name.S02E03.HDTV.XviD-RLSGROUP into Show Name - S02E03 [GROUP: RLSGROUP] [ABD: False] [ANIME: False] [whichReg: [u'standard']]
> 2017-03-31 23:56:22 DEBUG    MAIN :: Found codec for 'Show Name: Ep Name'.
> 2017-03-31 23:56:22 DEBUG    MAIN :: Episode has no release group, replacing it with 'RLSGROUP'
> 2017-03-31 23:56:22 DEBUG    MAIN :: formatting pattern: %SN - S%0SE%0E - %EN - %RG - %QN -> Show Name - S02E03 - Ep Name - RLSGROUP - 720p HDTV
> 2017-03-31 23:56:23 DEBUG    MAIN :: Parsed Show.Name.S02E03.HDTV.XviD-RLSGROUP into Show Name - S02E03 [GROUP: RLSGROUP] [ABD: False] [ANIME: False] [whichReg: [u'standard']]
> 2017-03-31 23:56:23 DEBUG    MAIN :: Found codec for 'Show Name: Ep Name'.
> 2017-03-31 23:56:23 DEBUG    MAIN :: formatting pattern: Season %S -> Season 2
> 2017-03-31 23:56:23 DEBUG    MAIN :: Trying to parse Show Name - S02E03 - Ep Name - RLSGROUP - 720p HDTV.ext
> 2017-03-31 23:56:23 DEBUG    MAIN :: Parsed Show Name - S02E03 - Ep Name - RLSGROUP - 720p HDTV.ext into Show Name - S02E03 [ABD: False] [ANIME: False] [whichReg: [u'standard']]
> 2017-03-31 23:56:23 DEBUG    MAIN :: The name Show Name - S02E03 - Ep Name - RLSGROUP - 720p HDTV.ext parsed into Show Name - S02E03 [ABD: False] [ANIME: False] [whichReg: [u'standard']]

### Steps to reproduce
_1._Start from UI or ssh

_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
[sickrage.zip](https://github.com/SynoCommunity/spksrc/files/887049/sickrage.zip)
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
[synopkg.zip](https://github.com/SynoCommunity/spksrc/files/887050/synopkg.zip)
```

**Comment by Tiwas** [comment]
Ok, I found this, which solved the problem (I think): [https://github.com/SickRage/SickRage/wiki/FAQ%27s-and-Fixes#i-have-problems-updating-or-my-installation-got-corrupt-what-now](https://github.com/SickRage/SickRage/wiki/FAQ%27s-and-Fixes#i-have-problems-updating-or-my-installation-got-corrupt-what-now)
