### ISSUE TITLE
Unable to start sickrage

### ISSUE THREAD

**Issue by masterxdk** [SynoCommunity/spksrc#2842]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_
_Package Version:_

_NAS Model: Synology DS1515+
_NAS Architecture: x86
_DSM version: DSM 6.1.3-15152 Update 1

### Expected behavior
Application should start

### Actual behavior
Application wont start, fails with "Failed to run the package service"

### Steps to reproduce
_1. Start application from Package Center

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
Nothing valuable, just searches for episodes (old logs)
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
2017/07/25 20:53:59 start sickbeard-custom: begin to start version 20151220-4
2017/07/25 20:53:59 start sickbeard-custom 20151220-4 Begin pre-load apparmor
2017/07/25 20:53:59 start sickbeard-custom 20151220-4 End pre-load apparmor ret=[0]
2017/07/25 20:53:59 start sickbeard-custom 20151220-4 Begin start-stop-status start
Starting SickBeard Custom ...
Traceback (most recent call last):
  File "/usr/local/sickbeard-custom/var/SickBeard/SickBeard.py", line 548, in <module>
    SickRage().start()
  File "/usr/local/sickbeard-custom/var/SickBeard/SickBeard.py", line 247, in start
    sickbeard.CFG = ConfigObj(sickbeard.CONFIG_FILE, encoding='UTF-8')
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/configobj.py", line 1219, in __init__
    self._load(infile, configspec)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/configobj.py", line 1302, in _load
    raise error
configobj.ConfigObjError: Parsing failed with several errors.
First error at line 1051.
2017/07/25 20:54:04 start sickbeard-custom 20151220-4 End start-stop-status start ret=[1]
2017/07/25 20:54:04 (system) trigger sickbeard-custom 20151220-4 Begin start-stop-status stop
SickBeard Custom is not running
2017/07/25 20:54:04 (system) trigger sickbeard-custom 20151220-4 End start-stop-status stop ret=[0]
2017/07/25 20:54:04 (system) trigger sickbeard-custom 20151220-4 Begin unload apparmor
2017/07/25 20:54:04 (system) trigger sickbeard-custom 20151220-4 End unload apparmor ret=[0]
2017/07/25 20:54:05 stop sickbeard-custom: begin to stop version 20151220-4
2017/07/25 20:54:05 stop sickbeard-custom: stop version 20151220-4 successfully, result 0
2017/07/25 20:54:05 start sickbeard-custom: start version 20151220-4 failed, result 1

**Comment by masterxdk** [comment]
Issue resolved. Config was fucked after update
