### ISSUE TITLE
Add "acoustid" plugin support in beets thanks to chromaprint

### ISSUE THREAD

**Issue by Godtux** [SynoCommunity/spksrc#2927]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_Chromaprint
_Package Version:_1.3.2-4

_NAS Model:_DS916+
_NAS Architecture:_Intel
_DSM version:_DSM 6.1.3-15152 Update 4

### Expected behavior
using beet to import music, the acoustic fingerprint allow music recognition

### Actual behavior
When using beets, with a call to the chroma plugin, it complains that it can't find the acoustid module.

This setup used to work this summer.
I have booth python 2.7 and 3 installed (i tried to remove the 3 with no effect).
I tested my beet configuration file on a linux mint computer and it worked.
I tried to remove and reinstall beet and chromaprint with no effect.

### Steps to reproduce
_1._configure beet with the chroma plugin
_2._launch beet
_3._see log 

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
vincent@NAS916:/var/services/music/in$ /usr/local/beets/env/bin/beet import .
** error loading plugin chroma:
Traceback (most recent call last):
  File "/usr/local/beets/env/lib/python2.7/site-packages/beets/plugins.py", line 254, in load_plugins
    namespace = __import__(modname, None, None)
  File "/usr/local/beets/env/lib/python2.7/site-packages/beetsplug/chroma.py", line 27, in <module>
    import acoustid
ImportError: No module named acoustid

No files imported from /volume1/music/in
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```

```

**Comment by ymartin59** [comment]
Please refer to package description: https://synocommunity.com/package/beets
<<Chromaprint/Acoustid and ReplayGain plugins are not available because of lacking dependencies.>>

I plan support of Acoustid plugin with beets next update. BUT, chromaprint package available in repository is built for DSM 5.2 and may not work on DSM 6.

**Comment by ymartin59** [comment]
I have just published "beets" update, and "acoustid" should work if plugin enable and "chromaprint" package is installed.
I am lazy and too busy, so shame on me, I have not even tested...
May you please update and confirm or report issue here. Thank you in advance for your help

**Comment by michaeltieso** [comment]
@ymartin59 Just tried it but getting
> chroma: fingerprint generation failed: fpcalc not found

**Comment by ymartin59** [comment]
I have no idea how I may say it clearer... Please install "Chromaprint" package: https://synocommunity.com/package/beets

**Comment by michaeltieso** [comment]
@ymartin59 I like that you edited your last incredibly rude reply. Yes, Chromaprint package has always been installed while testing this. It's required for FileBot too. You're welcome for the time I spent testing this for you. `fpcalc` is **not** available in `/usr/local/bin`. I did a search and found only `/volume1/@appstore/chromaprint/bin/fpcalc`.

**Comment by ymartin59** [comment]
I will not rebuild package for a lacking symlink. I propose you either create it as root:
  ln -s /volume1/@appstore/chromaprint/bin/fpcalc /usr/local/bin/fpcalc
Or either append location to PATH=/volume1/@appstore/chromaprint/bin:$PATH
I guess beets should be happy then.

**Comment by michaeltieso** [comment]
You do whatever you want. It's not my project. I'm just stating the facts.

**Comment by m4tt075** [comment]
@michaeltieso OK. Thanks for testing and reporting.
@ymartin59 One more business trip next week and then I should have more time to help in the second half of December / early January. Happy to further test this and PR some fixes, including the soft link, if you want me to. Please just let me know...

**Comment by ymartin59** [comment]
@michaeltieso My comment was there to propose immediate work-around so that you get beets acoustid for your own usage... until I report change to package.
