### ISSUE TITLE
Sickbeard-custom doesn't start after python 2.7.14-17 update

### ISSUE THREAD

**Issue by alexey-pimenov** [SynoCommunity/spksrc#3111]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ SickBeard Custom(medusa)
_Package Version:_ 20180115-5(from Saphire's fork)

_NAS Model:_ Sickbeard Custom
_NAS Architecture:_ DS218 Play
_DSM version:_ DSM 6.1.4-15217 Update 5

### Expected behavior
Sickbeard successfully starts after updating python

### Actual behavior
Medusa fail's to start with python error

### Steps to reproduce
_1._ Upgrade python to 2.7.14-17

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Starting sickbeard-custom command /volume1/@appstore/sickbeard-custom/env/bin/python /volume1/@appstore/sickbeard-custom/var/SickBeard/SickBeard.py --daemon --pidfile /volume1/@appstore/sickbeard-custom/var/sickbeard-custom.pid --config /volume1/@appstore/sickbeard-custom/var/config.ini --datadir /volume1/@appstore/sickbeard-custom/var/ 
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/SickBeard.py", line 4, in <module>
    from medusa.__main__ import main
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/__main__.py", line 65, in <module>
    from medusa import (
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/providers/__init__.py", line 10, in <module>
    from medusa.providers.nzb import (
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/providers/nzb/anizb.py", line 14, in <module>
    from medusa.providers.nzb.nzb_provider import NZBProvider
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/providers/nzb/nzb_provider.py", line 8, in <module>
    from medusa.providers.generic_provider import GenericProvider
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/providers/generic_provider.py", line 18, in <module>
    from medusa import (
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/config.py", line 30, in <module>
    from medusa.version_checker import CheckVersion
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/version_checker.py", line 31, in <module>
    from medusa.github_client import get_github_repo
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/github_client.py", line 6, in <module>
    import github
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/github/__init__.py", line 37, in <module>
    from MainClass import Github, GithubIntegration
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/github/MainClass.py", line 34, in <module>
    import jwt
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/jwt/__init__.py", line 19, in <module>
    from .api_jwt import (
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/jwt/api_jwt.py", line 8, in <module>
    from .api_jws import PyJWS
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/jwt/api_jws.py", line 7, in <module>
    from .algorithms import (
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/jwt/algorithms.py", line 8, in <module>
    from .utils import (
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/jwt/utils.py", line 8, in <module>
    from cryptography.hazmat.primitives.asymmetric.utils import (
  File "/var/packages/python/target/lib/python2.7/site-packages/cryptography/hazmat/primitives/asymmetric/utils.py", line 9, in <module>
    from asn1crypto.algos import DSASignature
  File "/var/packages/python/target/lib/python2.7/site-packages/asn1crypto/algos.py", line 24, in <module>
    from ._int import fill_width
  File "/var/packages/python/target/lib/python2.7/site-packages/asn1crypto/_int.py", line 56, in <module>
    from ._perf._big_num_ctypes import libcrypto
  File "/var/packages/python/target/lib/python2.7/site-packages/asn1crypto/_perf/_big_num_ctypes.py", line 35, in <module>
    libcrypto_path = find_library(b'crypto' if sys.version_info < (3,) else 'crypto')
  File "/var/packages/python/target/lib/python2.7/ctypes/util.py", line 274, in find_library
    return _findSoname_ldconfig(name) or _get_soname(_findLib_gcc(name))
  File "/var/packages/python/target/lib/python2.7/ctypes/util.py", line 107, in _findLib_gcc
    temp.close()
  File "/var/packages/python/target/lib/python2.7/tempfile.py", line 431, in close
    self.unlink(self.name)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/init/filesystem.py", line 108, in patched_output
    return handle_output(f(*args, **kwargs))
TypeError: remove() takes exactly 1 argument (2 given)
python: posix-lock.c:137: get_lock_object: Assertion `!"sizeof lock obj"' failed.
```

### Workaround:
1.  Backup /var/packages/sickbeard-custom/target/var
2.  Uninstall sickbeard-custom and python
3.  Manually install python 2.7.13-16 and sickbeard-custom
4.  Restore backup

**Comment by ymartin59** [comment]
Sorry for inconvenience. I have deactivated newer version.

**Comment by ThorEgilGit** [comment]
Same problem with Deluge.
So - I can just uninstall and then install again, and I will be back to previous version?

**Comment by Kilay** [comment]
Is it a way to downgrade without having to uninstall python ? I have 4 dependent packages and don't want to loose configuration by uninstalling them.

**Comment by alexey-pimenov** [comment]
@Kilay I've not found any official way to downgrade package without uninstalling it first.
So I've just manually created sickbeard and configuration backup in tar archive.
Downgraded python.
Then reinstalled sickbeard(unticked option to run it after installation) and just untarred backup files over fresh installation.

So it might work if you manually create backup for each python-dependent package data.

**Comment by Kilay** [comment]
Was thinking of manually installing the previous python version but I don't think that spk files are available somewhere for all synology architecture.
And I cannot build it myself.

**Comment by stefaang** [comment]
Please try to patch Medusa with this: https://github.com/pymedusa/Medusa/pull/3619

**Comment by Kilay** [comment]
I confirm that I was able to start Sickbeard/Medusa with Python 2.7.14-17 with your patch.
Thank you stefaang.

**Comment by Safihre** [comment]
What model Synology do you guys have?
This is quite a strange error and wonder why it's specific to this new Python.

**Comment by ThorEgilGit** [comment]
I have a Synology DS1517+
Deluge up and running again after downgrading Python.

**Comment by Safihre** [comment]
I recompiled Python 2.7.14 package but now with the correct `start-stop-deamon` and hopefully a fix for other crashes related to `cryptography`. [Would you like to give it a try?](https://github.com/Safihre/spksrc/releases/tag/python-recompile3)

Now that we also got your attention, we have new packages that we are testing for [NZBGet, SABnzbd, CouchPotato, Sickrage, SickBeard Custom, Syncthing, Mono, Jackett, Tvheaded, Sonarr and Radarr](https://github.com/SynoCommunity/spksrc/issues/2945#issuecomment-357008518).
Would you be willing to try those? If you have Python 2.7.13 or 2.7.14, we want to know if they work in all cases. Let us know if you test 👍 Others tested these packages already, but more testing is better clearly!
Thank you! 🥇

**Comment by MichelRabozee** [comment]
Hi Safihre,
I manually installed the python_avoton-6.1_2.7.14-17.spk you recompiled (I have 1515+ DSM DSM 6.1.4-15217 Update 5) and this is even worse, my SickBeard does not start at all now; it was at least still running with broken 2.7.14 update ("only" crypto did not work when invoking autoProcessTV.py).
Do I need to do other things than just manually install your recompiled version ?
Thank you for the support !
Michel

**Comment by ymartin59** [comment]
Please try following work-around:
- download package from https://packages.synocommunity.com/python/16/python.v16.f4458%5Bx86-braswell-bromolow-cedarview-avoton%5D.spk
- use Package Center "manual install" to downgrade version
Hope this helps

**Comment by MichelRabozee** [comment]
Thank you for the package ! Sadly, it the package manager says as I have version 2.7.14, I cannot downgrade to 2.7.13 :-(

Is there a way to trick the 2.7.14 info to make the system think it is a lower version ?

**Comment by Kilay** [comment]
I tried to mabually install python from your link above and got an error : Failed to update "Python".

Here is 
```
2018/01/23 09:08:20     upgrade python 2.7.14-17 Begin preupgrade
/volume1/@tmp/pkginstall/scripts/service-setup: line 7: type: service_preupgrade: not found
/volume1/@tmp/pkginstall/scripts/service-setup: line 7: type: service_save: not found
2018/01/23 09:08:21     upgrade python 2.7.14-17 End preupgrade ret=[0]
2018/01/23 09:08:21     upgrade python 2.7.14-17 Begin preuninst
/var/packages/python/scripts/service-setup: line 7: type: service_preuninst: not found
2018/01/23 09:08:21     upgrade python 2.7.14-17 End preuninst ret=[0]
2018/01/23 09:08:21     upgrade python 2.7.14-17 Begin /bin/rm -rf /volume1/@appstore/python
2018/01/23 09:08:27     upgrade python 2.7.14-17 End /bin/rm -rf /volume1/@appstore/python ret=[0]
2018/01/23 09:08:28     upgrade python 2.7.14-17 Begin postuninst
/var/packages/python/scripts/service-setup: line 7: type: service_postuninst: not found
2018/01/23 09:08:28     upgrade python 2.7.14-17 End postuninst ret=[0]
2018/01/23 09:08:28     upgrade python: Uninstall 2.7.14-17 successfully
2018/01/23 09:08:28     upgrade python 2.7.14-17 Begin preinst
/volume1/@tmp/pkginstall/scripts/service-setup: line 7: type: service_preinst: not found
2018/01/23 09:08:28     upgrade python 2.7.14-17 End preinst ret=[0]
2018/01/23 09:08:28     upgrade python 2.7.14-17 Begin /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/python
2018/01/23 09:08:28     upgrade python 2.7.14-17 End /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/python ret=[0]
2018/01/23 09:08:29     upgrade python 2.7.14-17 Begin /bin/mkdir -p /var/packages/python
2018/01/23 09:08:29     upgrade python 2.7.14-17 End /bin/mkdir -p /var/packages/python ret=[0]
2018/01/23 09:08:29     upgrade python 2.7.14-17 Begin /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/python/INFO
2018/01/23 09:08:29     upgrade python 2.7.14-17 End /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/python/INFO ret=[0]
2018/01/23 09:08:29     upgrade python 2.7.14-17 Begin /bin/rm -rf /var/packages/python/scripts
2018/01/23 09:08:29     upgrade python 2.7.14-17 End /bin/rm -rf /var/packages/python/scripts ret=[0]
2018/01/23 09:08:29     upgrade python 2.7.14-17 Begin /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/python/scripts
2018/01/23 09:08:29     upgrade python 2.7.14-17 End /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/python/scripts ret=[0]
2018/01/23 09:08:29     upgrade python 2.7.14-17 Begin /bin/rm -rf /var/packages/python/conf
2018/01/23 09:08:29     upgrade python 2.7.14-17 End /bin/rm -rf /var/packages/python/conf ret=[0]
2018/01/23 09:08:29     upgrade python 2.7.14-17 Begin /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/python/conf
2018/01/23 09:08:29     upgrade python 2.7.14-17 End /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/python/conf ret=[0]
2018/01/23 09:08:29     upgrade python 2.7.14-17 Begin postinst
```

**Comment by Safihre** [comment]
Closing this, the new Python package should fix these problems.
If you still experience problems after the 2.7.14-18 update, please create a new issue.
