### ISSUE TITLE
Deluge: Failed to start package service

### ISSUE THREAD

**Issue by BjornB2** [SynoCommunity/spksrc#3226]
### Setup
_Pagage name:_ Deluge
_Package Version:_ 1.3.15-8
_Python version:_ 2.7.14-18

_NAS Model:_ DS916+ 8GB
_NAS Architecture:_
_DSM version:_ 6.1.5-15254 Update 1

### Expected behavior
Deluge should start

### Actual behavior
Updated both DSM, Deluge and Python to latest version. Everything worked before.
After trying to start the package, I get a failure message "Failed to start package service". 
deluged.log and deluge-web.log don't show anything after the update.

I tried removing the var/*.state, var/*.pid and var/state/* but that didn't help.

### Steps to reproduce
_1._ See above
_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
Last log entries deluged.log
This is from before running the update.

```
[INFO    ] 09:51:34 rpcserver:226 Deluge client disconnected: Connection to the other side was lost in a non-clean fashion: Connection lost.
[INFO    ] 09:51:34 rpcserver:226 Deluge client disconnected: Connection to the other side was lost in a non-clean fashion: Connection lost.
[INFO    ] 09:51:34 rpcserver:226 Deluge client disconnected: Connection to the other side was lost in a non-clean fashion: Connection lost.
[INFO    ] 09:51:34 rpcserver:226 Deluge client disconnected: Connection to the other side was lost in a non-clean fashion: Connection lost.
[INFO    ] 09:52:07 daemon:196 Waiting for components to shutdown..
[INFO    ] 09:52:07 torrentmanager:737 Saving the state at: /usr/local/deluge/var/state/torrents.state
[INFO    ] 09:52:10 torrentmanager:780 Successfully loaded fastresume file: /usr/local/deluge/var/state/torrents.fastresume
[INFO    ] 09:52:10 torrentmanager:826 Saving the fastresume at: /usr/local/deluge/var/state/torrents.fastresume
[INFO    ] 09:52:10 rpcserver:226 Deluge client disconnected: Connection to the other side was lost in a non-clean fashion: Connection lost.
[INFO    ] 09:52:10 daemon:196 Waiting for components to shutdown..
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_ deluge-web.log
This is from before running the update.

```
[INFO    ] 11:29:51 json_api:795 Adding torrent from file `tmp68UBjU.torrent` with options `{u'add_paused': False, u'max_download_speed': -1, u'move_completed_path': u'/volume1/promo', u'download_location': u'/volume1/downloads/tmp', u'compact_allocation': False, u'max_upload_speed': -1, u'prioritize_first_last_pieces': False, u'max_upload_slots': -1, u'file_priorities': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], u'move_completed': True, u'max_connections': -1}`
[INFO    ] 11:29:51 json_api:795 Adding torrent from file `tmpdxmMn1.torrent` with options `{u'add_paused': False, u'max_download_speed': -1, u'move_completed_path': u'/volume1/promo', u'download_location': u'/volume1/downloads/tmp', u'compact_allocation': False, u'max_upload_speed': -1, u'prioritize_first_last_pieces': False, u'max_upload_slots': -1, u'file_priorities': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], u'move_completed': True, u'max_connections': -1}`
[INFO    ] 14:23:26 auth:327 Login success (ClientIP 127.0.0.1)
[INFO    ] 15:45:37 auth:327 Login success (ClientIP 127.0.0.1)
[INFO    ] 09:43:21 auth:327 Login success (ClientIP 127.0.0.1)
[INFO    ] 09:52:07 client:224 Connection lost to daemon at 127.0.0.1:58846 reason: Connection to the other side was lost in a non-clean fashion: Connection lost.
[INFO    ] 09:52:07 server:696 Shutting down webserver
```

**Comment by Safihre** [comment]
Could you try to start Deluge and then read the last lines from `/var/log/synopkg.log` related to Deluge?
Can also delete `/var/log/synopkg.log` first and then try to start Deluge, because the file can be crazy long.

**Comment by BjornB2** [comment]
```
2018/03/16 11:15:14 start deluge: begin to start version 1.3.15-8
2018/03/16 11:15:14 start deluge 1.3.15-8 Begin pre-load apparmor
2018/03/16 11:15:14 start deluge 1.3.15-8 End pre-load apparmor ret=[0]
2018/03/16 11:15:14 start deluge 1.3.15-8 Begin start-stop-status start
start-stop-daemon: unknown user deluge
start-stop-daemon: unknown user deluge
Starting Deluge ...
start-stop-daemon: unknown user deluge
start-stop-daemon: unknown user deluge
2018/03/16 11:15:17 start deluge 1.3.15-8 End start-stop-status start ret=[1]
2018/03/16 11:15:17 (system) trigger deluge 1.3.15-8 Begin start-stop-status stop
start-stop-daemon: unknown user deluge
start-stop-daemon: unknown user deluge
Deluge is not running
2018/03/16 11:15:17 (system) trigger deluge 1.3.15-8 End start-stop-status stop ret=[0]
2018/03/16 11:15:17 (system) trigger deluge 1.3.15-8 Begin unload apparmor
2018/03/16 11:15:17 (system) trigger deluge 1.3.15-8 End unload apparmor ret=[0]
2018/03/16 11:15:18 stop deluge: begin to stop version 1.3.15-8
2018/03/16 11:15:18 stop deluge: stop version 1.3.15-8 successfully, result 0
2018/03/16 11:15:18 start deluge: start version 1.3.15-8 failed, result 272
```

I see something about unknown user deluge, but I never had such user before. 
Manually created the user deluge in DSM. Error changed to this:

```
2018/03/16 11:18:49 start deluge: begin to start version 1.3.15-8
2018/03/16 11:18:49 start deluge 1.3.15-8 Begin pre-load apparmor
2018/03/16 11:18:49 start deluge 1.3.15-8 End pre-load apparmor ret=[0]
2018/03/16 11:18:49 start deluge 1.3.15-8 Begin start-stop-status start
Starting Deluge ...
Traceback (most recent call last):
  File "/usr/local/deluge/env/bin/deluged", line 11, in <module>
    load_entry_point('deluge==1.3.15', 'console_scripts', 'deluged')()
  File "/usr/local/deluge/env/lib/python2.7/site-packages/deluge-1.3.15-py2.7.egg/deluge/main.py", line 194, in start_daemon
    deluge.log.setupLogger(level=options.loglevel, filename=options.logfile)
  File "/usr/local/deluge/env/lib/python2.7/site-packages/deluge-1.3.15-py2.7.egg/deluge/log.py", line 65, in setupLogger
    filemode=filemode
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 1547, in basicConfig
    hdlr = FileHandler(filename, mode)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 913, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 943, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/usr/local/deluge/var/deluged.log'
2018/03/16 11:18:57 start deluge 1.3.15-8 End start-stop-status start ret=[0]
2018/03/16 11:18:57 start deluge: start version 1.3.15-8 successfully, result 0
```

Could this mean I need to chown the deluge files?

```
x@DS916P8G:/volume1/@appstore/deluge/var$ ls -la
total 41692
drwxr-sr-x 1  102 root      206 Mar 16 11:18 .
drwxr-xr-x 1  102 root       82 Dec 14 10:40 ..
-rw------- 1  102 root       89 Dec 17 19:57 auth
drwxr-sr-x 1 root root     5154 Mar 16 10:47 backup
-rw-r--r-- 1  102 root     2688 Dec 15 11:19 core.conf
-rw-r--r-- 1  102 root 42647118 Mar 16 09:52 deluged.log
-rw-r--r-- 1  102 root    21909 Mar 16 09:52 deluge-web.log
-rw-r--r-- 1 root root        6 Mar 16 11:18 deluge-web.pid
-rw-r--r-- 1  102 root      168 Dec 14 10:42 hostlist.conf.1.2
drwxr-sr-x 1  102 root        0 Dec 14 10:42 icons
drwxr-sr-x 1  102 root        0 Dec 14 10:42 plugins
drwxr-sr-x 1  102 root       44 Dec 14 10:42 ssl
drwxr-sr-x 1  102 root        0 Mar 16 10:47 state
-rw-r--r-- 1  102 root      557 Mar 16 09:52 web.conf
```

Thanks for your help!

**Comment by Safihre** [comment]
Very strange. 
You also got an update for Deluge you said?
Indeed you need a `chown` of the `var` directory to the `deluge` user.

**Comment by BjornB2** [comment]
Ok, after chown, deluge is running again 👍 
I looked back in the notifications and see I am mistaken about deluge being updated. I updated 13 packages at once and thought I saw Deluge as well. Sorry about that.

Thanks a lot for your help.

**Comment by Safihre** [comment]
Strange.
Hope this is a 1 off-thing.

**Comment by ThorEgilGit** [comment]
Hm, maybe I'll wait for 2.7.15 before I upgrade then.
