### ISSUE TITLE
InvalidObjectException(message:All is already granted by admin)

### ISSUE THREAD

**Issue by znguo** [SynoCommunity/spksrc#3287]
```
18/04/19 17:17:35 [main]: INFO metastore.HiveMetaStore: Added public role in metastore
18/04/19 17:17:35 [main]: DEBUG metastore.ObjectStore: Open transaction: count = 1, isActive = true at:
        org.apache.hadoop.hive.metastore.ObjectStore.grantPrivileges(ObjectStore.java:3912)
18/04/19 17:17:35 [main]: DEBUG metastore.ObjectStore: Open transaction: count = 2, isActive = true at:
        org.apache.hadoop.hive.metastore.ObjectStore.getMRole(ObjectStore.java:3527)
18/04/19 17:17:35 [main]: DEBUG metastore.ObjectStore: Commit transaction: count = 1, isactive true at:
        org.apache.hadoop.hive.metastore.ObjectStore.getMRole(ObjectStore.java:3533)
18/04/19 17:17:35 [main]: DEBUG metastore.ObjectStore: Open transaction: count = 2, isActive = true at:
        org.apache.hadoop.hive.metastore.ObjectStore.listPrincipalGlobalGrants(ObjectStore.java:4397)
18/04/19 17:17:35 [main]: DEBUG metastore.ObjectStore: Commit transaction: count = 1, isactive true at:
        org.apache.hadoop.hive.metastore.ObjectStore.listPrincipalGlobalGrants(ObjectStore.java:4407)
18/04/19 17:17:35 [main]: DEBUG metastore.ObjectStore: Rollback transaction, isActive: true at:
        org.apache.hadoop.hive.metastore.ObjectStore.grantPrivileges(ObjectStore.java:4115)
18/04/19 17:17:35 [main]: DEBUG metastore.HiveMetaStore: Failed while granting global privs to admin
InvalidObjectException(message:All is already granted by admin)
        at org.apache.hadoop.hive.metastore.ObjectStore.grantPrivileges(ObjectStore.java:3948)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.hadoop.hive.metastore.RawStoreProxy.invoke(RawStoreProxy.java:114)
        at com.sun.proxy.$Proxy8.grantPrivileges(Unknown Source)
        at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.createDefaultRoles_core(HiveMetaStore.java:679)
        at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.createDefaultRoles(HiveMetaStore.java:645)
        at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.init(HiveMetaStore.java:462)
        at org.apache.hadoop.hive.metastore.RetryingHMSHandler.<init>(RetryingHMSHandler.java:66)
        at org.apache.hadoop.hive.metastore.RetryingHMSHandler.getProxy(RetryingHMSHandler.java:72)
        at org.apache.hadoop.hive.metastore.HiveMetaStore.newRetryingHMSHandler(HiveMetaStore.java:5762)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.<init>(HiveMetaStoreClient.java:199)
        at org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient.<init>(SessionHiveMetaStoreClient.java:74)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.apache.hadoop.hive.metastore.MetaStoreUtils.newInstance(MetaStoreUtils.java:1521)
        at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.<init>(RetryingMetaStoreClient.java:86)
        at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:132)
        at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:104)
        at org.apache.hadoop.hive.ql.metadata.Hive.createMetaStoreClient(Hive.java:3005)
        at org.apache.hadoop.hive.ql.metadata.Hive.getMSC(Hive.java:3024)
        at org.apache.hadoop.hive.ql.metadata.Hive.getAllDatabases(Hive.java:1234)
        at org.apache.hadoop.hive.ql.metadata.Hive.reloadFunctions(Hive.java:174)
        at org.apache.hadoop.hive.ql.metadata.Hive.<clinit>(Hive.java:166)
        at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:503)
        at org.apache.hadoop.hive.cli.CliDriver.run(CliDriver.java:677)
        at org.apache.hadoop.hive.cli.CliDriver.main(CliDriver.java:621)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:208)
18/04/19 17:17:35 [main]: INFO metastore.HiveMetaStore: No user is added in admin role, since config is empty
18/04/19 17:17:35 [main]: INFO metastore.HiveMetaStore: 0: get_all_databases
18/04/19 17:17:35 [main]: INFO HiveMetaStore.audit: ugi=root    ip=unknown-ip-addr      cmd=get_all_databases
18/04/19 17:17:35 [main]: DEBUG metastore.ObjectStore: Open transaction: count = 1, isActive = true at:
        org.apache.hadoop.hive.metastore.ObjectStore.getDatabases(ObjectStore.java:677)
18/04/19 17:17:35 [main]: DEBUG metastore.ObjectStore: Commit transaction: count = 0, isactive true at:
        org.apache.hadoop.hive.metastore.ObjectStore.getDatabases(ObjectStore.java:701)
18/04/19 17:17:35 [main]: INFO metastore.HiveMetaStore: 0: get_functions: db=default pat=*
18/04/19 17:17:35 [main]: INFO HiveMetaStore.audit: ugi=root    ip=unknown-ip-addr      cmd=get_functions: db=default pat=*
18/04/19 17:17:35 [main]: DEBUG metastore.ObjectStore: Open transaction: count = 1, isActive = true at:
        org.apache.hadoop.hive.metastore.ObjectStore.getFunctions(ObjectStore.java:7013)
18/04/19 17:17:35 [main]: DEBUG metastore.ObjectStore: Commit transaction: count = 0, isactive true at:
        org.apache.hadoop.hive.metastore.ObjectStore.getFunctions(ObjectStore.java:7041)
18/04/19 17:17:35 [main]: DEBUG hdfs.NameNodeProxies: multipleLinearRandomRetry = null
18/04/19 17:17:35 [main]: DEBUG ipc.Server: rpcKind=RPC_PROTOCOL_BUFFER, rpcRequestWrapperClass=class org.apache.hadoop.ipc.ProtobufRpcEngine$RpcRequestWritable, rpcInvoker=org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker@26ecbe52
Exception in thread "main" java.lang.RuntimeException: java.lang.UnsupportedOperationException: This is supposed to be overridden by subclasses.
        at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:522)
        at org.apache.hadoop.hive.cli.CliDriver.run(CliDriver.java:677)
        at org.apache.hadoop.hive.cli.CliDriver.main(CliDriver.java:621)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:208)
Caused by: java.lang.UnsupportedOperationException: This is supposed to be overridden by subclasses.
        at com.google.protobuf.GeneratedMessage.getUnknownFields(GeneratedMessage.java:180)
        at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$GetFileInfoRequestProto.getSerializedSize(ClientNamenodeProtocolProtos.java:30042)
        at com.google.protobuf.AbstractMessageLite.toByteString(AbstractMessageLite.java:49)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.constructRpcRequest(ProtobufRpcEngine.java:149)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:193)
        at com.sun.proxy.$Proxy15.getFileInfo(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:164)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:83)
        at com.sun.proxy.$Proxy15.getFileInfo(Unknown Source)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:628)
        at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1545)
        at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:805)
        at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1367)
        at org.apache.hadoop.hive.ql.session.SessionState.createRootHDFSDir(SessionState.java:596)
        at org.apache.hadoop.hive.ql.session.SessionState.createSessionDirs(SessionState.java:554)
        at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:508)
        ... 7 more
18/04/19 17:17:36 [Thread-1]: DEBUG ipc.Client: Stopping client
```

**Comment by znguo** [comment]
i already change mysql‘s character to latin1，but it still have error when run with command：
/opt/app/apache-hive-1.2.1-bin/
   alias hive="/opt/app/apache-hive-1.2.1-bin/bin/hive --hiveconf user.group=`echo $group` --hiveconf mapred.job.queue.name=default --hiveconf mapred.fairscheduler.pool=`echo $cug_group`"

**Comment by Safihre** [comment]
Sorry but what is this about?
What package? What are you trying to do?

**Comment by Safihre** [comment]
Closing due to lack of response.
