### ISSUE TITLE
Debian chroot - No module named pyextdirect.configuration

### ISSUE THREAD

**Issue by supertin** [SynoCommunity/spksrc#3359]
### Setup
_Package Name:_ Debian chroot
_Package Version:_ 8.4-7

_NAS Model:_ DS213j
_NAS Architecture:_ armv7l 
_DSM version:_ DSM 6.2-23739

### Expected behavior
Install DSM from scratch, install Debian chroot, start chroot.

### Actual behavior
Upon starting chroot manually, the script throws an error about a missing python module pyextdirect.
This error seems to not effect the actual starting if run manually, but the GUI (and boot scripts) see the error and rather than letting it go, they issue a stop command.

### Steps to reproduce
Install chroot on a fresh DSM install.
Attempt to start via web GUI and get an error about failing to start.
Check /var/log/synpkg.log (from memory - might be slightly different name) to see the Python error.
Check status via start-stop-status script - says stopped/not running
Start manually via same script. Throws same error, but starts OK.
Check status from start-stop-status script again - says it's running.

#### Other logs
Segment of synopkg.log after clicking "run" in web GUI:
Starting Debian Chroot ...
Traceback (most recent call last):
  File "/usr/local/debian-chroot/app/start.py", line 2, in <module>
    from application.direct import Services
  File "/volume1/@appstore/debian-chroot/app/application/direct.py", line 1, in <module>
    from pyextdirect.configuration import create_configuration, expose, LOAD, STORE_READ, STORE_CUD
ImportError: No module named pyextdirect.configuration
2018/06/26 16:38:43     start debian-chroot 8.4-7 End start-stop-status start ret=[1]
2018/06/26 16:38:45     (system) trigger debian-chroot 8.4-7 Begin start-stop-status stop
Stopping Debian Chroot ...
Traceback (most recent call last):
  File "/usr/local/debian-chroot/app/stop.py", line 2, in <module>
    from application.direct import Services
  File "/volume1/@appstore/debian-chroot/app/application/direct.py", line 1, in <module>
    from pyextdirect.configuration import create_configuration, expose, LOAD, STORE_READ, STORE_CUD
ImportError: No module named pyextdirect.configuration
umount: /volume1/@appstore/debian-chroot/var/chroottarget/dev: target is busy
        (In some cases useful info about processes that
         use the device is found by lsof(8) or fuser(1).)
2018/06/26 16:38:45     (system) trigger debian-chroot 8.4-7 End start-stop-status stop ret=[0]
2018/06/26 16:38:46     (system) trigger debian-chroot 8.4-7 Begin unload apparmor
2018/06/26 16:38:46     (system) trigger debian-chroot 8.4-7 End unload apparmor ret=[0]
2018/06/26 16:38:46     stop debian-chroot: begin to stop version 8.4-7
2018/06/26 16:38:46     stop debian-chroot: stop version 8.4-7 successfully, result 0
2018/06/26 16:38:46     start debian-chroot: start version 8.4-7 failed, result 272

#### Notes
Obviously the fix here is to install said Python module. But as a non-python person, that's easier said than understood. There appears to be a very similar/same issue (2799) from 12 months ago, but there isn't really a solution listed (and being that old, not sure if it's the same problem).

Also, this was all working fine until yesterday when I did a fresh DSM install on new HDDs. Same NAS with different drives had been running chroot fine for 6 months or so. So obviously the module USED to get installed somewhere, but now does not.

**Comment by supertin** [comment]
Alright - my workaround, which isn't great but works for now....
Install pip using the get-pip.py script.
Use pip to install pyextdirect
Add the following to start.py and stop.py in /var/packages/debian-chroot/target/app/
`import sys
sys.path.append("/usr/lib/python2.7/site-packages")`

I noticed during all this that debian-chroot is looking for python libs inside it's own path. Does that mean this missing module should have been included in the debian-chroot package?

**Comment by ymartin59** [comment]
Running debian-chroot on DSM 6.x is probably "dangerous", from some reports, try to uninstall may "brick" your DSM system.
I have no answer to your question but we will welcome any PR with improvements and fixes on Debian Chroot package: https://github.com/SynoCommunity/spksrc/tree/master/spk/debian-chroot

**Comment by dzung-hoang** [comment]
I tracked this down to the use of the deprecated "--use-wheel" option to pip inside the /var/packages/debian-chroot/installer script. Because of this, pip fails to install the packages from the requirements.txt file.

[One suggested fix](https://stackoverflow.com/questions/49835842/docker-no-such-option-use-wheel) is to replace "--use-wheel" with "--only-binary=:all:".

**Comment by dzung-hoang** [comment]
I fixed the issue by running the following script.

```
#!/bin/sh

# Package
PACKAGE="debian-chroot"
DNAME="Debian Chroot"

# Others
INSTALL_DIR="/usr/local/${PACKAGE}"
PYTHON_DIR="/usr/local/python"
CHROOTTARGET="${INSTALL_DIR}/var/chroottarget"
PATH="${INSTALL_DIR}/bin:${INSTALL_DIR}/env/bin:${PYTHON_DIR}/bin:${PATH}"
CHROOT_PATH="/usr/local/bin:/usr/bin:/bin"
VIRTUALENV="${PYTHON_DIR}/bin/virtualenv"
TMP_DIR="${SYNOPKG_PKGDEST}/../../@tmp"

# Create a Python virtualenv
${VIRTUALENV} --system-site-packages ${INSTALL_DIR}/env

# Install the wheels/requirements
${INSTALL_DIR}/env/bin/pip install --only-binary=:all: --no-deps --no-index -U --force-reinstall -f ${INSTALL_DIR}/share/wheelhouse -r ${INSTALL_DIR}/share/wheelhouse/requirements.txt

# Setup the database
${INSTALL_DIR}/env/bin/python ${INSTALL_DIR}/app/setup.py
```

**Comment by dzung-hoang** [comment]
It looks like this issue was fixed in the source.

https://github.com/SynoCommunity/spksrc/blob/master/spk/debian-chroot/src/installer.sh

**Comment by hgy59** [comment]
The debian-chroot package has been archived and is not supported anymore.
