### ISSUE TITLE
Home Assistant - Error while setting up platform broadlink

### ISSUE THREAD

**Issue by vinhpaint** [SynoCommunity/spksrc#3573]
Log Details (ERROR)
Thu Jan 10 2019 14:46:53 GMT+0700 (Indochina Time)

Error while setting up platform broadlink
Traceback (most recent call last):
File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
SLOW_SETUP_MAX_WAIT, loop=hass.loop)
File "/var/packages/python3/target/lib/python3.5/asyncio/tasks.py", line 406, in wait_for
return fut.result()
File "/var/packages/python3/target/lib/python3.5/asyncio/futures.py", line 294, in result
raise self._exception
File "/var/packages/python3/target/lib/python3.5/concurrent/futures/thread.py", line 55, in run
result = self.fn(*self.args, **self.kwargs)
File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/homeassistant/components/sensor/broadlink.py", line 58, in setup_platform
broadlink_data = BroadlinkData(update_interval, host, mac_addr, timeout)
File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/homeassistant/components/sensor/broadlink.py", line 108, in __init__
self._connect()
File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/homeassistant/components/sensor/broadlink.py", line 121, in _connect
import broadlink
File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/broadlink/__init__.py", line 5, in <module>
from Crypto.Cipher import AES
File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/Crypto/Cipher/__init__.py", line 27, in <module>
from Crypto.Cipher._mode_ecb import _create_ecb_cipher
File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/Crypto/Cipher/_mode_ecb.py", line 47, in <module>
"""
File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/Crypto/Util/_raw_api.py", line 299, in load_pycryptodome_raw_lib
raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cpython-35m-aarch64-linux-gnu.so': cannot load library '/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/Crypto/Util/../Cipher/_raw_ecb.cpython-35m-aarch64-linux-gnu.so': /volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/Crypto/Util/../Cipher/_raw_ecb.cpython-35m-aarch64-linux-gnu.so: cannot open shared object file: No such file or directory. Additionally, ctypes.util.find_library() did not manage to locate a library called '/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/Crypto/Util/../Cipher/_raw_ecb.cpython-35m-aarch64-linux-gnu.so', Trying '_raw_ecb.abi3.so': cannot load library '/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/Crypto/Util/../Cipher/_raw_ecb.abi3.so': /volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/Crypto/Util/../Cipher/_raw_ecb.abi3.so: cannot open shared object file: No such file or directory. Additionally, ctypes.util.find_library() did not manage to locate a library called '/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/Crypto/Util/../Cipher/_raw_ecb.abi3.so', Trying '_raw_ecb.so': cannot load library '/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/Crypto/Util/../Cipher/_raw_ecb.so': /volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/Crypto/Util/../Cipher/_raw_ecb.so: cannot open shared object file: No such file or directory. Additionally, ctypes.util.find_library() did not manage to locate a library called '/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/Crypto/Util/../Cipher/_raw_ecb.so'

I installed the Home Assistant beta package and everything was fine since when I wanted to turn on broadlink RM component and also enable Broadlink RM for discover component. Did you see the same issue?

### Setup
_Package Name:_Home Assistant
_Package Version:_0.82.1-2

_NAS Model:_DS418
_NAS Architecture:_Realtek RTD1296 SoC
_DSM version:_DSM 6.2.1-23824 Update 4

### Expected behavior
Home Assistant 0.82.1-2

### Actual behavior
error

### Steps to reproduce
_1._install Home Assistnat Beta
_2._add into discovery component
sensor:
  - platform: broadlink
    host: 192.168.2.202
    mac: 'B4:43:0D:B6:0C:CE'
    name: RMPro
    monitored_conditions:
      - temperature

#### Package log
File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
SLOW_SETUP_MAX_WAIT, loop=hass.loop)
File "/var/packages/python3/target/lib/python3.5/asyncio/tasks.py", line 406, in wait_for
return fut.result()
File "/var/packages/python3/target/lib/python3.5/asyncio/futures.py", line 294, in result
raise self._exception
File "/var/packages/python3/target/lib/python3.5/concurrent/futures/thread.py", line 55, in run
result = self.fn(*self.args, **self.kwargs)
File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/homeassistant/components/sensor/broadlink.py", line 58, in setup_platform
broadlink_data = BroadlinkData(update_interval, host, mac_addr, timeout)
File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/homeassistant/components/sensor/broadlink.py", line 108, in __init__
self._connect()
File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/homeassistant/components/sensor/broadlink.py", line 121, in _connect
import broadlink
File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/broadlink/__init__.py", line 5, in <module>
from Crypto.Cipher import AES
File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/Crypto/Cipher/__init__.py", line 27, in <module>
from Crypto.Cipher._mode_ecb import _create_ecb_cipher
File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/Crypto/Cipher/_mode_ecb.py", line 47, in <module>
"""
File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/Crypto/Util/_raw_api.py", line 299, in load_pycryptodome_raw_lib
raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cpython-35m-aarch64-linux-gnu.so': cannot load library '/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/Crypto/Util/../Cipher/_raw_ecb.cpython-35m-aarch64-linux-gnu.so': /volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/Crypto/Util/../Cipher/_raw_ecb.cpython-35m-aarch64-linux-gnu.so: cannot open shared object file: No such file or directory. Additionally, ctypes.util.find_library() did not manage to locate a library called '/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/Crypto/Util/../Cipher/_raw_ecb.cpython-35m-aarch64-linux-gnu.so', Trying '_raw_ecb.abi3.so': cannot load library '/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/Crypto/Util/../Cipher/_raw_ecb.abi3.so': /volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/Crypto/Util/../Cipher/_raw_ecb.abi3.so: cannot open shared object file: No such file or directory. Additionally, ctypes.util.find_library() did not manage to locate a library called '/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/Crypto/Util/../Cipher/_raw_ecb.abi3.so', Trying '_raw_ecb.so': cannot load library '/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/Crypto/Util/../Cipher/_raw_ecb.so': /volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/Crypto/Util/../Cipher/_raw_ecb.so: cannot open shared object file: No such file or directory. Additionally, ctypes.util.find_library() did not manage to locate a library called '/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/Crypto/Util/../Cipher/_raw_ecb.so'

**Comment by hgy59** [comment]
This might be fixed with python3 3.7.7 (and current home assistant v0.114.2-7)
