### ISSUE TITLE
Home Assistant - Error while setting up Xiaomi vacuum 2

### ISSUE THREAD

**Issue by vinhpaint** [SynoCommunity/spksrc#3584]
Log Details (ERROR)
Thu Jan 17 2019 21:40:39 GMT+0700 (Indochina Time)

xiaomi_miio: Error on device update!
Traceback (most recent call last):
  File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 251, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 349, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/var/packages/python3/target/lib/python3.5/asyncio/futures.py", line 381, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/var/packages/python3/target/lib/python3.5/asyncio/tasks.py", line 310, in _wakeup
    future.result()
  File "/var/packages/python3/target/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/var/packages/python3/target/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/homeassistant/components/vacuum/xiaomi_miio.py", line 365, in update
    state = self._vacuum.status()
  File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/miio/vacuum.py", line 153, in status
    return VacuumStatus(self.send("get_status")[0])
  File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/miio/device.py", line 241, in send
    m = Message.build(msg, token=self.token)
  File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/construct/core.py", line 352, in build
    self.build_stream(obj, stream, **contextkw)
  File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/construct/core.py", line 364, in build_stream
    self._build(obj, stream, context, "(building)")
  File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/construct/core.py", line 2003, in _build
    buildret = sc._build(subobj, stream, context, path)
  File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/construct/core.py", line 2472, in _build
    return self.subcon._build(obj, stream, context, path)
  File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/construct/core.py", line 4078, in _build
    buildret = self.subcon._build(obj, stream, context, path)
  File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/construct/core.py", line 4365, in _build
    buildret = self.subcon._build(value, stream, context, path)
  File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/construct/core.py", line 718, in _build
    obj2 = self._encode(obj, context, path)
  File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/miio/protocol.py", line 144, in _encode
    context['_']['token'])
  File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/miio/protocol.py", line 71, in encrypt
    backend=default_backend())
  File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/cryptography/hazmat/backends/__init__.py", line 15, in default_backend
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 53, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: undefined symbol: pthread_atfork

### Setup
_Package Name:_Home Assistant
_Package Version:_0.82.1-2

_NAS Model:_DS418
_NAS Architecture:_Realtek RTD1296 SoC
_DSM version:_DSM 6.2.1-23824 Update 4

### Expected behavior
Tell us what should happen

### Actual behavior
Home Assistant 0.82.1-2

### Steps to reproduce
_1._install Home Assistnat Beta
_2._add into discovery component
vacuum:
  - platform: xiaomi_miio
    host: 192.168.2.89
    token:

#### Package log
Log Details (ERROR)
Thu Jan 17 2019 21:40:39 GMT+0700 (Indochina Time)

xiaomi_miio: Error on device update!
Traceback (most recent call last):
  File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 251, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 349, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/var/packages/python3/target/lib/python3.5/asyncio/futures.py", line 381, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/var/packages/python3/target/lib/python3.5/asyncio/tasks.py", line 310, in _wakeup
    future.result()
  File "/var/packages/python3/target/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/var/packages/python3/target/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/homeassistant/components/vacuum/xiaomi_miio.py", line 365, in update
    state = self._vacuum.status()
  File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/miio/vacuum.py", line 153, in status
    return VacuumStatus(self.send("get_status")[0])
  File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/miio/device.py", line 241, in send
    m = Message.build(msg, token=self.token)
  File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/construct/core.py", line 352, in build
    self.build_stream(obj, stream, **contextkw)
  File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/construct/core.py", line 364, in build_stream
    self._build(obj, stream, context, "(building)")
  File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/construct/core.py", line 2003, in _build
    buildret = sc._build(subobj, stream, context, path)
  File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/construct/core.py", line 2472, in _build
    return self.subcon._build(obj, stream, context, path)
  File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/construct/core.py", line 4078, in _build
    buildret = self.subcon._build(obj, stream, context, path)
  File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/construct/core.py", line 4365, in _build
    buildret = self.subcon._build(value, stream, context, path)
  File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/construct/core.py", line 718, in _build
    obj2 = self._encode(obj, context, path)
  File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/miio/protocol.py", line 144, in _encode
    context['_']['token'])
  File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/miio/protocol.py", line 71, in encrypt
    backend=default_backend())
  File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/cryptography/hazmat/backends/__init__.py", line 15, in default_backend
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 53, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /volume1/@appstore/homeassistant/env/lib/python3.5/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: undefined symbol: pthread_atfork

**Comment by miklosandras** [comment]
I also had this issue. Solution:
Before you build your python3 / homeassistant package with cryptography (please include cryptography in src/requirements.txt ).

Required linux command: `export CFLAGS=-pthread`

**Comment by ymartin59** [comment]
Python 3.6 with cryptograpy updates is ready. HomeAssistant update to 0.87.1 is in progress.

**Comment by dotvav** [comment]
How long does it usually take before the new version becomes available in the Package Center?

**Comment by hgy59** [comment]
This might be fixed with python3 3.7.7 (and current home assistant  v0.114.2-7)
