### ISSUE TITLE
Borgbackup and python3 no longer install as intended

### ISSUE THREAD

**Issue by claw111** [SynoCommunity/spksrc#3644]
### Setup
Package Name: Python3
Package Version: 3.6.8-9

Package Name: Borgbackup
Package Version: 1.1.9-4

NAS Model: evansport (DS415Play)
NAS Architecture: x86
DSM version: DSM 6.2.1-23824 Update 6

### Expected behavior
Install, update, or re-install the `borgbackup` package from SynoCommunity should provide `borg` executable.

Install, update, or re-install the `python3` package from SynoCommunity should provide `virtualenv` executable.

### Actual behavior
Installation/update/re-install of either `python3` or `borgbackup` completes without user visible error.

The `borg` executable is no longer available through the symlink at `/usr/local/bin/borg`.
The `env/bin/` sub-directories is absent from the @appstore installation of the `borgbackup` package.

The `virtualenv` executable is no longer available under `/usr/local/python3/bin/`, but the `python3` executable is available.

### Steps to reproduce
1. Install, update, or re-install `python3` package version 3.6.8-9 from SynoCommunity channel onto DS415Play; then
2. Install, update, or re-install `borgbackup` package version 1.1.9-4 from SynoCommunity channel onto DS415Play.

#### Package logs
From `/usr/local/borgbackup/var/borgbackup_install.log`:
```
Sat Mar  2 12:39:36 AWST 2019
===> Step preuninst. USER= GROUP= SHARE_PATH=
Sat Mar  2 12:39:37 AWST 2019
===> Step postuninst. USER= GROUP= SHARE_PATH=
Invoke service_postuninst
Sat Mar  2 12:52:24 AWST 2019
===> Step preinst. USER= GROUP= SHARE_PATH=
Sat Mar  2 12:52:25 AWST 2019
===> Step postinst. USER= GROUP= SHARE_PATH=
Invoke service_postinst
/var/packages/borgbackup/scripts/service-setup: line 25: /volume1/@appstore/borgbackup/env/bin/pip: No such file or directory
```

From `/usr/local/python3/var/python3_install.log`:
```
Sat Mar  2 12:39:54 AWST 2019
===> Step preuninst. USER= GROUP= SHARE_PATH=
Sat Mar  2 12:39:54 AWST 2019
===> Step postuninst. USER= GROUP= SHARE_PATH=
Sat Mar  2 12:41:19 AWST 2019
===> Step preinst. USER= GROUP= SHARE_PATH=
Sat Mar  2 12:41:20 AWST 2019
===> Step postinst. USER= GROUP= SHARE_PATH=
Invoke service_postinst
Failed to import the site module
Traceback (most recent call last):
  File "/var/packages/python3/target/lib/python3.6/site.py", line 553, in <module>
    main()
  File "/var/packages/python3/target/lib/python3.6/site.py", line 539, in main
    known_paths = addusersitepackages(known_paths)
  File "/var/packages/python3/target/lib/python3.6/site.py", line 282, in addusersitepackages
    user_site = getusersitepackages()
  File "/var/packages/python3/target/lib/python3.6/site.py", line 258, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/var/packages/python3/target/lib/python3.6/site.py", line 248, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/var/packages/python3/target/lib/python3.6/sysconfig.py", line 601, in get_config_var
    return get_config_vars().get(name)
  File "/var/packages/python3/target/lib/python3.6/sysconfig.py", line 550, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/var/packages/python3/target/lib/python3.6/sysconfig.py", line 421, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata_m_linux_i386-linux-gnu'
Python 3.6.8

System installed modules:
```
#### Other logs
From `/var/log/messages`:
```
2019-03-02T12:39:36+08:00 nas01 synoscgi_SYNO.Core.Package.Uninstallation_1_uninstall[19314]: resource_api.cpp:231 Release service-cfg for borgbackup when 0x0004 (done)
2019-03-02T12:39:54+08:00 nas01 synoscgi_SYNO.Core.Package.Uninstallation_1_uninstall[19616]: resource_api.cpp:231 Release service-cfg for python3 when 0x0004 (done)
2019-03-02T12:41:20+08:00 nas01 synoscgi_SYNO.Core.Package.Installation_1_install[19892]: resource_api.cpp:163 Acquire service-cfg for python3 when 0x0001 (done)
2019-03-02T12:52:24+08:00 nas01 synoscgi_SYNO.Core.Package.Installation_1_install[24409]: resource_api.cpp:163 Acquire service-cfg for borgbackup when 0x0001 (done)
```

From `/var/log/synopkg.log`:
```
2019/03/02 12:39:36 uninstall borgbackup: begin to stop version 1.1.9-4
2019/03/02 12:39:36 uninstall borgbackup 1.1.9-4 Begin start-stop-status stop
2019/03/02 12:39:36 uninstall borgbackup 1.1.9-4 End start-stop-status stop ret=[0]
2019/03/02 12:39:36 uninstall borgbackup 1.1.9-4 Begin unload apparmor
2019/03/02 12:39:36 uninstall borgbackup 1.1.9-4 End unload apparmor ret=[0]
2019/03/02 12:39:36 uninstall borgbackup: stop version 1.1.9-4 successfully, result 0
2019/03/02 12:39:36 uninstall borgbackup 1.1.9-4 Begin preuninst
/var/packages/borgbackup/scripts/service-setup: line 7: type: service_preuninst: not found
2019/03/02 12:39:36 uninstall borgbackup 1.1.9-4 End preuninst ret=[0]
2019/03/02 12:39:36 uninstall borgbackup 1.1.9-4 Begin /bin/rm -rf /volume1/@appstore/borgbackup
2019/03/02 12:39:37 uninstall borgbackup 1.1.9-4 End /bin/rm -rf /volume1/@appstore/borgbackup ret=[0]
2019/03/02 12:39:37 uninstall borgbackup 1.1.9-4 Begin postuninst
2019/03/02 12:39:37 uninstall borgbackup 1.1.9-4 End postuninst ret=[0]
2019/03/02 12:39:37 uninstall borgbackup: Uninstall 1.1.9-4 successfully
2019/03/02 12:39:53 uninstall python3: begin to stop version 3.6.8-9
2019/03/02 12:39:53 uninstall python3 3.6.8-9 Begin start-stop-status stop
2019/03/02 12:39:53 uninstall python3 3.6.8-9 End start-stop-status stop ret=[0]
2019/03/02 12:39:53 uninstall python3 3.6.8-9 Begin unload apparmor
2019/03/02 12:39:53 uninstall python3 3.6.8-9 End unload apparmor ret=[0]
2019/03/02 12:39:53 uninstall python3: stop version 3.6.8-9 successfully, result 0
2019/03/02 12:39:53 uninstall python3 3.6.8-9 Begin preuninst
/var/packages/python3/scripts/service-setup: line 7: type: service_preuninst: not found
2019/03/02 12:39:54 uninstall python3 3.6.8-9 End preuninst ret=[0]
2019/03/02 12:39:54 uninstall python3 3.6.8-9 Begin /bin/rm -rf /volume1/@appstore/python3
2019/03/02 12:39:54 uninstall python3 3.6.8-9 End /bin/rm -rf /volume1/@appstore/python3 ret=[0]
2019/03/02 12:39:54 uninstall python3 3.6.8-9 Begin postuninst
/var/packages/python3/scripts/service-setup: line 7: type: service_postuninst: not found
2019/03/02 12:39:54 uninstall python3 3.6.8-9 End postuninst ret=[0]
2019/03/02 12:39:54 uninstall python3: Uninstall 3.6.8-9 successfully
2019/03/02 12:41:19 install python3 3.6.8-9 Begin preinst
/volume1/@tmp/pkginstall/scripts/service-setup: line 7: type: service_preinst: not found
2019/03/02 12:41:19 install python3 3.6.8-9 End preinst ret=[0]
2019/03/02 12:41:19 install python3 3.6.8-9 Begin /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/python3
2019/03/02 12:41:19 install python3 3.6.8-9 End /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/python3 ret=[0]
2019/03/02 12:41:19 install python3 3.6.8-9 Begin /bin/rm -rf /var/packages/python3
2019/03/02 12:41:19 install python3 3.6.8-9 End /bin/rm -rf /var/packages/python3 ret=[0]
2019/03/02 12:41:20 install python3 3.6.8-9 Begin /bin/mkdir -p /var/packages/python3
2019/03/02 12:41:20 install python3 3.6.8-9 End /bin/mkdir -p /var/packages/python3 ret=[0]
2019/03/02 12:41:20 install python3 3.6.8-9 Begin /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/python3/INFO
2019/03/02 12:41:20 install python3 3.6.8-9 End /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/python3/INFO ret=[0]
2019/03/02 12:41:20 install python3 3.6.8-9 Begin /bin/rm -rf /var/packages/python3/scripts
2019/03/02 12:41:20 install python3 3.6.8-9 End /bin/rm -rf /var/packages/python3/scripts ret=[0]
2019/03/02 12:41:20 install python3 3.6.8-9 Begin /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/python3/scripts
2019/03/02 12:41:20 install python3 3.6.8-9 End /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/python3/scripts ret=[0]
2019/03/02 12:41:20 install python3 3.6.8-9 Begin /bin/rm -rf /var/packages/python3/conf
2019/03/02 12:41:20 install python3 3.6.8-9 End /bin/rm -rf /var/packages/python3/conf ret=[0]
2019/03/02 12:41:20 install python3 3.6.8-9 Begin /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/python3/conf
2019/03/02 12:41:20 install python3 3.6.8-9 End /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/python3/conf ret=[0]
2019/03/02 12:41:20 install python3 3.6.8-9 Begin postinst
Failed to import the site module
Traceback (most recent call last):
  File "/var/packages/python3/target/lib/python3.6/site.py", line 553, in <module>
    main()
  File "/var/packages/python3/target/lib/python3.6/site.py", line 539, in main
    known_paths = addusersitepackages(known_paths)
  File "/var/packages/python3/target/lib/python3.6/site.py", line 282, in addusersitepackages
    user_site = getusersitepackages()
  File "/var/packages/python3/target/lib/python3.6/site.py", line 258, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/var/packages/python3/target/lib/python3.6/site.py", line 248, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/var/packages/python3/target/lib/python3.6/sysconfig.py", line 601, in get_config_var
    return get_config_vars().get(name)
  File "/var/packages/python3/target/lib/python3.6/sysconfig.py", line 550, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/var/packages/python3/target/lib/python3.6/sysconfig.py", line 421, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata_m_linux_i386-linux-gnu'
Failed to import the site module
Traceback (most recent call last):
  File "/volume1/@appstore/python3/lib/python3.6/site.py", line 553, in <module>
    main()
  File "/volume1/@appstore/python3/lib/python3.6/site.py", line 539, in main
    known_paths = addusersitepackages(known_paths)
  File "/volume1/@appstore/python3/lib/python3.6/site.py", line 282, in addusersitepackages
    user_site = getusersitepackages()
  File "/volume1/@appstore/python3/lib/python3.6/site.py", line 258, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/volume1/@appstore/python3/lib/python3.6/site.py", line 248, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/volume1/@appstore/python3/lib/python3.6/sysconfig.py", line 601, in get_config_var
    return get_config_vars().get(name)
  File "/volume1/@appstore/python3/lib/python3.6/sysconfig.py", line 550, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/volume1/@appstore/python3/lib/python3.6/sysconfig.py", line 421, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata_m_linux_i386-linux-gnu'
2019/03/02 12:41:21 install python3 3.6.8-9 End postinst ret=[0]
Failed to import the site module
Traceback (most recent call last):
  File "/volume1/@appstore/python3/lib/python3.6/site.py", line 553, in <module>
    main()
  File "/volume1/@appstore/python3/lib/python3.6/site.py", line 539, in main
    known_paths = addusersitepackages(known_paths)
  File "/volume1/@appstore/python3/lib/python3.6/site.py", line 282, in addusersitepackages
    user_site = getusersitepackages()
  File "/volume1/@appstore/python3/lib/python3.6/site.py", line 258, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/volume1/@appstore/python3/lib/python3.6/site.py", line 248, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/volume1/@appstore/python3/lib/python3.6/sysconfig.py", line 601, in get_config_var
    return get_config_vars().get(name)
  File "/volume1/@appstore/python3/lib/python3.6/sysconfig.py", line 550, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/volume1/@appstore/python3/lib/python3.6/sysconfig.py", line 421, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata_m_linux_i386-linux-gnu'
Failed to import the site module
Traceback (most recent call last):
  File "/volume1/@appstore/python3/lib/python3.6/site.py", line 553, in <module>
    main()
  File "/volume1/@appstore/python3/lib/python3.6/site.py", line 539, in main
    known_paths = addusersitepackages(known_paths)
  File "/volume1/@appstore/python3/lib/python3.6/site.py", line 282, in addusersitepackages
    user_site = getusersitepackages()
  File "/volume1/@appstore/python3/lib/python3.6/site.py", line 258, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/volume1/@appstore/python3/lib/python3.6/site.py", line 248, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/volume1/@appstore/python3/lib/python3.6/sysconfig.py", line 601, in get_config_var
    return get_config_vars().get(name)
  File "/volume1/@appstore/python3/lib/python3.6/sysconfig.py", line 550, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/volume1/@appstore/python3/lib/python3.6/sysconfig.py", line 421, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata_m_linux_i386-linux-gnu'
2019/03/02 12:41:22 install python3: begin to start version 3.6.8-9
2019/03/02 12:41:23 install python3 3.6.8-9 Begin pre-load apparmor
2019/03/02 12:41:23 install python3 3.6.8-9 End pre-load apparmor ret=[0]
2019/03/02 12:41:23 install python3 3.6.8-9 Begin start-stop-status start
2019/03/02 12:41:23 install python3 3.6.8-9 End start-stop-status start ret=[0]
2019/03/02 12:41:23 install python3: start version 3.6.8-9 successfully, result 0
2019/03/02 12:41:23 install python3 3.6.8-9 Begin /bin/rm -rf /volume1/@tmp/pkginstall
2019/03/02 12:41:23 install python3 3.6.8-9 End /bin/rm -rf /volume1/@tmp/pkginstall ret=[0]
2019/03/02 12:41:23 install python3 3.6.8-9 successfully
2019/03/02 12:52:24 install borgbackup 1.1.9-4 Begin preinst
/volume1/@tmp/pkginstall/scripts/service-setup: line 7: type: service_preinst: not found
2019/03/02 12:52:24 install borgbackup 1.1.9-4 End preinst ret=[0]
2019/03/02 12:52:24 install borgbackup 1.1.9-4 Begin /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/borgbackup
2019/03/02 12:52:24 install borgbackup 1.1.9-4 End /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/borgbackup ret=[0]
2019/03/02 12:52:24 install borgbackup 1.1.9-4 Begin /bin/rm -rf /var/packages/borgbackup
2019/03/02 12:52:24 install borgbackup 1.1.9-4 End /bin/rm -rf /var/packages/borgbackup ret=[0]
2019/03/02 12:52:24 install borgbackup 1.1.9-4 Begin /bin/mkdir -p /var/packages/borgbackup
2019/03/02 12:52:24 install borgbackup 1.1.9-4 End /bin/mkdir -p /var/packages/borgbackup ret=[0]
2019/03/02 12:52:24 install borgbackup 1.1.9-4 Begin /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/borgbackup/INFO
2019/03/02 12:52:24 install borgbackup 1.1.9-4 End /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/borgbackup/INFO ret=[0]
2019/03/02 12:52:24 install borgbackup 1.1.9-4 Begin /bin/rm -rf /var/packages/borgbackup/scripts
2019/03/02 12:52:24 install borgbackup 1.1.9-4 End /bin/rm -rf /var/packages/borgbackup/scripts ret=[0]
2019/03/02 12:52:24 install borgbackup 1.1.9-4 Begin /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/borgbackup/scripts
2019/03/02 12:52:24 install borgbackup 1.1.9-4 End /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/borgbackup/scripts ret=[0]
2019/03/02 12:52:24 install borgbackup 1.1.9-4 Begin /bin/rm -rf /var/packages/borgbackup/conf
2019/03/02 12:52:24 install borgbackup 1.1.9-4 End /bin/rm -rf /var/packages/borgbackup/conf ret=[0]
2019/03/02 12:52:24 install borgbackup 1.1.9-4 Begin /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/borgbackup/conf
2019/03/02 12:52:24 install borgbackup 1.1.9-4 End /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/borgbackup/conf ret=[0]
2019/03/02 12:52:25 install borgbackup 1.1.9-4 Begin postinst
/var/packages/borgbackup/scripts/service-setup: line 22: /usr/local/python3/bin/virtualenv: No such file or directory
2019/03/02 12:52:25 install borgbackup 1.1.9-4 End postinst ret=[0]
2019/03/02 12:52:26 install borgbackup: begin to start version 1.1.9-4
2019/03/02 12:52:26 install borgbackup 1.1.9-4 Begin pre-load apparmor
2019/03/02 12:52:26 install borgbackup 1.1.9-4 End pre-load apparmor ret=[0]
2019/03/02 12:52:26 install borgbackup 1.1.9-4 Begin start-stop-status start
2019/03/02 12:52:26 install borgbackup 1.1.9-4 End start-stop-status start ret=[0]
2019/03/02 12:52:26 install borgbackup: start version 1.1.9-4 successfully, result 0
2019/03/02 12:52:26 install borgbackup 1.1.9-4 Begin /bin/rm -rf /volume1/@tmp/pkginstall
2019/03/02 12:52:26 install borgbackup 1.1.9-4 End /bin/rm -rf /volume1/@tmp/pkginstall ret=[0]
2019/03/02 12:52:26 install borgbackup 1.1.9-4 successfully
```

**Comment by ymartin59** [comment]
@chickenandpork Hello Allan. Are you aware of this python3 `ModuleNotFoundError: No module named '_sysconfigdata_m_linux_i386-linux-gnu'` trouble for cross-compiled packages? Looks like only `x64` package is properly running...

**Comment by ymartin59** [comment]
Module file name contains always `x86_64` for any arch:
```
./work-evansport-5.2/Python-3.6.8/build/lib.linux-i686-3.6/_sysconfigdata_m_linux_x86_64-linux-gnu.py
./work-aarch64-6.1/Python-3.6.8/build/lib.linux-aarch64-3.6/_sysconfigdata_m_linux_x86_64-linux-gnu.py
```

**Comment by Honiix** [comment]
With borg Package Version: 1.1.7-3

I also got the error : 
`/volume1/@appstore/borgbackup/env/bin/python3.5: error while loading shared libraries: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory
`

But I think the problem comes from the python package. Here is what's displayed in Package Center :
- Installed version 3.6.8-9
- Newest version 3.5.6-8

If i go in the python folder and run Python3.6, here is the output:
```
cd /volume1/@appstore/python3/bin
./python3

Failed to import the site module
Traceback (most recent call last):
  File "/volume1/@appstore/python3/lib/python3.6/site.py", line 553, in <module>
    main()
  File "/volume1/@appstore/python3/lib/python3.6/site.py", line 539, in main
    known_paths = addusersitepackages(known_paths)
  File "/volume1/@appstore/python3/lib/python3.6/site.py", line 282, in addusersitepackages
    user_site = getusersitepackages()
  File "/volume1/@appstore/python3/lib/python3.6/site.py", line 258, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/volume1/@appstore/python3/lib/python3.6/site.py", line 248, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/volume1/@appstore/python3/lib/python3.6/sysconfig.py", line 601, in get_config_var
    return get_config_vars().get(name)
  File "/volume1/@appstore/python3/lib/python3.6/sysconfig.py", line 550, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/volume1/@appstore/python3/lib/python3.6/sysconfig.py", line 421, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata_m_linux_arm-linux-gnueabihf'
```

**Comment by ymartin59** [comment]
As Python 3.6 (except x64) fails, I have unpublished the three corelated packages: python3.6, borgbackup and homeassistant.
To get back borg 1.1.7 you have to uninstall/reinstall both python3 and borgbackup.
Sorry for the inconvenience

**Comment by claw111** [comment]
Curiously, was there a particular need for borgbackup 1.1.9 to depend on python 3.6?  I had borgbackup 1.1.9-x running quite well on python 3.5.

**Comment by claw111** [comment]
Sorry, my bad.  I see from my logs I was running borgbackup 1.1.7 with python 3.5.  I thought I was running 1.1.9 a few weeks ago, but I think now it was just the new package notification for 1.1.9 that I had in my minds eye.

**Comment by ymartin59** [comment]
@chickenandpork I have investigated python3 cross-compilation troubles with "sysconfigdata".
Symptom: incorrect sysconfigdata file name
```
find work-aarch64-6.1 -name "*sysconfigdata*"
work-aarch64-6.1/Python-3.6.8/build/lib.linux-aarch64-3.6/__pycache__/_sysconfigdata_m_linux_x86_64-linux-gnu.cpython-36.pyc
work-aarch64-6.1/Python-3.6.8/build/lib.linux-aarch64-3.6/__pycache__/_sysconfigdata_m_linux_x86_64-linux-gnu.cpython-36.opt-2.pyc
work-aarch64-6.1/Python-3.6.8/build/lib.linux-aarch64-3.6/__pycache__/_sysconfigdata_m_linux_x86_64-linux-gnu.cpython-36.opt-1.pyc
work-aarch64-6.1/Python-3.6.8/build/lib.linux-aarch64-3.6/_sysconfigdata_m_linux_x86_64-linux-gnu.py
work-aarch64-6.1/Python-3.6.8/build/lib.linux-x86_64-3.6/__pycache__/_sysconfigdata_m_linux_x86_64-linux-gnu.cpython-36.pyc
work-aarch64-6.1/Python-3.6.8/build/lib.linux-x86_64-3.6/__pycache__/_sysconfigdata_m_linux_x86_64-linux-gnu.cpython-36.opt-2.pyc
work-aarch64-6.1/Python-3.6.8/build/lib.linux-x86_64-3.6/__pycache__/_sysconfigdata_m_linux_x86_64-linux-gnu.cpython-36.opt-1.pyc
work-aarch64-6.1/Python-3.6.8/build/lib.linux-x86_64-3.6/_sysconfigdata_m_linux_x86_64-linux-gnu.py
work-aarch64-6.1/Python-3.6.8/build/lib.linux-x86_64-3.6/_sysconfigdata.py
work-aarch64-6.1/install/var/packages/python3/target/lib/python3.6/lib-dynload/_sysconfigdata_m_linux_x86_64-linux-gnu.py
work-aarch64-6.1/staging/lib/python3.6/lib-dynload/_sysconfigdata_m_linux_x86_64-linux-gnu.py
```
Input:
- https://raspberrypi.stackexchange.com/questions/66528/how-to-cross-compile-python-3-6-for-the-raspberry-pi
- https://bugs.python.org/issue28266
- http://lists.busybox.net/pipermail/buildroot/2017-March/186929.html

It looks like some environment variables are laking for `make` invocation: `CROSS-COMPILE CROSS_COMPILE_TARGET  HOSTARCH BUILDARCH` - and this may explain incorrect `MULTIARCH` value when generating sysconfigdata file.

**Comment by chickenandpork** [comment]
Just did a clean build of python3-3.6.8 for Avoton I'm not seeing this "has python3.5 and 3.6 at the same time".  A listing of the packages.tgz shows only 3.6.  Same for an arm build (88f6281).  but if there's more than one version there, it might be an unclean buildenv or something.

My minimal test case to check ffi and imports was:

/var/packages/python3/target/usr/bin/python3 -c 'import _ctypes; import lxml; import sqlite3; print("x");'

Can't automatically test on hardware I don't have, but I thought it was python3 that I had a few other users on the HomeAssistant lists testing on my behalf.  Really should automate that somehow.

The HOST_FOR_PYTHON and such is holdover from much older python3 builds; if it needs to be scrapped, then we should.

**Comment by ymartin59** [comment]
@chickenandpork Please review this issue from its starting point
```
Traceback (most recent call last):
  File "/var/packages/python3/target/lib/python3.6/site.py", line 553, in <module>
    main()
  File "/var/packages/python3/target/lib/python3.6/site.py", line 539, in main
    known_paths = addusersitepackages(known_paths)
  File "/var/packages/python3/target/lib/python3.6/site.py", line 282, in addusersitepackages
    user_site = getusersitepackages()
  File "/var/packages/python3/target/lib/python3.6/site.py", line 258, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/var/packages/python3/target/lib/python3.6/site.py", line 248, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/var/packages/python3/target/lib/python3.6/sysconfig.py", line 601, in get_config_var
    return get_config_vars().get(name)
  File "/var/packages/python3/target/lib/python3.6/sysconfig.py", line 550, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/var/packages/python3/target/lib/python3.6/sysconfig.py", line 421, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata_m_linux_i386-linux-gnu'
Python 3.6.8
```

Mixed 3.5 and 3.6 comes from user's trial to revert to previous version.

Only x86_64 architectures are functional - all other cross-compiled have this "sysconfigdata" trouble - it is not a compilation issue, evansport binary published in your own online repository fails too.

**Comment by Honiix** [comment]
@ymartin59 I think uninstalling and reinstalling Python3 + Borg still fails.

If I recall correctly, borg executable was in /usr/local/bin :

```
$ ls -l /usr/local/bin
lrwxrwxrwx 1 root root   42 Mar  5 20:57 borg -> /volume1/@appstore/borgbackup/env/bin/borg

$ ls -l /volume1/@appstore/borgbackup
drwxr-xr-x 2 root root 4096 Nov 25 17:52 bin
drwxr-xr-x 2 root root 4096 Nov 25 17:52 lib
drwxr-xr-x 5 root root 4096 Nov 25 17:52 share
drwxr-xr-x 2 root root 4096 Mar  5 20:57 var
```

No env folder.

**Comment by BenjV** [comment]
That's not the location but just a simlink to the virtual environment location of the package

**Comment by claw111** [comment]
Just an update on the work-around.  The following downgrade combination is working on evansport (DS415Play):Downgrading to python3 from ??? to ???

**Comment by claw111** [comment]
Just an update on the work-around proposed in https://github.com/SynoCommunity/spksrc/issues/3644#issuecomment-469003243.  The following package downgrade combination is working again on evansport (DS415Play):

- `python3` from 3.6.8-9 to 3.5.6-8
- `borgbackup` from 1.1.9-4 to 1.1.7-3

Respect to @ymartin59 for investigating, advising, collaborating, and herding the cats :)

**Comment by brandonscript** [comment]
Any news on getting 3.6 to work? Really itching to adopt f-strings 😊

**Comment by ymartin59** [comment]
Seems to be on the right path: #3726

**Comment by ymartin59** [comment]
New versions have been published. Please open a new issue if relevant
