### ISSUE TITLE
CouchPotato fails to start with message "service-setup: line 18: type: service_prestart: not found"

### ISSUE THREAD

**Issue by leolobato** [SynoCommunity/spksrc#3729]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ CouchPotato Custom
_Package Version:_ 20180513-5

_NAS Model:_ DS213
_NAS Architecture:_ 
_DSM version:_ DSM 6.2.2-24922

### Expected behavior
Tell us what should happen

CouchPotato to start, just like it has for the past few years.

### Actual behavior
Tell us what happens instead

It fails to restart. When I check /var/log/packages/couchpotatoserver-custom.log, I see this:
```
/var/packages/couchpotatoserver-custom/scripts/service-setup: line 18: type: service_prestart: not found
```

### Steps to reproduce
_1._ Click "Run" on the web UI to start the service
_2._ 
_3._ 

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
2019/06/27 03:54:34	install couchpotatoserver-custom 20180513-5 Begin preinst
2019/06/27 03:54:36	install couchpotatoserver-custom 20180513-5 End preinst ret=[0]
2019/06/27 03:54:36	install couchpotatoserver-custom 20180513-5 Begin /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/couchpotatoserver-custom
2019/06/27 03:54:36	install couchpotatoserver-custom 20180513-5 End /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/couchpotatoserver-custom ret=[0]
2019/06/27 03:54:36	install couchpotatoserver-custom 20180513-5 Begin /bin/rm -rf /var/packages/couchpotatoserver-custom
2019/06/27 03:54:36	install couchpotatoserver-custom 20180513-5 End /bin/rm -rf /var/packages/couchpotatoserver-custom ret=[0]
2019/06/27 03:54:36	install couchpotatoserver-custom 20180513-5 Begin /bin/mkdir -p /var/packages/couchpotatoserver-custom
2019/06/27 03:54:36	install couchpotatoserver-custom 20180513-5 End /bin/mkdir -p /var/packages/couchpotatoserver-custom ret=[0]
2019/06/27 03:54:36	install couchpotatoserver-custom 20180513-5 Begin /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/couchpotatoserver-custom/INFO
2019/06/27 03:54:36	install couchpotatoserver-custom 20180513-5 End /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/couchpotatoserver-custom/INFO ret=[0]
2019/06/27 03:54:36	install couchpotatoserver-custom 20180513-5 Begin /bin/rm -rf /var/packages/couchpotatoserver-custom/scripts
2019/06/27 03:54:36	install couchpotatoserver-custom 20180513-5 End /bin/rm -rf /var/packages/couchpotatoserver-custom/scripts ret=[0]
2019/06/27 03:54:36	install couchpotatoserver-custom 20180513-5 Begin /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/couchpotatoserver-custom/scripts
2019/06/27 03:54:36	install couchpotatoserver-custom 20180513-5 End /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/couchpotatoserver-custom/scripts ret=[0]
2019/06/27 03:54:36	install couchpotatoserver-custom 20180513-5 Begin /bin/rm -rf /var/packages/couchpotatoserver-custom/WIZARD_UIFILES
2019/06/27 03:54:36	install couchpotatoserver-custom 20180513-5 End /bin/rm -rf /var/packages/couchpotatoserver-custom/WIZARD_UIFILES ret=[0]
2019/06/27 03:54:36	install couchpotatoserver-custom 20180513-5 Begin /bin/mv -f /volume1/@tmp/pkginstall/WIZARD_UIFILES /var/packages/couchpotatoserver-custom/WIZARD_UIFILES
2019/06/27 03:54:36	install couchpotatoserver-custom 20180513-5 End /bin/mv -f /volume1/@tmp/pkginstall/WIZARD_UIFILES /var/packages/couchpotatoserver-custom/WIZARD_UIFILES ret=[0]
2019/06/27 03:54:36	install couchpotatoserver-custom 20180513-5 Begin /bin/rm -rf /var/packages/couchpotatoserver-custom/conf
2019/06/27 03:54:36	install couchpotatoserver-custom 20180513-5 End /bin/rm -rf /var/packages/couchpotatoserver-custom/conf ret=[0]
2019/06/27 03:54:36	install couchpotatoserver-custom 20180513-5 Begin /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/couchpotatoserver-custom/conf
2019/06/27 03:54:36	install couchpotatoserver-custom 20180513-5 End /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/couchpotatoserver-custom/conf ret=[0]
2019/06/27 03:54:37	install couchpotatoserver-custom 20180513-5 Begin postinst
delgroup: can't find couchpotatoserver-custom in /etc/group
deluser: unknown user couchpotatoserver-custom
2019/06/27 03:59:59	install couchpotatoserver-custom 20180513-5 End postinst ret=[0]
2019/06/27 03:59:59	install couchpotatoserver-custom 20180513-5 Begin /bin/rm -rf /volume1/@tmp/pkginstall
2019/06/27 03:59:59	install couchpotatoserver-custom 20180513-5 End /bin/rm -rf /volume1/@tmp/pkginstall ret=[0]
2019/06/27 04:00:03	install couchpotatoserver-custom 20180513-5 Begin start-stop-status start
Starting couchpotatoserver-custom ...
/var/packages/couchpotatoserver-custom/scripts/service-setup: line 18: type: service_prestart: not found
2019/06/27 04:00:37	install couchpotatoserver-custom 20180513-5 End start-stop-status start ret=[0]
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
2019/06/27 04:19:32	start couchpotatoserver-custom: begin to start version 20180513-5
2019/06/27 04:19:34	start couchpotatoserver-custom 20180513-5 Begin start-stop-status start
2019/06/27 04:19:43	start couchpotatoserver-custom 20180513-5 End start-stop-status start ret=[0]
2019/06/27 04:19:44	start couchpotatoserver-custom: start version 20180513-5 successfully, result 0```

**Comment by ymartin59** [comment]
As far as I know, that error message is a false positive (aka "expected") because generic start-stop script tries to invoke that "optional" function...

**Comment by leolobato** [comment]
Any other logs I can investigate?

**Comment by BenjV** [comment]
What is the problem?
The log is telling you that the package is started successfully.

**Comment by leolobato** [comment]
The problem is that it wouldn't actually start.

After a couple of seconds, the button will go back to "Run" on the UI (as if it's not running) and trying to access couchpotato on its port wouldn't work (connection refused).

Strangely enough, it did start correctly at some point after these 4 days. I tried stopping/running the service again just to be sure it was ok, and it went back to the same "not running" state.

**Comment by BenjV** [comment]
In that case it is not an package issue but an application issue.

Look in the arror.log and the CouchPotato.log in this folder:
/var/packages/couchpotatoserver/target/var/logs

**Comment by leolobato** [comment]
Thank you, found the issue on the application logs. Apparently, the database was corrupt:

```
$ cat /var/packages/couchpotatoserver-custom/target/var/logs/error.log 

Traceback (most recent call last):
  File "/volume1/@appstore/couchpotatoserver-custom/var/CouchPotatoServer/CouchPotato.py", line 135, in <module>
    l.run()
  File "/volume1/@appstore/couchpotatoserver-custom/var/CouchPotatoServer/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/volume1/@appstore/couchpotatoserver-custom/var/CouchPotatoServer/couchpotato/runner.py", line 142, in runCouchPotato
    db.open()
  File "/volume1/@appstore/couchpotatoserver-custom/var/CouchPotatoServer/libs/CodernityDB/database_super_thread_safe.py", line 43, in _inner
    res = f(*args, **kwargs)
  File "/volume1/@appstore/couchpotatoserver-custom/var/CouchPotatoServer/libs/CodernityDB/database_super_thread_safe.py", line 93, in open
    res = super(SuperThreadSafeDatabase, self).open(*args, **kwargs)
  File "/volume1/@appstore/couchpotatoserver-custom/var/CouchPotatoServer/libs/CodernityDB/database.py", line 571, in open
    index.open_index()
  File "/volume1/@appstore/couchpotatoserver-custom/var/CouchPotatoServer/libs/CodernityDB/hash_index.py", line 112, in open_index
    self._open_storage()
  File "/volume1/@appstore/couchpotatoserver-custom/var/CouchPotatoServer/libs/CodernityDB/hash_index.py", line 137, in _open_storage
    self.storage.open()
  File "/volume1/@appstore/couchpotatoserver-custom/var/CouchPotatoServer/libs/CodernityDB/storage.py", line 99, in open
    raise IOError("Storage doesn't exists!")
IOError: Storage doesn't exists!
```

The solution was to [delete the database](https://github.com/SynoCommunity/spksrc/issues/3184) and let CouchPotato recreate it.

So this issue can be closed.
