### ISSUE TITLE
[SabNZBD3] won't start, reference to python 2.7

### ISSUE THREAD

**Issue by pven** [SynoCommunity/spksrc#4145]
### Setup
_Package Name: sabnzbd
_Package Version: 3.0.1-42

_NAS Model: DS214+
_NAS Architecture: Marvell Armada XP MV78230
_DSM version: 6.2.3-25427 Update 2

### Expected behavior
Tell us what should happen

### Actual behavior
I've updated the SABnzb-package on my Synology DS214+ (this also included a Python3-upgrade). But after this SABnzbd won't start. There is a strange reference to python 2.7 in the logging, I have no idea where that is coming from.

### Steps to reproduce
_1._ Update package on my DS214+, this automatically triggers a Python3-update
_2._ Wait for it to start, it fails
_3._ Check the logging

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Starting sabnzbd ...
/var/packages/sabnzbd/scripts/service-setup: line 20: type: service_prestart: not found
2020/03/02 20:20:16     start sabnzbd 2.3.9-40 End start-stop-status start ret=[1]
2020/03/02 20:20:18     (system) trigger sabnzbd 2.3.9-40 Begin start-stop-status stop
sabnzbd is not running
2020/03/02 20:20:18     (system) trigger sabnzbd 2.3.9-40 End start-stop-status stop ret=[0]
2020/08/23 10:09:18     upgrade sabnzbd 2.3.9-40 Begin preupgrade
2020/08/23 10:09:23     upgrade sabnzbd 2.3.9-40 End preupgrade ret=[0]
2020/08/23 10:09:23     upgrade sabnzbd 2.3.9-40 Begin preuninst
/var/packages/sabnzbd/scripts/service-setup: line 20: type: service_preuninst: not found
2020/08/23 10:09:23     upgrade sabnzbd 2.3.9-40 End preuninst ret=[0]
2020/08/23 10:09:23     upgrade sabnzbd 2.3.9-40 Begin /bin/rm -rf /volume1/@appstore/sabnzbd
/bin/rm: cannot remove '/volume1/@appstore/sabnzbd': Directory not empty
2020/08/23 10:09:27     upgrade sabnzbd 2.3.9-40 End /bin/rm -rf /volume1/@appstore/sabnzbd ret=[1]
2020/08/23 10:09:27     upgrade sabnzbd 2.3.9-40 Begin /bin/mv -f /volume1/@appstore/sabnzbd /volume1/@tmp/pkg_fPZfiv
2020/08/23 10:09:27     upgrade sabnzbd 2.3.9-40 End /bin/mv -f /volume1/@appstore/sabnzbd /volume1/@tmp/pkg_fPZfiv ret=[0]
2020/08/23 10:09:27     upgrade sabnzbd 2.3.9-40 Begin postuninst
/var/packages/sabnzbd/scripts/service-setup: line 20: type: service_postuninst: not found
2020/08/23 10:09:28     upgrade sabnzbd 2.3.9-40 End postuninst ret=[0]
2020/08/23 10:09:28     upgrade sabnzbd 3.0.1-42 Begin preinst
2020/08/23 10:09:28     upgrade sabnzbd 3.0.1-42 End preinst ret=[0]
2020/08/23 10:09:28     upgrade sabnzbd 3.0.1-42 Begin /bin/rm -rf /volume1/@appstore/sabnzbd
2020/08/23 10:09:28     upgrade sabnzbd 3.0.1-42 End /bin/rm -rf /volume1/@appstore/sabnzbd ret=[0]
2020/08/23 10:09:28     upgrade sabnzbd 3.0.1-42 Begin /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/sabnzbd
2020/08/23 10:09:28     upgrade sabnzbd 3.0.1-42 End /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/sabnzbd ret=[0]
2020/08/23 10:09:28     upgrade sabnzbd 3.0.1-42 Begin /bin/mkdir -p /var/packages/sabnzbd
2020/08/23 10:09:28     upgrade sabnzbd 3.0.1-42 End /bin/mkdir -p /var/packages/sabnzbd ret=[0]
2020/08/23 10:09:28     upgrade sabnzbd 3.0.1-42 Begin /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/sabnzbd/INFO
2020/08/23 10:09:28     upgrade sabnzbd 3.0.1-42 End /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/sabnzbd/INFO ret=[0]
2020/08/23 10:09:28     upgrade sabnzbd 3.0.1-42 Begin /bin/rm -rf /var/packages/sabnzbd/scripts
2020/08/23 10:09:29     upgrade sabnzbd 3.0.1-42 End /bin/rm -rf /var/packages/sabnzbd/scripts ret=[0]
2020/08/23 10:09:29     upgrade sabnzbd 3.0.1-42 Begin /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/sabnzbd/scripts
2020/08/23 10:09:29     upgrade sabnzbd 3.0.1-42 End /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/sabnzbd/scripts ret=[0]
2020/08/23 10:09:29     upgrade sabnzbd 3.0.1-42 Begin /bin/rm -rf /var/packages/sabnzbd/WIZARD_UIFILES
2020/08/23 10:09:29     upgrade sabnzbd 3.0.1-42 End /bin/rm -rf /var/packages/sabnzbd/WIZARD_UIFILES ret=[0]
2020/08/23 10:09:29     upgrade sabnzbd 3.0.1-42 Begin /bin/mv -f /volume1/@tmp/pkginstall/WIZARD_UIFILES /var/packages/sabnzbd/WIZARD_UIFILES
2020/08/23 10:09:29     upgrade sabnzbd 3.0.1-42 End /bin/mv -f /volume1/@tmp/pkginstall/WIZARD_UIFILES /var/packages/sabnzbd/WIZARD_UIFILES ret=[0]
2020/08/23 10:09:29     upgrade sabnzbd 3.0.1-42 Begin /bin/rm -rf /var/packages/sabnzbd/conf
2020/08/23 10:09:29     upgrade sabnzbd 3.0.1-42 End /bin/rm -rf /var/packages/sabnzbd/conf ret=[0]
2020/08/23 10:09:29     upgrade sabnzbd 3.0.1-42 Begin /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/sabnzbd/conf
2020/08/23 10:09:29     upgrade sabnzbd 3.0.1-42 End /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/sabnzbd/conf ret=[0]
2020/08/23 10:09:30     upgrade sabnzbd 3.0.1-42 Begin postinst
2020/08/23 10:10:36     upgrade sabnzbd 3.0.1-42 End postinst ret=[0]
2020/08/23 10:10:36     upgrade sabnzbd 3.0.1-42 Begin postupgrade
/var/packages/sabnzbd/scripts/service-setup: line 63: /volume1/downloads/complete: Is a directory
2020/08/23 10:10:42     upgrade sabnzbd 3.0.1-42 End postupgrade ret=[0]
2020/08/23 10:10:42     upgrade sabnzbd 3.0.1-42 Begin /bin/rm -rf /volume1/@tmp/pkginstall
2020/08/23 10:10:42     upgrade sabnzbd 3.0.1-42 End /bin/rm -rf /volume1/@tmp/pkginstall ret=[0]
2020/08/23 10:12:55     start sabnzbd 3.0.1-42 Begin start-stop-status start
Starting sabnzbd ...
2020/08/23 10:13:45     start sabnzbd 3.0.1-42 End start-stop-status start ret=[1]
2020/08/23 10:13:47     (system) trigger sabnzbd 3.0.1-42 Begin start-stop-status stop
sabnzbd is not running
2020/08/23 10:13:47     (system) trigger sabnzbd 3.0.1-42 End start-stop-status stop ret=[0]
root@diskstation2:/var/log/packages#
```
#### Other logs
sabnzbd.log
```
2020-08-23 10:09:26,620::INFO::[misc:523] script_dir directory: /usr/local/sabnzbd/var/scripts does not exist, try to create it
2020-08-23 10:09:26,726::INFO::[_cplogging:219] [23/Aug/2020:10:09:26] HTTP
Request Headers:
  COOKIE: stay_login=1; tk_tc=PhMW4bBlmLcWI8xY; did=DAZejgmhnbEbYKbprZqo3nYBINUHW3CIg7ZvNmfk17tZVVNz8ZNtS1N0981Z06c7RkpltWotjSneqH3dPQEU1cZHJ48gnYQgsmqIaaDmYxdTtlNNPHOSjp6fGiFX39v; login_cookie=6a6dd4352162dda15293228862e5d052f3716d2d; login_salt=730; id=zQ8KWa0qv8TDTx2EFzE2olMuV7ppwf0juKbpyZRfnGA3Ro12QLetM1JiYzjCPbYASJtllwNAUtqvdg6CmTujsg; smid=EBLysIusVh1rdFylMTwnODRyyPsAgNn5D0F5rLnTik6RTwPS1GMHIfsXWjqd9cpRW3VsW5UZ6aL47GrzqgvJ1Q
  Remote-Addr: 192.168.1.108
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
  CONNECTION: keep-alive
  REFERER: https://local.stuff.com:10101/
  X-REQUESTED-WITH: XMLHttpRequest
  SEC-FETCH-MODE: cors
  HOST: local.stuff.com:10101
  SEC-FETCH-SITE: same-origin
  ACCEPT: */*
  ACCEPT-LANGUAGE: en-US,en;q=0.9,nl;q=0.8
  SEC-FETCH-DEST: empty
  ACCEPT-ENCODING: gzip, deflate, br
2020-08-23 10:09:26,789::ERROR::[_cplogging:219] [23/Aug/2020:10:09:26] HTTP
Traceback (most recent call last):
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/cherrypy/_cprequest.py", line 670, in respond
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/cherrypy/lib/encoding.py", line 220, in __call__
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/cherrypy/_cpdispatch.py", line 60, in __call__
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/interface.py", line 127, in internal_wrap
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/interface.py", line 944, in index
  File "/var/packages/python/target/lib/python2.7/site-packages/Cheetah/Template.py", line 1259, in __init__
    self._compile(source, file, compilerSettings=compilerSettings)
  File "/var/packages/python/target/lib/python2.7/site-packages/Cheetah/Template.py", line 1546, in _compile
    self._fileMtime = os.path.getmtime(file)
  File "/var/packages/sabnzbd/target/env/lib/python2.7/genericpath.py", line 62, in getmtime
OSError: [Errno 2] No such file or directory: '/var/packages/sabnzbd/target/share/SABnzbd/interfaces/Glitter/templates/queue.tmpl'
2020-08-23 10:09:27,533::INFO::[misc:523] script_dir directory: /usr/local/sabnzbd/var/scripts does not exist, try to create it
2020-08-23 10:09:27,534::ERROR::[misc:525] Cannot create directory /usr/local/sabnzbd/var/scripts
2020-08-23 10:09:30,548::INFO::[misc:523] script_dir directory: /usr/local/sabnzbd/var/scripts does not exist, try to create it
```
The directory mentioned in the last line exists btw.

After putting back the backup, and change two references in service-setup back to python2 the old SABnzbd works again. But off course I wat the new version.

What is going on?

**Comment by pven** [comment]
It works! :-) Thanks!

**Comment by BenjV** [comment]
@Safihre 
Could you please make a change to this package.
Because you are changing from python2 to python3 you should clear the old virtual environment folder and create a new python3 virtual environment in the "post upgrade" phase.
Otherwise it is tring to use site-packages from python2.7

**Comment by Safihre** [comment]
I thought the uninstall step removes the whole `/volume1/@appstore/sabnzbd/share/SABnzbd` directory.. Hmm.

**Comment by Safihre** [comment]
Yes, it seems it does:
```
2020/08/23 10:09:28     upgrade sabnzbd 3.0.1-42 Begin /bin/rm -rf /volume1/@appstore/sabnzbd
2020/08/23 10:09:28     upgrade sabnzbd 3.0.1-42 End /bin/rm -rf /volume1/@appstore/sabnzbd ret=[0]
```

**Comment by BenjV** [comment]
If you look at the log from @pven you see it still is the python2.7 version
> File "/var/packages/sabnzbd/target/env/lib/python2.7/genericpath.py", line 62, in getmtime

So why is that?

**Comment by Safihre** [comment]
Not sure.. I tried the upgrade path on my NAS and it worked with a previous package, it was a fresh virtualenv.
Would have to check again to verify.

**Comment by BenjV** [comment]
After your comment I tried to reproduce the problem and could not reproduce  it.

But if I look at the lfirst log of @pven, I find something strange in these lines:

> 2020/08/23 10:09:23     upgrade sabnzbd 2.3.9-40 Begin /bin/rm -rf /volume1/@appstore/sabnzbd
> /bin/rm: cannot remove '/volume1/@appstore/sabnzbd': Directory not empty

This can only happen when a process has a lock on a file in there.
Any Idea's?

**Comment by BenjV** [comment]
@Safihre 
Forget this item.

I spoke in another forum the original poster of this item and found out that he started en stopped Sabnzbd outside the packagecenter and that caused the failure.
Most likely there was still some locked files and he ended up with a mixture of two packages.

**Comment by Safihre** [comment]
@BenjV thanks for looking into it!
