### ISSUE TITLE
Can't install Z-Wave integration in Home Assistant

### ISSUE THREAD

**Issue by mcwieger** [SynoCommunity/spksrc#4183]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Home Assistant
_Package Version:_ 0.114.2-7

_NAS Model:_ DS414
_NAS Architecture:_ ArmadaXP
_DSM version:_ 6.2.3-25426

### Expected behavior
Installation of Z-Wave integration should install.

### Actual behavior
Z-Wave integration does not install

### Steps to reproduce
_1._ Open Home Assistant
_2._ Go to Settings > Integrations
_3._ Add Integration
_4._ Select Z-Wave

#### Package log

```
2020-09-16 16:43:25 ERROR (SyncWorker_19) [homeassistant.util.package] Unable to install package homeassistant-pyozw==0.1.10: ERROR: Command errored out with exit status 1:
   command: /volume1/@appstore/homeassistant/env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jcpsxdy2/homeassistant-pyozw/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jcpsxdy2/homeassistant-pyozw/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-4bf48gr8
       cwd: /tmp/pip-install-jcpsxdy2/homeassistant-pyozw/
  Complete output (16 lines):
  sysargv ['/tmp/pip-install-jcpsxdy2/homeassistant-pyozw/setup.py', 'bdist_wheel', '-d', '/tmp/pip-wheel-4bf48gr8']
  Found SETUP_DIR : /tmp/pip-install-jcpsxdy2/homeassistant-pyozw
  <pyozw_setup.EmbedTemplate object at 0x2bd19ab0>
  {'name': 'libopenzwave', 'sources': ['openzwave-embed/open-zwave-hass/python-openzwave/src-lib/libopenzwave/libopenzwave.cpp'], 'include_dirs': ['src-lib/libopenzwave/', 'openzwave-embed/open-zwave-hass/cpp/src', 'openzwave-embed/open-zwave-hass/cpp/src/value_classes', 'openzwave-embed/open-zwave-hass/cpp/src/platform', 'openzwave-embed/open-zwave-hass/cpp/build/linux'], 'define_macros': [('PY_LIB_VERSION', '0.1.10'), ('PY_SSIZE_T_CLEAN', 1), ('PY_LIB_FLAVOR', 'embed'), ('PY_LIB_BACKEND', 'cpp')], 'libraries': ['udev', 'stdc++', 'resolv'], 'extra_objects': ['openzwave-embed/open-zwave-hass/libopenzwave.a'], 'extra_compile_args': [], 'extra_link_args': [], 'language': 'c++'}
  ['six', 'PyDispatcher>=2.0.5']
  running bdist_wheel
  running build
  running build_openzwave
  Found g++ : None
  Found gcc : None
  Found make : None
  Found gmake : None
  Found cython : None
  Found pkg-config : None
  fetching https://raw.githubusercontent.com/home-assistant/python-openzwave/hass/archives/open-zwave-hass-0.1.10.zip into openzwave-embed/open-zwave.zip for version 0.1.10
  error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)>
  ----------------------------------------
  ERROR: Failed building wheel for homeassistant-pyozw
    ERROR: Command errored out with exit status 1:
     command: /volume1/@appstore/homeassistant/env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jcpsxdy2/homeassistant-pyozw/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jcpsxdy2/homeassistant-pyozw/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-2qy7njs1/install-record.txt --single-version-externally-managed --compile --install-headers /volume1/@appstore/homeassistant/env/include/site/python3.7/homeassistant-pyozw
         cwd: /tmp/pip-install-jcpsxdy2/homeassistant-pyozw/
    Complete output (16 lines):
    sysargv ['/tmp/pip-install-jcpsxdy2/homeassistant-pyozw/setup.py', 'install', '--record', '/tmp/pip-record-2qy7njs1/install-record.txt', '--single-version-externally-managed', '--compile', '--install-headers', '/volume1/@appstore/homeassistant/env/include/site/python3.7/homeassistant-pyozw']
    Found SETUP_DIR : /tmp/pip-install-jcpsxdy2/homeassistant-pyozw
    <pyozw_setup.EmbedTemplate object at 0x2bde8ab0>
    {'name': 'libopenzwave', 'sources': ['openzwave-embed/open-zwave-hass/python-openzwave/src-lib/libopenzwave/libopenzwave.cpp'], 'include_dirs': ['src-lib/libopenzwave/', 'openzwave-embed/open-zwave-hass/cpp/src', 'openzwave-embed/open-zwave-hass/cpp/src/value_classes', 'openzwave-embed/open-zwave-hass/cpp/src/platform', 'openzwave-embed/open-zwave-hass/cpp/build/linux'], 'define_macros': [('PY_LIB_VERSION', '0.1.10'), ('PY_SSIZE_T_CLEAN', 1), ('PY_LIB_FLAVOR', 'embed'), ('PY_LIB_BACKEND', 'cpp')], 'libraries': ['udev', 'stdc++', 'resolv'], 'extra_objects': ['openzwave-embed/open-zwave-hass/libopenzwave.a'], 'extra_compile_args': [], 'extra_link_args': [], 'language': 'c++'}
    ['six', 'PyDispatcher>=2.0.5']
    running install
    flavor embed
    running build_openzwave
    Found g++ : None
    Found gcc : None
    Found make : None
    Found gmake : None
    Found cython : None
    Found pkg-config : None
    fetching https://raw.githubusercontent.com/home-assistant/python-openzwave/hass/archives/open-zwave-hass-0.1.10.zip into openzwave-embed/open-zwave.zip for version 0.1.10
    error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)>
    ----------------------------------------
ERROR: Command errored out with exit status 1: /volume1/@appstore/homeassistant/env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jcpsxdy2/homeassistant-pyozw/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jcpsxdy2/homeassistant-pyozw/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-2qy7njs1/install-record.txt --single-version-externally-managed --compile --install-headers /volume1/@appstore/homeassistant/env/include/site/python3.7/homeassistant-pyozw Check the logs for full command output.
2020-09-16 16:43:25 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
    return await handler(request)
  File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/homeassistant/components/http/ban.py", line 73, in ban_middleware
    return await handler(request)
  File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/homeassistant/components/config/config_entries.py", line 112, in post
    return await super().post(request)
  File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/homeassistant/helpers/data_entry_flow.py", line 73, in post
    "show_advanced_options": data["show_advanced_options"],
  File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/homeassistant/data_entry_flow.py", line 117, in async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/homeassistant/config_entries.py", line 526, in async_create_flow
    await async_process_deps_reqs(self.hass, self._hass_config, integration)
  File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/homeassistant/setup.py", line 322, in async_process_deps_reqs
    hass, integration.domain
  File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/homeassistant/requirements.py", line 76, in async_get_integration_with_requirements
    hass, integration.domain, integration.requirements
  File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/homeassistant/requirements.py", line 132, in async_process_requirements
    raise RequirementsNotFound(name, [req])
homeassistant.requirements.RequirementsNotFound: Requirements for zwave not found: ['homeassistant-pyozw==0.1.10'].

```

**Comment by BenjV** [comment]
https://github.com/SynoCommunity/spksrc/issues/4137

**Comment by ymartin59** [comment]
Anyway support for Zwave is far from obvious on DSM
