### ISSUE TITLE
Home Assistant installed on Synology DS918+ not polling Homematic-IP 

### ISSUE THREAD

**Issue by eL-Zotto** [SynoCommunity/spksrc#4190]
_For new Package Requests, see the guidelines_  

## The problem
Hello

I installed and configured Home Assistant on my Synology DS918+ yesterday. I used the homeassistant package and NOT hassio!
I can open the page on port 8123 and went through the first steps, where I integrated my Homematic-IP AccessPoint.
I see all my Homematic devices and grouped them according the rooms they are located in.
When I chack a temperature senor, I only see 1 tick (measured value), taken at the time I configured my AccessPoint (24 hours ago).
No new ticks seem to be collected. When I restart the homeassistant service on my DS, a new tick will be taken.
What went wrong?
Thank you for your support

Regards
Laurent

## Additional information
Port forwarding enabled on FritzBox

### Setup
_Package Name:_ Home Assistant
_Package Version:_ 0.114.2-7

_NAS Model:_ Synology DS 918+
_NAS Architecture:_ AMD
_DSM version:_ 6.2.3-25426 Update 2

### Expected behavior
Homa Assistant should get data from my homematic-IP on regular intervals.

### Actual behavior
I only get 1 mesure (tick) each time the Home Assistant services are restarted

### Steps to reproduce
_1._ 
_2._ 
_3._ 

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
2020-09-24 13:40:35 ERROR (MainThread) [homematicip.aio.connection] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)
Traceback (most recent call last):
  File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/homematicip/aio/connection.py", line 120, in _connect_to_websocket
    loop=self._loop,
  File "/var/packages/python3/target/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/var/packages/python3/target/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/websockets/client.py", line 535, in __await_impl__
    transport, protocol = await self._create_connection()
  File "/var/packages/python3/target/lib/python3.7/asyncio/base_events.py", line 989, in create_connection
    ssl_handshake_timeout=ssl_handshake_timeout)
  File "/var/packages/python3/target/lib/python3.7/asyncio/base_events.py", line 1017, in _create_connection_transport
    await waiter
  File "/var/packages/python3/target/lib/python3.7/asyncio/sslproto.py", line 530, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/var/packages/python3/target/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/var/packages/python3/target/lib/python3.7/ssl.py", line 774, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)
2020-09-24 13:40:35 ERROR (MainThread) [homeassistant.components.homematicip_cloud.hap] Error connecting to HomematicIP with HAP 3014F711A00003DA49A90878. Retrying in 256 seconds
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by ymartin59** [comment]
Known issue: #4137

**Comment by eL-Zotto** [comment]
If I go for solution 2....
admin@DS:~$ ll /var/packages/python/target/lib/python2.7/site-packages/certifi/cacert.pem
ls: cannot access /var/packages/python/target/lib/python2.7/site-packages/certifi/cacert.pem: No such file or directory

I tried this...

``
admin@DS:~$ sudo su -
Password:
root@DS:~# wget -O /var/packages/python3/target/cert.pem 'https://raw.githubusercontent.com/certifi/python-certifi/master/certifi/cacert.pem'
--2020-09-25 07:26:30--  'https://raw.githubusercontent.com/certifi/python-certifi/master/certifi/cacert.pem'
Resolving raw.githubusercontent.com... 151.101.112.133
Connecting to raw.githubusercontent.com|151.101.112.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 282394 (276K) [text/plain]
Saving to: '/var/packages/python3/target/cert.pem'

/var/packages/python3/target/cert.pem  100%[=========================================================================>] 275.78K  --.-KB/s    in 0.1s

2020-09-25 07:26:31 (2.51 MB/s) - '/var/packages/python3/target/cert.pem' saved [282394/282394]

root@DS:~#
``

Then I restarted the Home Assistant package.

The SSL error disapeared! but still not updates from homematic-IP since 6 minutes.
I ceck later today

**Comment by eL-Zotto** [comment]
Home Assistant is getting the values from homematic-IP now... Thank yiu

**Comment by ymartin59** [comment]
As a definitive fix, Python 3 has to be rebuilt and pubilsh with properly configured (and upgraded to latest) openssl dependency. It should come soon now.

**Comment by BenjV** [comment]
I saw both Python 2 and Python3 packages with a fix for this certificate problem appearing in my package center.

**Comment by eL-Zotto** [comment]
The issue was solved with correct SSL certificates inplemented
