### ISSUE TITLE
Home Assistant Core >> Error for integration tradfri

### ISSUE THREAD

**Issue by alardeux** [SynoCommunity/spksrc#4343]
### Setup
Package Name: Home Assistant Core
Package Version: 0.118.5-10
Python Version: 3.7.7 (synoCommunity)

NAS Model: DS218 play
NAS Architecture: aarch64
DSM version: DSM 6.2.3-25426 Update 3

### Expected behavior
To succeed the Tradfri integration by starting with a prompt for credential.

### Actual behavior
No integration at all.
Error: No module named 'aiocoap'

### Steps to reproduce
1. Install the package
2. Run HA 
3. Create an account
4. Add integration Tradfri (not auto discovered) --> error 

#### Package log

2020-12-30 15:11:25 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration tradfri: No module named 'aiocoap'
2020-12-30 15:11:25 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/homeassistant/config_entries.py", line 535, in async_create_flow
integration.get_platform("config_flow")
File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/homeassistant/loader.py", line 424, in get_platform
cache[full_name] = self._import_platform(platform_name)
File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/homeassistant/loader.py", line 429, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
File "/var/packages/python3/target/lib/python3.7/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
File "<frozen importlib._bootstrap>", line 983, in _find_and_load
File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
File "<frozen importlib._bootstrap>", line 983, in _find_and_load
File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 728, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/homeassistant/components/tradfri/__init__.py", line 7, in <module>
from pytradfri.api.aiocoap_api import APIFactory
File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/pytradfri/api/aiocoap_api.py", line 6, in <module>
from aiocoap import Message, Context
ModuleNotFoundError: No module named 'aiocoap'

And by the way:

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/homeassistant/data_entry_flow.py", line 119, in async_init
flow = await self.async_create_flow(handler, context=context, data=data)
File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/homeassistant/config_entries.py", line 542, in async_create_flow
raise data_entry_flow.UnknownHandler
homeassistant.data_entry_flow.UnknownHandler

**Comment by hgy59** [comment]
@alardeux sorry for this, now I found out, that I have to verify all off the 227 Integrations before publishing an update!

**Comment by alardeux** [comment]
> @alardeux sorry for this, now I found out, that I have to verify all off the 224 Integrations before publishing an update!

No worries ;-)
I would say that this github is made for such a feedback. The community is there for sharing the tasks and make HA moving forward. Thanks again for the nice job about porting HA natively on DSM (especially for those without docker support!)

Update: I installed manually aiocoap-0.3 via wheel and now on I encounter an issue with aiocoap.credentials.
Not surprising btw cause there is no credentials.py file in the aiocoap's package directory. Weird...

Don't hesitate to suggest any proposals/guidances that I might implement and try.
Cheers.

**Comment by hgy59** [comment]
> Update: I installed manually aiocoap-0.3 via wheel and now on I encounter an issue with aiocoap.credentials.
> Not surprising btw cause there is no credentials.py file in the aiocoap's package directory. Weird...

Same here (and aiocoap is still in Development Status 4 - Beta, and version 0.3 is from 2016)

**Comment by hgy59** [comment]
Currently failing integrations
- [ ] IKEA TRÅDFRI
- [ ] Apple iCloud
- [ ]

**Comment by hgy59** [comment]
> 
> 
> > Update: I installed manually aiocoap-0.3 via wheel and now on I encounter an issue with aiocoap.credentials.
> > Not surprising btw cause there is no credentials.py file in the aiocoap's package directory. Weird...
> 
> Same here (and aiocoap is still in Development Status 4 - Beta, and version 0.3 is from 2016)

with `aiocoap==0.4b3` it seems to work
