### ISSUE TITLE
Can't connect to Ikea Tradfri gateway

### ISSUE THREAD

**Issue by reapp3r** [SynoCommunity/spksrc#4403]
### Setup
_Package Name:_ Home Assistant Core / Tradfri Integration
_Package Version:_ 0.118.5-11

_NAS Model:_ DS218+
_NAS Architecture:_ INTEL Celeron J3355
_DSM version:_ DSM 6.2.3-25426 Update 3

### Expected behavior
Connect from NAS to IKEA Tradfri Gateway

### Actual behavior
Connect dialog box shows "Unknown error occurred" when I press submit
The following is added to the logs:

```
Logger: aiohttp.server
Source: components/tradfri/config_flow.py:168 
First occurred: 13 January 2021, 14:41:39 (10 occurrences) 
Last logged: 7:22:20

Error handling request
Traceback (most recent call last):
  File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 118, in impl
    return await handler(request)
  File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/homeassistant/components/config/config_entries.py", line 169, in post
    return await super().post(request, flow_id)
  File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/homeassistant/helpers/data_entry_flow.py", line 106, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/homeassistant/data_entry_flow.py", line 155, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/homeassistant/data_entry_flow.py", line 213, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/homeassistant/components/tradfri/config_flow.py", line 54, in async_step_auth
    self.hass, host, user_input[KEY_SECURITY_CODE]
  File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/homeassistant/components/tradfri/config_flow.py", line 168, in authenticate
    key = await api_factory.generate_psk(security_code)
  File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/pytradfri/api/aiocoap_api.py", line 216, in generate_psk
    self._psk = await self.request(command)
  File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/pytradfri/api/aiocoap_api.py", line 164, in request
    result = await self._execute(api_commands)
  File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/pytradfri/api/aiocoap_api.py", line 148, in _execute
    _, res = await self._get_response(msg)
  File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/pytradfri/api/aiocoap_api.py", line 96, in _get_response
    r = await pr.response
  File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/aiocoap/protocol.py", line 731, in _run_outer
    await cls._run(app_request, response, weak_observation, protocol, log)
  File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/aiocoap/protocol.py", line 756, in _run
    await protocol.find_remote_and_interface(app_request)
  File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/aiocoap/protocol.py", line 301, in find_remote_and_interface
    raise RuntimeError("No request interface could route message")
RuntimeError: No request interface could route message
```

### Steps to reproduce
_1._ Add IKEA Tradfri integration, provide IP address and security code of Gateway
_2._ Press submit

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
See above

#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
See above

**Comment by hgy59** [comment]
@reapp3r can you try the solution given in the upstream [issue](https://github.com/home-assistant/core/issues/15079)?

**Comment by reapp3r** [comment]
Thanks @hgy59, any clues on how to install dtlssocket in the python bundled with the Synology app?

**Comment by hgy59** [comment]
@reapp3r my question for you is: does the installation of dtlssocket really solve your issue?

**Comment by hgy59** [comment]
> Thanks @hgy59, any clues on how to install dtlssocket in the python bundled with the Synology app?

@reapp3r sorry for my miss understanding. I have now pushed an update that includes the DTLSSocket package in  #4421.

As I do not have access to a tradfri gateway, can you please test with the homeassistant 2021.1.5 update?
_you need python3.8 for this_

**Comment by hgy59** [comment]
@reapp3r did you ever try tradfri with homeassistant core 2021.1.5 (#4421)?
As I'm working on the update for homeassistant core 2021.4.6 (#4580) I would like to know whether we can close this issue or anything remains to do.
