### ISSUE TITLE
Unable to Start Home Assistant Core

### ISSUE THREAD

**Issue by Forge36** [SynoCommunity/spksrc#4418]
### Setup
_Package Name:_ Home Assistant Core
_Package Version:_ 0.118.5-11

_NAS Model:_ DS416j
_NAS Architecture:_ MARVELL Armada 388 88F6828
_DSM version:_ 6.2.3-25426 Update 3

### Expected behavior
Home Assistant should be available under port 8123

### Actual behavior
"Nothing" (see error log for aiohttp/_http_parser.pyx exception)

### Steps to reproduce
_1._ Stop Home Assistant Core
_2._ Start Home Assistant Core
_3._ Monitor homeassistant.log

#### Package log
```
homeassistant.log
[...]
2021-01-30 16:35:16 WARNING (MainThread) [homeassistant.bootstrap] Support for the running Python version 3.7.7 is depr
ecated and will be removed in the first release after December 7, 2020. Please upgrade Python to 3.8.0 or higher.
2021-01-30 16:35:16 INFO (MainThread) [homeassistant.core] Starting Home Assistant
2021-01-30 16:35:16 INFO (MainThread) [homeassistant.core] Timer:starting
2021-01-30 16:42:11 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 314, in data_re
ceived
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'invalid HTTP method'"
2021-01-30 16:42:12 ERROR (MainThread) [aiohttp.server] Error handling request
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
/var/log/synopkg.log
2021/01/30 16:34:45     stop homeassistant: begin to stop version 0.118.5-11
2021/01/30 16:34:45     stop homeassistant 0.118.5-11 Begin start-stop-status stop
2021/01/30 16:34:46     stop homeassistant 0.118.5-11 End start-stop-status stop ret=[0]
2021/01/30 16:34:46     stop homeassistant 0.118.5-11 Begin unload apparmor
2021/01/30 16:34:46     stop homeassistant 0.118.5-11 End unload apparmor ret=[0]
2021/01/30 16:34:47     stop homeassistant: stop version 0.118.5-11 successfully, result 0
2021/01/30 16:34:58     start homeassistant: begin to start version 0.118.5-11
2021/01/30 16:34:59     start homeassistant 0.118.5-11 Begin pre-load apparmor
2021/01/30 16:34:59     start homeassistant 0.118.5-11 End pre-load apparmor ret=[0]
2021/01/30 16:34:59     start homeassistant 0.118.5-11 Begin start-stop-status start
2021/01/30 16:35:07     start homeassistant 0.118.5-11 End start-stop-status start ret=[0]
2021/01/30 16:35:07     start homeassistant: start version 0.118.5-11 successfully, result 0
```

**Comment by Forge36** [comment]
I did find: https://github.com/aio-libs/aiohttp/issues/5358 
I'm a little lost on what to debug next.

Some random guessing: I think I have HSTS configured, which is causing aiohttp to encounter issues. I had a previous home assistant instance (~0.104 which I couldn't update) I had a key/cert in my config file, but I didn't copy any of that over to this instance trying to get a "cleanup startup" first.

I ended up copying my .yaml files and previous storage into the `spksrc` version. I'm now able to start AND login using my old configuration.

HTTPS configuration was fixed by running:
```
cp /usr/syno/etc/certificate/system/default/* /volume1/homes/homeassistant/cert/
chown sc-homeassistant /volume1/homes/homeassistant/cert/*
```
Though I'm not certain _why_ that's required for this instance (note: my old instance was probably setup in an awful way)
