### ISSUE TITLE
[Bug] ZHA (zigbee) not working after home assistant core update to 2021.1.5

### ISSUE THREAD

**Issue by rs1gg** [SynoCommunity/spksrc#4458]
### Setup
_Package Name:_ Home Assistant Core (spk/homeassistant)
_Package Version:_ 2021.1.5

_NAS Model:_ DS214+
_NAS Architecture:_ armadaxp
_DSM version:_ 6.2.3-25426 Update 3

### Expected behavior
Zigbee integration (zha) works. It worked before on package version 0.118.5 (python 3.7 from synology)

### Actual behavior
Home assistant core 2021.1.5 starts up correctly. But when configuring the zha integration, dependency errors are shown in the homeassistant.log (see below).

### Steps to reproduce
_1._ Install python 3.8 from syno community repository
_2._ Install Home Assistant Core 2021.1.5 from syno community repository, start, onboard
_3._ In the homeassistant gui, add the zha integration, which fails with errors in the log

I don't really understand the dependencies with different kind of native/non-native modules/wheels, etc. But I would be happy to try things out and am also able to build an spk on my own.

#### Package log
```
[add zha integration start]

2021-02-27 10:03:01 INFO (SyncWorker_7) [homeassistant.util.package] Attempting install of bellows==0.21.0
2021-02-27 10:04:08 ERROR (SyncWorker_7) [homeassistant.util.package] Unable to install package bellows==0.21.0: ERROR: Command errored out with exit status 1:
   command: /volume1/@appstore/homeassistant/env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/volume1/@appstore/homeassistant/tmp/pip-install-72lvopei/pycryptodome/setup.py'"'"'; __file__='"'"'/volume1/@appstore/homeassistant/tmp/pip-install-72lvopei/pycryptodome/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /volume1/@appstore/homeassistant/tmp/pip-wheel-bcqzo5ir
       cwd: /volume1/@appstore/homeassistant/tmp/pip-install-72lvopei/pycryptodome/
  Complete output (311 lines):
  Testing support for clang
  Target does not support clang
  Testing support for gcc
  Target does not support gcc
  Testing support for stdint.h header

[skip many copying/creating lines]

  copying lib/Crypto/Math/_IntegerNative.pyi -> build/lib.linux-armv7l-3.8/Crypto/Math
  copying lib/Crypto/Math/_IntegerBase.pyi -> build/lib.linux-armv7l-3.8/Crypto/Math
  copying lib/Crypto/Math/Primality.pyi -> build/lib.linux-armv7l-3.8/Crypto/Math
  running build_ext
  building 'Crypto.Hash._MD2' extension
  creating build/temp.linux-armv7l-3.8
  creating build/temp.linux-armv7l-3.8/src
  /spksrc/toolchain/syno-armv7-6.1/work/arm-unknown-linux-gnueabi/bin/arm-unknown-linux-gnueabi-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/spksrc/toolchain/syno-armv7-6.1/work/arm-unknown-linux-gnueabi/arm-unknown-linux-gnueabi/sysroot/usr/include -I/spksrc/spk/python38/work-armv7-6.1/install//var/packages/python38/target/include -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -L /spksrc/spk/python38/work-armv7-6.1/install/var/packages/python38/target/lib -I /spksrc/spk/python38/work-armv7-6.1/install/var/packages/python38/target/include -I/spksrc/toolchain/syno-armv7-6.1/work/arm-unknown-linux-gnueabi/arm-unknown-linux-gnueabi/sysroot/usr/include -I/spksrc/spk/python38/work-armv7-6.1/install//var/packages/python38/target/include -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -L /spksrc/spk/python38/work-armv7-6.1/install/var/packages/python38/target/lib -I /spksrc/spk/python38/work-armv7-6.1/install/var/packages/python38/target/include -fPIC -DPYCRYPTO_LITTLE_ENDIAN -DSYS_BITS=32 -DLTC_NO_ASM -Isrc/ -I/volume1/@appstore/homeassistant/env/include -I/var/packages/python38/target/include/python3.8 -c src/MD2.c -o build/temp.linux-armv7l-3.8/src/MD2.o
  unable to execute '/spksrc/toolchain/syno-armv7-6.1/work/arm-unknown-linux-gnueabi/bin/arm-unknown-linux-gnueabi-gcc': No such file or directory
  error: command '/spksrc/toolchain/syno-armv7-6.1/work/arm-unknown-linux-gnueabi/bin/arm-unknown-linux-gnueabi-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pycryptodome
ERROR: xbee-helper 0.0.7 requires xbee, which is not installed.
ERROR: pygatt 4.0.5 requires enum-compat, which is not installed.
    ERROR: Command errored out with exit status 1:
     command: /volume1/@appstore/homeassistant/env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/volume1/@appstore/homeassistant/tmp/pip-install-72lvopei/pycryptodome/setup.py'"'"'; __file__='"'"'/volume1/@appstore/homeassistant/tmp/pip-install-72lvopei/pycryptodome/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /volume1/@appstore/homeassistant/tmp/pip-record-ql4o_dc_/install-record.txt --single-version-externally-managed --compile --install-headers /volume1/@appstore/homeassistant/env/include/site/python3.8/pycryptodome
         cwd: /volume1/@appstore/homeassistant/tmp/pip-install-72lvopei/pycryptodome/
    Complete output (311 lines):
    Testing support for clang
    Target does not support clang
    Testing support for gcc

[skip many copying/creating lines]

    copying lib/Crypto/Math/_IntegerNative.pyi -> build/lib.linux-armv7l-3.8/Crypto/Math
    copying lib/Crypto/Math/_IntegerBase.pyi -> build/lib.linux-armv7l-3.8/Crypto/Math
    copying lib/Crypto/Math/Primality.pyi -> build/lib.linux-armv7l-3.8/Crypto/Math
    running build_ext
    building 'Crypto.Hash._MD2' extension
    creating build/temp.linux-armv7l-3.8
    creating build/temp.linux-armv7l-3.8/src
    /spksrc/toolchain/syno-armv7-6.1/work/arm-unknown-linux-gnueabi/bin/arm-unknown-linux-gnueabi-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/spksrc/toolchain/syno-armv7-6.1/work/arm-unknown-linux-gnueabi/arm-unknown-linux-gnueabi/sysroot/usr/include -I/spksrc/spk/python38/work-armv7-6.1/install//var/packages/python38/target/include -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -L /spksrc/spk/python38/work-armv7-6.1/install/var/packages/python38/target/lib -I /spksrc/spk/python38/work-armv7-6.1/install/var/packages/python38/target/include -I/spksrc/toolchain/syno-armv7-6.1/work/arm-unknown-linux-gnueabi/arm-unknown-linux-gnueabi/sysroot/usr/include -I/spksrc/spk/python38/work-armv7-6.1/install//var/packages/python38/target/include -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -L /spksrc/spk/python38/work-armv7-6.1/install/var/packages/python38/target/lib -I /spksrc/spk/python38/work-armv7-6.1/install/var/packages/python38/target/include -fPIC -DPYCRYPTO_LITTLE_ENDIAN -DSYS_BITS=32 -DLTC_NO_ASM -Isrc/ -I/volume1/@appstore/homeassistant/env/include -I/var/packages/python38/target/include/python3.8 -c src/MD2.c -o build/temp.linux-armv7l-3.8/src/MD2.o
    unable to execute '/spksrc/toolchain/syno-armv7-6.1/work/arm-unknown-linux-gnueabi/bin/arm-unknown-linux-gnueabi-gcc': No such file or directory
    error: command '/spksrc/toolchain/syno-armv7-6.1/work/arm-unknown-linux-gnueabi/bin/arm-unknown-linux-gnueabi-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /volume1/@appstore/homeassistant/env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/volume1/@appstore/homeassistant/tmp/pip-install-72lvopei/pycryptodome/setup.py'"'"'; __file__='"'"'/volume1/@appstore/homeassistant/tmp/pip-install-72lvopei/pycryptodome/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /volume1/@appstore/homeassistant/tmp/pip-record-ql4o_dc_/install-record.txt --single-version-externally-managed --compile --install-headers /volume1/@appstore/homeassistant/env/include/site/python3.8/pycryptodome Check the logs for full command output.
WARNING: You are using pip version 20.0.2; however, version 21.0.1 is available.
You should consider upgrading via the '/volume1/@appstore/homeassistant/env/bin/python -m pip install --upgrade pip' command.
2021-02-27 10:04:08 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 118, in impl
    return await handler(request)
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
    return await handler(request)
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/components/config/config_entries.py", line 136, in post
    return await super().post(request)
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/helpers/data_entry_flow.py", line 69, in post
    result = await self._flow_mgr.async_init(
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/data_entry_flow.py", line 119, in async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/config_entries.py", line 532, in async_create_flow
    await async_process_deps_reqs(self.hass, self._hass_config, integration)
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/setup.py", line 343, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/requirements.py", line 76, in async_get_integration_with_requirements
    await async_process_requirements(
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/requirements.py", line 133, in async_process_requirements
    raise RequirementsNotFound(name, [req])
homeassistant.requirements.RequirementsNotFound: Requirements for zha not found: ['bellows==0.21.0'].
```

**Comment by hgy59** [comment]
got it.

@rs1gg as temp. workaround you can manually install the missing packages by running the following command in /var/packages/homeassistant/target/env/bin:

`./pip install bellows==0.21.0 zha-quirks==0.0.51 zigpy-cc==0.5.2 zigpy-deconz==0.11.1 zigpy-xbee==0.13.0 zigpy-zigate==0.7.3 zigpy-znp==0.3.0 zigpy==0.30.0`

Then you need to restart homeassistant before adding the `Zigbee Home Automation` integration.

**Comment by hgy59** [comment]
I think there should be some investigations to avoid the need of packaging pure pyhton wheels into the spk.

**Comment by rs1gg** [comment]
Workaround worked, thanks a lot! (had to be careful with filesystem user permissions/ownership - pip falls back to some kind of user repo if the current cache is not writable which then is not available to HA)

The two ERRORs (and the warning about pip version 20->21) still exist but don't bother me so far.
````
ERROR: xbee-helper 0.0.7 requires xbee, which is not installed.
ERROR: pygatt 4.0.5 requires enum-compat, which is not installed.
````

**Comment by rs1gg** [comment]
From the log, bellows seems to depend on pycryptodome, whose setup.py tried to compile some crypto lib functions which in turn triggered the error.

However, in the workaround, pycryptodome was installed as a dependency to zigpy without error, see [workaround.txt](https://github.com/SynoCommunity/spksrc/files/6054432/workaround.txt).

**Comment by smaarn** [comment]
> I think there should be some investigations to avoid the need of packaging pure pyhton wheels into the spk.

I wonder if there isn't an issue with the default way pip now works with build isolation mechanisms. Which is one of the reason why our wheel builds are customized to avoid that.

**Comment by smaarn** [comment]
> Workaround worked, thanks a lot! (had to be careful with filesystem user permissions/ownership - pip falls back to some kind of user repo if the current cache is not writable which then is not available to HA)
> 
> The two ERRORs (and the warning about pip version 20->21) still exist but don't bother me so far.
> 
> ```
> ERROR: xbee-helper 0.0.7 requires xbee, which is not installed.
> ERROR: pygatt 4.0.5 requires enum-compat, which is not installed.
> ```

What do you mean by "careful with filesystem user permissions/ownership" ?

**Comment by ymartin59** [comment]
@hgy59 I agree. I was used to get (some / most) pure python packages from DSM without trouble. But here, package rule tries to find compiler/link on DSM...
