### ISSUE TITLE
Deluge installation errors, can't run package. Pls Help!

### ISSUE THREAD

**Issue by kelvinade** [SynoCommunity/spksrc#4516]
### Setup
_Package Name:_ Deluge
_Package Version:_ 2.0.3-12

_NAS Model:_DS213J
_NAS Architecture:_Armada 370
_DSM version:_6.2.4-25556

### Expected behavior
I reset DSM, installed Deluge, it should Run. 

### Actual behavior
"Failed to run the package service" error message is displayed. I see errors in the deluge install log files. Can you pls help? Maybe it's a Python issue based on installation log errors... I'm not a programmer.

### Steps to reproduce
_1._ Reset DSM.
_2._ Install Deluge from package center
_3._ 

#### Package log
_find logfiles in `/var/packages/{package}/var/`, for DSM7: `/var/log/packages/{package}.log`, for DSM < 6.0: protocol in Package Center.
_
```
relevant portions of /volume1/@appstore/deluge/var/deluge_install.log

Installing collected packages: Mako, PyHamcrest, characteristic, chardet, pyasn1-modules, python-libtorrent, pyxdg, rencode, service-identity, setproc
title
  Attempting uninstall: chardet
    Found existing installation: chardet 3.0.4
    Not uninstalling chardet at /volume1/@appstore/python/lib/python2.7/site-packages, outside environment /volume1/@appstore/deluge/env
    Can't uninstall 'chardet'. No files were found to uninstall.
Successfully installed Mako-1.1.2 PyHamcrest-1.10.1 characteristic-14.3.0 chardet-3.0.4 pyasn1-modules-0.2.8 python-libtorrent-1.1.14 pyxdg-0.26 renco
de-1.0.6 service-identity-18.1.0 setproctitle-1.1.10
running build
running build_webui
Warning: No minifying command found.
Minifying deluge/ui/web/js/deluge-all
Warning: Failed minifying files deluge/ui/web/js/deluge-all, debug only
Minifying deluge/ui/web/js/extjs/ext-extensions
Warning: Failed minifying files deluge/ui/web/js/extjs/ext-extensions, debug only
Creating WebUI translation file: deluge/ui/web/js/deluge-all/gettext.js
running build_trans
Compiling po files from deluge/i18n...
id, cy, Traceback (most recent call last):
  File "setup.py", line 604, in <module>
    entry_points=_entry_points,
  File "/volume1/@appstore/deluge/env/lib/python2.7/site-packages/setuptools/__init__.py", line 162, in setup
    return distutils.core.setup(**attrs)
  File "/var/packages/python/target/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/var/packages/python/target/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/var/packages/python/target/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 393, in run
    _build.run(self)
  File "/var/packages/python/target/lib/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/var/packages/python/target/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/var/packages/python/target/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 237, in run
    msgfmt.make(src, dest)
  File "/volume1/@appstore/deluge/share/deluge/msgfmt.py", line 183, in make
    line = ast.literal_eval(line)
  File "/var/packages/python/target/lib/python2.7/ast.py", line 49, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/var/packages/python/target/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 2
    msgstr "Ategion"
         ^
SyntaxError: invalid syntax
Granting 'sc-deluge' unix ownership on /volume1/@appstore/deluge/env
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
/var/log/packages/deluge.log

2021/03/23 10:18:46     install deluge 2.0.3-12 Begin preinst
2021/03/23 10:18:47     install deluge 2.0.3-12 End preinst ret=[0]
2021/03/23 10:18:47     install deluge 2.0.3-12 Begin /bin/rm -rf /volume1/@appstore/deluge
2021/03/23 10:18:47     install deluge 2.0.3-12 End /bin/rm -rf /volume1/@appstore/deluge ret=[0]
2021/03/23 10:18:47     install deluge 2.0.3-12 Begin /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/deluge
2021/03/23 10:18:47     install deluge 2.0.3-12 End /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/deluge ret=[0]
2021/03/23 10:18:47     install deluge 2.0.3-12 Begin /bin/rm -rf /var/packages/deluge
2021/03/23 10:18:47     install deluge 2.0.3-12 End /bin/rm -rf /var/packages/deluge ret=[0]
2021/03/23 10:18:47     install deluge 2.0.3-12 Begin /bin/mkdir -p /var/packages/deluge
2021/03/23 10:18:47     install deluge 2.0.3-12 End /bin/mkdir -p /var/packages/deluge ret=[0]
2021/03/23 10:18:47     install deluge 2.0.3-12 Begin /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/deluge/INFO
2021/03/23 10:18:47     install deluge 2.0.3-12 End /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/deluge/INFO ret=[0]
2021/03/23 10:18:47     install deluge 2.0.3-12 Begin /bin/rm -rf /var/packages/deluge/scripts
2021/03/23 10:18:47     install deluge 2.0.3-12 End /bin/rm -rf /var/packages/deluge/scripts ret=[0]
2021/03/23 10:18:47     install deluge 2.0.3-12 Begin /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/deluge/scripts
2021/03/23 10:18:47     install deluge 2.0.3-12 End /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/deluge/scripts ret=[0]
2021/03/23 10:18:47     install deluge 2.0.3-12 Begin /bin/rm -rf /var/packages/deluge/WIZARD_UIFILES
2021/03/23 10:18:47     install deluge 2.0.3-12 End /bin/rm -rf /var/packages/deluge/WIZARD_UIFILES ret=[0]
2021/03/23 10:18:47     install deluge 2.0.3-12 Begin /bin/mv -f /volume1/@tmp/pkginstall/WIZARD_UIFILES /var/packages/deluge/WIZARD_UIFILES
2021/03/23 10:18:47     install deluge 2.0.3-12 End /bin/mv -f /volume1/@tmp/pkginstall/WIZARD_UIFILES /var/packages/deluge/WIZARD_UIFILES ret=[0]
2021/03/23 10:18:47     install deluge 2.0.3-12 Begin /bin/rm -rf /var/packages/deluge/conf
2021/03/23 10:18:47     install deluge 2.0.3-12 End /bin/rm -rf /var/packages/deluge/conf ret=[0]
2021/03/23 10:18:47     install deluge 2.0.3-12 Begin /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/deluge/conf
2021/03/23 10:18:47     install deluge 2.0.3-12 End /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/deluge/conf ret=[0]
2021/03/23 10:18:49     install deluge 2.0.3-12 Begin postinst
delgroup: can't find deluge in /etc/group
deluser: unknown user deluge
2021/03/23 10:21:24     install deluge 2.0.3-12 End postinst ret=[0]
2021/03/23 10:21:24     install deluge 2.0.3-12 Begin /bin/rm -rf /volume1/@tmp/pkginstall
2021/03/23 10:21:24     install deluge 2.0.3-12 End /bin/rm -rf /volume1/@tmp/pkginstall ret=[0]
2021/03/23 10:38:40     start deluge 2.0.3-12 Begin start-stop-status start
Starting deluge ...
env: /volume1/@appstore/deluge/env/bin/deluged: No such file or directory
env: /volume1/@appstore/deluge/env/bin/deluge-web: No such file or directory
2021/03/23 10:38:43     start deluge 2.0.3-12 End start-stop-status start ret=[127]
2021/03/23 10:38:47     (system) trigger deluge 2.0.3-12 Begin start-stop-status stop
deluge is not running
2021/03/23 10:38:47     (system) trigger deluge 2.0.3-12 End start-stop-status stop ret=[0]
```

**Comment by Epithumia** [comment]
Same issue and logs (only difference is the list of languages right before the exception) here on DS214se, MARVELL Armada 370, DSM 6.2.4-25556
