### ISSUE TITLE
Radarr internal update broken?

### ISSUE THREAD

**Issue by Epyon83** [SynoCommunity/spksrc#4536]
### Setup
_Package Name:_ Radarr
_Package Version:_ 20210311-15

_NAS Model:_ 916+
_NAS Architecture:_ x64?
_DSM version:_ DSM 6.2.4-25556

### Expected behavior
Radarr should apply update and restart

### Actual behavior
It says in the web GUI it applies the update and tries to restart, but doesnt update and doesnt restart

### Steps to reproduce
_1._ Install latest Synocommunity version v20210311-15
_2._ Use the internal update function of Radarr and try to update to the latest version (3.1.0.4832-31 Mar 2021 nightly)
_3._ Watch

#### Package log
_find logfiles in `/var/packages/{package}/var/`, for DSM7: `/var/log/packages/{package}.log`, for DSM < 6.0: protocol in Package Center.
_
```
Insert the package log here - follows later
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here - follows later
```

2021-4-1 08:26:25.6|Info|UpdateApp|Starting Radarr Update Client
2021-4-1 08:26:26.0|Debug|UpdateApp|NzbDrone process ID: 10125
2021-4-1 08:26:26.0|Debug|UpdateApp|Arguments:
2021-4-1 08:26:26.0|Debug|UpdateApp|  10125
2021-4-1 08:26:26.0|Debug|UpdateApp|  /tmp/radarr_update
2021-4-1 08:26:26.0|Debug|UpdateApp|  /volume1/@appstore/radarr/share/Radarr/bin/Radarr
2021-4-1 08:26:26.0|Debug|UpdateApp|Using executing application: /volume1/@appstore/radarr/share/Radarr/bin/Radarr
2021-4-1 08:26:26.0|Debug|UpdateApp|Executable location: /volume1/@appstore/radarr/share/Radarr/bin/Radarr
2021-4-1 08:26:26.0|Info|InstallUpdateService|Installation Folder: /volume1/@appstore/radarr/share/Radarr/bin
2021-4-1 08:26:26.0|Info|InstallUpdateService|Updating Radarr from version (unknown) to version 3.1.0.4832
2021-4-1 08:26:26.1|Info|InstallUpdateService|Verifying requirements before update...
2021-4-1 08:26:26.1|Debug|ProcessProvider|Finding process with Id:10125
2021-4-1 08:26:26.1|Debug|ProcessProvider|Found process 10125:Radarr [/volume1/@appstore/radarr/share/Radarr/bin/Radarr]
2021-4-1 08:26:26.1|Info|InstallUpdateService|Verifying Update Folder
2021-4-1 08:26:26.2|Fatal|UpdateApp|An error has occurred while applying update package.

[v3.1.0.4832] System.UnauthorizedAccessException: Access to the path '/proc/8023/maps' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileStream.CheckFileCall(Int64 result, Boolean ignoreNotSupported)
   at System.IO.FileStream.ReadNative(Span`1 buffer)
   at System.IO.FileStream.ReadSpan(Span`1 destination)
   at System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadLine()
   at System.IO.ReadLinesIterator.MoveNext()
   at Interop.procfs.ParseMapsModulesCore(IEnumerable`1 lines)+MoveNext()
   at System.Diagnostics.ProcessManager.GetModules(Int32 processId)
   at System.Diagnostics.Process.get_Modules()
   at NzbDrone.Common.Processes.ProcessProvider.<>c__DisplayClass21_0.<GetProcessesByName>b__0(Process process) in D:\a\1\s\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 347
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Set`1.UnionWith(IEnumerable`1 other)
   at System.Linq.Enumerable.UnionIterator`1.FillSet()
   at System.Linq.Enumerable.UnionIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NzbDrone.Common.Processes.ProcessProvider.GetProcessesByName(String name)
   at NzbDrone.Common.Processes.ProcessProvider.FindProcessByName(String name) in D:\a\1\s\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 94
   at NzbDrone.Update.UpdateEngine.InstallUpdateService.Start(String installationFolder, Int32 processId) in D:\a\1\s\src\NzbDrone.Update\UpdateEngine\InstallUpdateService.cs:line 101
   at NzbDrone.Update.UpdateApp.Start(String[] args) in D:\a\1\s\src\NzbDrone.Update\UpdateApp.cs:line 54
   at NzbDrone.Update.UpdateApp.Main(String[] args) in D:\a\1\s\src\NzbDrone.Update\UpdateApp.cs:line 39

**Comment by publicarray** [comment]
Hi, yes your NAS running on x64 (braswell)

I was unable to reproduce your issue, but I've seen someone else have a problem with `/proc/8023/maps' is denied` at the time they were told to ignore the issue since radarr was still working. You may have better support at https://radarr.video/discord. I can't see anything on our end that could fix this.

**Comment by publicarray** [comment]
Does starting via the package center work?

https://user-images.githubusercontent.com/5497998/113303144-4f967980-92f0-11eb-937c-e31b3c1d40ec.mov

**Comment by publicarray** [comment]
Might be duplicate of #4487

**Comment by publicarray** [comment]
Found the issue I was referring to: #6068

**Comment by Epyon83** [comment]
Issue can be closed, I restarted the NAS twice and then the update worked. Sorry if I made you some extra work.
