### ISSUE TITLE
Radarr unable to update

### ISSUE THREAD

**Issue by gavster2002** [SynoCommunity/spksrc#4679]
### Setup
_Package Name:_ Radarr
_Package Version:_ 3.0.2.4552

_NAS Model:_ DS1512+
_NAS Architecture:_ INTEL Atom D2700
_DSM version:_ DSM 6.2.4-25556

### Expected behavior
Update processes

### Actual behavior
Update is failing with access denied to /proc/18428/maps access denied error when trying to update to version 3.2.2.5080

### Steps to reproduce
_1._ Click update / install now
_2._ 
_3._ 

#### Package log
2021-6-14 15:38:20.7|Info|InstallUpdateService|Deleting old update files
2021-6-14 15:38:20.9|Info|InstallUpdateService|Downloading update 3.2.2.5080
2021-6-14 15:38:25.3|Info|InstallUpdateService|Verifying update package
2021-6-14 15:38:26.7|Info|InstallUpdateService|Update package verified successfully
2021-6-14 15:38:26.7|Info|InstallUpdateService|Extracting Update package
2021-6-14 15:38:42.6|Info|InstallUpdateService|Update package extracted successfully
2021-6-14 15:38:42.6|Info|BackupService|Starting Backup
2021-6-14 15:38:42.9|Info|InstallUpdateService|Preparing client
2021-6-14 15:38:46.5|Info|InstallUpdateService|Starting update client /tmp/radarr_update/Radarr.Update
2021-6-14 15:38:46.5|Info|InstallUpdateService|Radarr will restart shortly.
2021-6-14 15:40:11.0|Info|LifecycleService|Shutdown requested.
2021-6-14 15:41:19.2|Info|Bootstrap|Starting Radarr - /volume1/@appstore/radarr/share/Radarr/bin/Radarr.dll - Version 3.0.2.4552
2021-6-14 15:41:22.7|Warn|SingleInstancePolicy|Failed to check for multiple instances of Radarr.

[v3.0.2.4552] System.UnauthorizedAccessException: Access to the path '/proc/18428/maps' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileStream.CheckFileCall(Int64 result, Boolean ignoreNotSupported)
   at System.IO.FileStream.ReadNative(Span`1 buffer)
   at System.IO.FileStream.ReadSpan(Span`1 destination)
   at System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadLine()
   at System.IO.ReadLinesIterator.MoveNext()
   at Interop.procfs.ParseMapsModulesCore(IEnumerable`1 lines)+MoveNext()
   at System.Diagnostics.ProcessManager.GetModules(Int32 processId)
   at System.Diagnostics.Process.get_Modules()
   at NzbDrone.Common.Processes.ProcessProvider.<>c__DisplayClass21_0.<GetProcessesByName>b__0(Process process) in D:\a\1\s\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 344
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Set`1.UnionWith(IEnumerable`1 other)
   at System.Linq.Enumerable.UnionIterator`1.FillSet()
   at System.Linq.Enumerable.UnionIterator`1.ToList()
   at NzbDrone.Common.Processes.ProcessProvider.GetProcessesByName(String name)
   at NzbDrone.Common.Processes.ProcessProvider.FindProcessByName(String name) in D:\a\1\s\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 91
   at Radarr.Host.SingleInstancePolicy.GetOtherNzbDroneProcessIds() in D:\a\1\s\src\NzbDrone.Host\SingleInstancePolicy.cs:line 68

2021-6-14 15:41:22.9|Info|Router|Application mode: Interactive
2021-6-14 15:41:24.0|Info|MigrationController|*** Migrating data source=/volume1/@appstore/radarr/var/.config/Radarr/radarr.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
2021-6-14 15:41:26.2|Info|MigrationController|*** Migrating data source=/volume1/@appstore/radarr/var/.config/Radarr/logs.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
2021-6-14 15:41:27.6|Info|WebHostController|Listening on the following URLs:
2021-6-14 15:41:27.6|Info|WebHostController|  http://*:8310
2021-6-14 15:41:29.1|Info|RadarrBootstrapper|Starting Web Server
2021-6-14 15:41:35.8|Info|CommandExecutor|Starting 2 threads for tasks.

**Comment by yarez0** [comment]
same here, trying to upgrade from UI, logs said that all is ok and restart will be done but the package stopped, need to manually start it from package center and then the update did not completed. 

`2021-6-15 17:34:16.5|Info|InstallUpdateService|Downloading update 3.2.2.5080
2021-6-15 17:34:20.3|Info|InstallUpdateService|Verifying update package
2021-6-15 17:34:21.1|Info|InstallUpdateService|Update package verified successfully
2021-6-15 17:34:21.1|Info|InstallUpdateService|Extracting Update package
2021-6-15 17:34:29.3|Info|InstallUpdateService|Update package extracted successfully
2021-6-15 17:34:29.3|Info|BackupService|Starting Backup
2021-6-15 17:34:34.2|Info|InstallUpdateService|Preparing client
2021-6-15 17:34:38.8|Info|InstallUpdateService|Starting update client /tmp/radarr_update/Radarr.Update
2021-6-15 17:34:38.8|Info|InstallUpdateService|Radarr will restart shortly.
2021-6-15 17:35:19.8|Info|LifecycleService|Restart requested.
2021-6-15 17:39:02.8|Info|Bootstrap|Starting Radarr - /volume1/@appstore/radarr/share/Radarr/bin/Radarr.dll - Version 3.0.2.4552
2021-6-15 17:39:07.2|Warn|SingleInstancePolicy|Failed to check for multiple instances of Radarr.

[v3.0.2.4552] System.UnauthorizedAccessException: Access to the path '/proc/27086/maps' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileStream.CheckFileCall(Int64 result, Boolean ignoreNotSupported)
   at System.IO.FileStream.ReadNative(Span`1 buffer)
   at System.IO.FileStream.ReadSpan(Span`1 destination)
   at System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadLine()
   at System.IO.ReadLinesIterator.MoveNext()
   at Interop.procfs.ParseMapsModulesCore(IEnumerable`1 lines)+MoveNext()
   at System.Diagnostics.ProcessManager.GetModules(Int32 processId)
   at System.Diagnostics.Process.get_Modules()
   at NzbDrone.Common.Processes.ProcessProvider.<>c__DisplayClass21_0.<GetProcessesByName>b__0(Process process) in D:\a\1\s\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 344
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Set`1.UnionWith(IEnumerable`1 other)
   at System.Linq.Enumerable.UnionIterator`1.FillSet()
   at System.Linq.Enumerable.UnionIterator`1.ToList()
   at NzbDrone.Common.Processes.ProcessProvider.GetProcessesByName(String name)
   at NzbDrone.Common.Processes.ProcessProvider.FindProcessByName(String name) in D:\a\1\s\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 91
   at Radarr.Host.SingleInstancePolicy.GetOtherNzbDroneProcessIds() in D:\a\1\s\src\NzbDrone.Host\SingleInstancePolicy.cs:line 68


2021-6-15 17:39:07.5|Info|Router|Application mode: Interactive
2021-6-15 17:39:07.9|Info|MigrationController|*** Migrating data source=/volume1/@appstore/radarr/var/.config/Radarr/radarr.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
2021-6-15 17:39:10.0|Info|MigrationController|*** Migrating data source=/volume1/@appstore/radarr/var/.config/Radarr/logs.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
2021-6-15 17:39:13.1|Info|WebHostController|Listening on the following URLs:
2021-6-15 17:39:13.1|Info|WebHostController|  http://*:8310
2021-6-15 17:39:15.9|Info|RadarrBootstrapper|Starting Web Server
2021-6-15 17:39:35.3|Error|LocalizationService|Missing translation/culture resource: /volume1/@appstore/radarr/share/Radarr/bin/Localization/Core/fr_FR.json
2021-6-15 17:39:35.4|Info|CommandExecutor|Starting 2 threads for tasks.`

**Comment by markdopson** [comment]
I think it's a duplicate of #4621.
Note: I fixed it by stopping sonarr, updating radarr, then restarting sonarr.

**Comment by gavster2002** [comment]
Thanks, stopping sonarr then updating radarr resolved my issue.
