### ISSUE TITLE
SickChill NameError: name 'TVShow' is not defined

### ISSUE THREAD

**Issue by Dimas-sc** [SynoCommunity/spksrc#4703]
### Setup
_Package Name:_ SickChill
_Package Version:_ 20210329-1

_NAS Model:_ DS214
_NAS Architecture:_ 
_DSM version:_ 6.2.4-25556

### Expected behavior
Chickchill doesn't start

### Actual behavior
Chickchill doesn't start

### Steps to reproduce
_1._ Try to start/run

#### Log
Starting sickchill command /volume1/@appstore/sickchill/env/bin/python3 /volume1/@appstore/sickchill/share/SickChill/SickChill.py --daemon --nolaunch --pidfile /volume1/@appstore/sickchill/var/sickchill.pid --config /volume1/@appstore/sickchill/var/data/config.ini --datadir /volume1/@appstore/sickchill/var/data
/volume1/@appstore/sickchill/share/SickChill/sickchill/locale
/volume1/@appstore/sickchill/share/SickChill/sickchill/locale
Traceback (most recent call last):
  File "/volume1/@appstore/sickchill/share/SickChill/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/volume1/@appstore/sickchill/share/SickChill/sickchill/__init__.py", line 1, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/volume1/@appstore/sickchill/share/SickChill/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/volume1/@appstore/sickchill/share/SickChill/sickchill/show/indexers/handler.py", line 5, in <module>
    from sickchill.tv import Show, TVEpisode
  File "/volume1/@appstore/sickchill/share/SickChill/sickchill/tv.py", line 19, in <module>
    import sickchill.oldbeard.providers
  File "/volume1/@appstore/sickchill/share/SickChill/sickchill/oldbeard/providers/__init__.py", line 6, in <module>
    from sickchill.oldbeard.providers import (
  File "/volume1/@appstore/sickchill/share/SickChill/sickchill/oldbeard/providers/abnormal.py", line 8, in <module>
    from sickchill.oldbeard import tvcache
  File "/volume1/@appstore/sickchill/share/SickChill/sickchill/oldbeard/tvcache.py", line 10, in <module>
    from . import db, show_name_helpers
  File "/volume1/@appstore/sickchill/share/SickChill/sickchill/oldbeard/show_name_helpers.py", line 10, in <module>
    from .name_parser.parser import InvalidNameException, InvalidShowException, NameParser
  File "/volume1/@appstore/sickchill/share/SickChill/sickchill/oldbeard/name_parser/parser.py", line 23, in <module>
    class NameParser(object):
  File "/volume1/@appstore/sickchill/share/SickChill/sickchill/oldbeard/name_parser/parser.py", line 28, in NameParser
    def __init__(self, filename: bool = True, showObj: TVShow = None, tryIndexers: bool = False, naming_pattern: bool = False, parse_method: str = None):
NameError: name 'TVShow' is not defined

**Comment by BKSteve** [comment]
@Dimas-sc if you still have this error you should raise it in SickChill https://github.com/SickChill/SickChill/issues as it's not an install error related to the SynoCommunity spk package and not a DSM7 issue either as you're still on 6.2.4-25556

**Comment by Dimas-sc** [comment]
Done, thx (https://github.com/SickChill/SickChill/issues/7248)
