### ISSUE TITLE
Cannot update Radarr

### ISSUE THREAD

**Issue by fdfytr** [SynoCommunity/spksrc#4755]
### Setup
_Package Name:_ Radarr
_Package Version:_ 3.0.2.4552

_NAS Model:_ DS220j
_NAS Architecture:_ rtd1296 (armv8)
_DSM version:_ 6.2.4-25556

### Expected behavior
Trying to update to latest version

### Actual behavior
Error (see log details)

#### Package log
|Error|CommandExecutor|Error occurred while executing task ApplicationUpdate

[v3.0.2.4552] System.IO.IOException: No space left on device
at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.WriteSpan(ReadOnlySpan`1 source)
   at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
   at ICSharpCode.SharpZipLib.Tar.TarInputStream.CopyEntryContents(Stream outputStream)
   at ICSharpCode.SharpZipLib.Tar.TarArchive.ExtractEntry(String destDir, TarEntry entry)
   at ICSharpCode.SharpZipLib.Tar.TarArchive.ExtractContents(String destinationDirectory)
   at NzbDrone.Common.ArchiveService.ExtractTgz(String compressedFile, String destination) in D:\a\1\s\src\NzbDrone.Common\ArchiveService.cs:line 110
   at NzbDrone.Common.ArchiveService.Extract(String compressedFile, String destination) in D:\a\1\s\src\NzbDrone.Common\ArchiveService.cs:line 36
   at NzbDrone.Core.Update.InstallUpdateService.InstallUpdate(UpdatePackage updatePackage) in D:\a\1\s\src\NzbDrone.Core\Update\InstallUpdateService.cs:line 133
   at NzbDrone.Core.Update.InstallUpdateService.Execute(ApplicationUpdateCommand message) in D:\a\1\s\src\NzbDrone.Core\Update\InstallUpdateService.cs:line 275
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 118
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 44

--------

Sorry guys total newbie with NAS, looks as similar error to Jackett. Is it something about DS220j low specs?? I have plenty space left on HDD -1.6GB. Thank you

**Comment by publicarray** [comment]
What file system is your NAS formatted with? btrfs?

**Comment by fdfytr** [comment]
ext4

**Comment by publicarray** [comment]
Even with 1.6GB I still think low disk space is to blame. You don't need to get to 0GBs left to start seeing odd behaviour due to low free disk space. Modern OSs need space for swap, temp files, log files and when extracting files etc. During installation, it is not uncommon to have 3 copies of the files in various stages i.e 3 times the size, (the downloaded package file, extracted package file, and the old package) until the installation is completed/cleaned up.

**Comment by publicarray** [comment]
My recommendation is to install more disk space, e.g. add an external drive to move some stuff off the NAS until you extend the storage of the NAS itself.

**Comment by fdfytr** [comment]
I put OMV on pi 4 and run jackett sonarr via docker. Works like a charm.
Struggling with getting NFS to work from synology to pi now :)
I guess it is DS220j to blame...

**Comment by BenjV** [comment]
@fdfytr 
Maybe the space on the system volume is to low.
Log into the commandline and look with the df command to see it that is the case.

**Comment by hgy59** [comment]
#4621 might help.
1. stop sonarr to update radarr
2. define TMPDIR to point to a folder that is large enough

**Comment by fdfytr** [comment]
> @fdfytr
> Maybe the space on the system volume is to low.
> Log into the commandline and look with the df command to see it that is the case.

I ran sonarr via docker with OMV5 at pi4 and works smoothly
Now fighting to make radarr work via portainer :)
