### ISSUE TITLE
DSM 7 SABNZB errors

### ISSUE THREAD

**Issue by NKOS123** [SynoCommunity/spksrc#4987]
### Setup
_Package Name:_ SABNZBD
_Package Version:_ 3.4.2-50

_NAS Model:_ DS214Play
_NAS Architecture:_ Standard
_DSM version:_ 7.0.1-42218

### Expected behavior
SABNZBD operates as per normal (as prior to upgrade to DSM 7. Have tried reinstall, changing default directories with no effect.

### Actual behavior
Below errors received in SABNZBD:

Traceback (most recent call last):
  File "/volume1/@appstore/sabnzbd/env/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/volume1/@appstore/sabnzbd/env/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/volume1/@appstore/sabnzbd/env/lib/python3.8/site-packages/cherrypy/lib/encoding.py", line 223, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/volume1/@appstore/sabnzbd/env/lib/python3.8/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/interface.py", line 169, in internal_wrap
    return wrap_func(*args, **kwargs)
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/interface.py", line 452, in api
    return api_handler(kwargs)
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/api.py", line 100, in api_handler
    response = _api_table.get(mode, (_api_undefined, 2))[0](name, kwargs)
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/api.py", line 474, in _api_status
    return _api_status_table.get(name, (_api_fullstatus, 2))[0](value, kwargs)
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/api.py", line 465, in _api_fullstatus
    status = build_status(
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/api.py", line 1340, in build_status
    info["publicipv4"] = publicipv4()
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/getipaddress.py", line 87, in publicipv4
    result = addresslookup4(sabnzbd.cfg.selftest_host())
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/getipaddress.py", line 45, in func_wrapper
    return async_result.get(max_timeout)
  File "/var/packages/python38/target/lib/python3.8/multiprocessing/pool.py", line 736, in __exit__
    self.terminate()
  File "/var/packages/python38/target/lib/python3.8/multiprocessing/pool.py", line 654, in terminate
    self._terminate()
  File "/var/packages/python38/target/lib/python3.8/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/var/packages/python38/target/lib/python3.8/multiprocessing/pool.py", line 687, in _terminate_pool
    change_notifier.put(None)
  File "/var/packages/python38/target/lib/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/var/packages/python38/target/lib/python3.8/multiprocessing/synchronize.py", line 98, in __exit__
    return self._semlock.__exit__(*args)
ValueError: semaphore or lock released too many times

**Comment by hgy59** [comment]
@NKOS123 is this issue still open - or fixed with the current version of the sabnzbd  package?

**Comment by mreid-tt** [comment]
Hi @NKOS123, it looks like this issue has been open for some time without any recent updates. Since then, a new version of SABnzbd (v4.1.0-66) has been released which may have resolved this issue. Can you please test with the latest version and let us know if the issue persists? If we don't hear back from you in a few days, we'll assume the issue has been resolved and close this ticket. Thank you!
