### ISSUE TITLE
Unable to update Radarr on DS918+

### ISSUE THREAD

**Issue by Casuallynoted** [SynoCommunity/spksrc#5135]
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

Radarr

### Package Version

20210708-15

### Device Model

DS918+

### Device Architecture

x86_64

### Firmware Version

DSM 7.0.1-42218 update 2

### What happened?

Radarr reports as being version 3.0.2.4552. When I try to update or restart Radarr, it just stops running. Starting it manually does not run the update, so I'm unable to get myself to the latest version. I've been told by the Radarr devs there should be a newer version of the Synocommunity package, but I am not presented with one in Package Center.

### Reproduction steps

```bash
1. Install Radarr on fresh installed DS918+
2. Run, notice notification for update
3. Choose to update, Radarr extracts and then tries to restart, doesn't start/doesn't update
```

### Install Log

```log
2022/02/17 18:42:23	start radarr 20210708-15 Begin start-stop-status stop
2022/02/17 18:42:23	start radarr 20210708-15 End start-stop-status stop ret=[0]
2022/02/17 18:42:25	start radarr 20210708-15 Begin start-stop-status start
2022/02/17 18:42:30	start radarr 20210708-15 End start-stop-status start ret=[0]
2022/02/17 21:14:09	(system) trigger radarr 20210708-15 Begin start-stop-status start
2022/02/17 21:14:24	(system) trigger radarr 20210708-15 End start-stop-status start ret=[0]
2022/02/18 12:16:50	(system) trigger radarr 20210708-15 Begin start-stop-status stop
2022/02/18 12:16:53	(system) trigger radarr 20210708-15 End start-stop-status stop ret=[0]
2022/02/18 12:21:11	(system) trigger radarr 20210708-15 Begin start-stop-status start
2022/02/18 12:21:25	(system) trigger radarr 20210708-15 End start-stop-status start ret=[0]
```

**Comment by Casuallynoted** [comment]
Here's a section of the updater log that might be relevant:

2022-02-24 15:15:24.4|Fatal|UpdateApp|An error has occurred while applying update package.

[v4.0.5.5971] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Common.Processes.ProcessProvider.GetExeFileName(Process process) in D:\a\1\s\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 329
   at NzbDrone.Common.Processes.ProcessProvider.ConvertToProcessInfo(Process process) in D:\a\1\s\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 312
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NzbDrone.Common.Processes.ProcessProvider.FindProcessByName(String name) in D:\a\1\s\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 90
   at NzbDrone.Update.UpdateEngine.InstallUpdateService.Start(String installationFolder, Int32 processId) in D:\a\1\s\src\NzbDrone.Update\UpdateEngine\InstallUpdateService.cs:line 102
   at NzbDrone.Update.UpdateApp.Start(String[] args) in D:\a\1\s\src\NzbDrone.Update\UpdateApp.cs:line 59
   at NzbDrone.Update.UpdateApp.Main(String[] args) in D:\a\1\s\src\NzbDrone.Update\UpdateApp.cs:line 44

**Comment by bakerboy448** [comment]
Believe this is due to the `/tmp` dir issue that was resolved in https://github.com/SynoCommunity/spksrc/commit/5a174ae655388df9bbbf6d9bb19a8f16662a9fcb

Why that package (2021 October)  is not available to your NAS is something SynoCommunity will need to investigate.

Also the provided tiny radarr logs are not helpful.  The trace log loading the updater and then the update log are what is needed

**Comment by Stanzilla** [comment]
@hgy59 I just ran into this as well and the package is also not available via the website which is weird

**Comment by hgy59** [comment]
Radar 20220513-17 is just published (available in package center within about 48h) that installs well on my DS218+ with DSM 7.0.1-42218 Update 3.
