### ISSUE TITLE
sabnzbd: cannot find 'cpumodel'

### ISSUE THREAD

**Issue by MagicOneFr** [SynoCommunity/spksrc#5328]
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

sabnzbd

### Package Version

3.6.0-56

### Device Model

DS412+

### Device Architecture

x86_64

### Firmware Version

DSM 6.2.4-25556 Update 6

### What happened?

After the update to the latest version I can't access to the interface webpage.
It gives this error:

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/volume1/@appstore/sabnzbd/env/lib/python3.10/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/volume1/@appstore/sabnzbd/env/lib/python3.10/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/volume1/@appstore/sabnzbd/env/lib/python3.10/site-packages/cherrypy/lib/encoding.py", line 223, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/volume1/@appstore/sabnzbd/env/lib/python3.10/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/interface.py", line 171, in internal_wrap
    if check_api_key:
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/interface.py", line 442, in index
    info["have_logout"] = (
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/interface.py", line 375, in template_filtered_response
    return None
  File "cheetah__volume1__appstore_sabnzbd_share_SABnzbd_interfaces_Glitter_templates_main_tmpl_1656260413_954244_10630.py", line 543, in respond
  File "/volume1/@appstore/sabnzbd/env/lib/python3.10/site-packages/Cheetah/Template.py", line 1708, in _handleCheetahInclude
    self._CHEETAH__cheetahIncludes[_includeID].respond(trans)
  File "cheetah__volume1__appstore_sabnzbd_share_SABnzbd_interfaces_Glitter_templates_include_overlays_tmpl_1656260417_947812_91747.py", line 337, in respond
NameMapper.NotFound: cannot find 'cpumodel'

Everything was ok with the previous version.

### Reproduction steps

```bash
1. Launch a web browser with the address of my NAS and port 8080
2.
3.
...
```

### Install Log

```log
Sun Mar 28 16:48:40 CEST 2021
===> Step preupgrade. USER=sabnzbd GROUP=sc-download SHARE_PATH=/volume1/downloads
Sun Mar 28 16:48:40 CEST 2021
===> Step preuninst. USER=sabnzbd GROUP=sc-download SHARE_PATH=/volume1/downloads
Sun Mar 28 16:48:46 CEST 2021
===> Step postuninst. USER=sabnzbd GROUP=sc-download SHARE_PATH=/volume1/downloads
Sun Mar 28 16:48:47 CEST 2021
===> Step preinst. USER=sabnzbd GROUP=sc-download SHARE_PATH=
Sun Mar 28 16:48:49 CEST 2021
===> Step postinst. USER=sabnzbd GROUP=sc-download SHARE_PATH=/volume1/downloads
Installing service configuration /var/packages/sabnzbd/conf/sabnzbd.sc
Configuring /volume1/downloads
Invoke service_postinst
created virtual environment CPython3.8.8.final.0-64 in 5766ms
  creator CPython3Posix(dest=/volume1/@appstore/sabnzbd/env, clear=False, global=True)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/root/.local/share/virtualenv/seed-v1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
Looking in links: /volume1/@appstore/sabnzbd/share/wheelhouse
Processing /volume1/@appstore/sabnzbd/share/wheelhouse/Cheetah3-3.2.6-cp38-none-any.whl
Processing /volume1/@appstore/sabnzbd/share/wheelhouse/CherryPy-18.6.0-py2.py3-none-any.whl
Processing /volume1/@appstore/sabnzbd/share/wheelhouse/chardet-4.0.0-py2.py3-none-any.whl
Processing /volume1/@appstore/sabnzbd/share/wheelhouse/cheroot-8.5.2-py2.py3-none-any.whl
Processing /volume1/@appstore/sabnzbd/share/wheelhouse/configobj-5.0.6-py3-none-any.whl
Processing /volume1/@appstore/sabnzbd/share/wheelhouse/feedparser-6.0.2-py3-none-any.whl
Processing /volume1/@appstore/sabnzbd/share/wheelhouse/jaraco.classes-3.2.1-py3-none-any.whl
Processing /volume1/@appstore/sabnzbd/share/wheelhouse/jaraco.collections-3.2.0-py3-none-any.whl
Processing /volume1/@appstore/sabnzbd/share/wheelhouse/jaraco.functools-3.2.1-py3-none-any.whl
Processing /volume1/@appstore/sabnzbd/share/wheelhouse/jaraco.text-3.5.0-py3-none-any.whl
Processing /volume1/@appstore/sabnzbd/share/wheelhouse/more_itertools-8.7.0-py3-none-any.whl
Processing /volume1/@appstore/sabnzbd/share/wheelhouse/portend-2.7.1-py3-none-any.whl
Processing /volume1/@appstore/sabnzbd/share/wheelhouse/pytz-2021.1-py3-none-any.whl
Processing /volume1/@appstore/sabnzbd/share/wheelhouse/sabyenc3-4.0.2-cp38-none-any.whl
Processing /volume1/@appstore/sabnzbd/share/wheelhouse/sgmllib3k-1.0.0-py3-none-any.whl
Processing /volume1/@appstore/sabnzbd/share/wheelhouse/tempora-4.0.1-py3-none-any.whl
Processing /volume1/@appstore/sabnzbd/share/wheelhouse/zc.lockfile-2.0-py2.py3-none-any.whl
Installing collected packages: Cheetah3, CherryPy, chardet, cheroot, configobj, feedparser, jaraco.classes, jaraco.collections, jaraco.functools, jaraco.text, more-itertools, portend, pytz, sabyenc3, sgmllib3k, tempora, zc.lockfile
Successfully installed Cheetah3-3.2.6 CherryPy-18.6.0 chardet-4.0.0 cheroot-8.5.2 configobj-5.0.6 feedparser-6.0.2 jaraco.classes-3.2.1 jaraco.collections-3.2.0 jaraco.functools-3.2.1 jaraco.text-3.5.0 more-itertools-8.7.0 portend-2.7.1 pytz-2021.1 sabyenc3-4.0.2 sgmllib3k-1.0.0 tempora-4.0.1 zc.lockfile-2.0
mkdir: cannot create directory '/volume1/@appstore/sabnzbd/var': File exists
Granting 'sc-sabnzbd' unix ownership on /volume1/@appstore/sabnzbd/var
Sun Mar 28 16:49:28 CEST 2021
===> Step postupgrade. USER=sabnzbd GROUP=sc-download SHARE_PATH=/volume1/downloads
Granting 'sc-sabnzbd' unix ownership on /volume1/@appstore/sabnzbd/var
Invoke service_postupgrade
Granting 'sc-sabnzbd' unix ownership on /volume1/downloads/incomplete
ACL version: 1 
Archive: has_ACL,is_support_ACL 
Owner: [sc-sabnzbd(user)] 
--------------------- 
	 [0] group:administrators:allow:rwxpdDaARWc--:fd--  (level:0)
Granting 'sc-download' group permissions on /volume1/downloads/incomplete
ACL version: 1 
Archive: has_ACL,is_support_ACL 
Owner: [sc-sabnzbd(user)] 
--------------------- 
	 [0] group:administrators:allow:rwxpdDaARWc--:fd--  (level:0)
	 [1] group:sc-download:allow:rwxpdDaARWcC-:fd--  (level:0)
```

### Service Log

```log
Sun Jun 26 10:03:54 CEST 2022
Starting sabnzbd command env LANG=en_US.UTF-8 /volume1/@appstore/sabnzbd/env/bin/python3 -OO /volume1/@appstore/sabnzbd/share/SABnzbd/SABnzbd.py -f /volume1/@appstore/sabnzbd/var/config.ini --pidfile /volume1/@appstore/sabnzbd/var/sabnzbd.pid -d 
sabnzbd is not running
sabnzbd is already running
```

**Comment by hgy59** [comment]
@MagicOneFr is this issue still open?

**Comment by MagicOneFr** [comment]
> @MagicOneFr is this issue still open?

Hello. I don't know. Since this error, I'm using nzbget.

**Comment by mreid-tt** [comment]
Closing stale issue as it cannot be reproduced.
