### ISSUE TITLE
jackett can not start with dsm 7.2 beta (DSM 7.2-64216)

### ISSUE THREAD

**Issue by lazeyliu** [SynoCommunity/spksrc#5688]
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

jackett

### Package Version

 0.20.1171-15

### Device Model

DS220+

### Device Architecture

x86_64

### Firmware Version

7.2-64216

### What happened?

```
Sun Apr  9 10:35:02 CST 2023
Starting jackett command env HOME=/volume1/@appdata/jackett PATH=/volume1/@appstore/jackett/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin LD_LIBRARY_PATH=/volume1/@appstore/jackett/lib /volume1/@appstore/jackett/share/jackett --PIDFile /volume1/@appdata/jackett/jackett.pid
Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode+Settings..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.get_InvariantCulture()
   at CommandLine.ParserSettings..ctor()
   at CommandLine.Parser..ctor(System.Action`1<CommandLine.ParserSettings>)
   at Jackett.Server.Program.Main(System.String[])
jackett is not running
```

### Reproduction steps

```bash
1. install 
2. start
```

### Install Log

```log
2023/04/09 10:34:58	install jackett 0.20.1171-15 Begin preinst
2023/04/09 10:34:58	Begin reload_inst_variables
2023/04/09 10:34:58	End reload_inst_variables
2023/04/09 10:34:58	Begin initialize_variables
2023/04/09 10:34:58	End initialize_variables
2023/04/09 10:34:58	===> Step preinst. USER=sc-jackett GROUP= SHARE_PATH=
2023/04/09 10:34:58	install jackett 0.20.1171-15 End preinst ret=[0]
2023/04/09 10:34:59	install jackett 0.20.1171-15 Begin /bin/mkdir -p /volume1/@appstore/jackett -m 755
2023/04/09 10:34:59	install jackett 0.20.1171-15 End /bin/mkdir -p /volume1/@appstore/jackett -m 755 ret=[0]
2023/04/09 10:34:59	install jackett 0.20.1171-15 Begin /bin/rm -rf /volume1/@appstore/jackett
2023/04/09 10:34:59	install jackett 0.20.1171-15 End /bin/rm -rf /volume1/@appstore/jackett ret=[0]
2023/04/09 10:34:59	install jackett 0.20.1171-15 Begin /bin/mv -f /volume1/@tmp/synopkg/install.pLWtjP/package /volume1/@appstore/jackett
2023/04/09 10:34:59	install jackett 0.20.1171-15 End /bin/mv -f /volume1/@tmp/synopkg/install.pLWtjP/package /volume1/@appstore/jackett ret=[0]
2023/04/09 10:34:59	install jackett 0.20.1171-15 Begin /bin/rm -rf /var/packages/jackett
2023/04/09 10:34:59	install jackett 0.20.1171-15 End /bin/rm -rf /var/packages/jackett ret=[0]
2023/04/09 10:34:59	install jackett 0.20.1171-15 Begin /bin/mkdir -p /var/packages/jackett -m 755
2023/04/09 10:34:59	install jackett 0.20.1171-15 End /bin/mkdir -p /var/packages/jackett -m 755 ret=[0]
2023/04/09 10:34:59	install jackett 0.20.1171-15 Begin /bin/touch /var/packages/jackett/installing
2023/04/09 10:34:59	install jackett 0.20.1171-15 End /bin/touch /var/packages/jackett/installing ret=[0]
2023/04/09 10:34:59	install jackett 0.20.1171-15 Begin /bin/mv -f /volume1/@tmp/synopkg/install.pLWtjP/INFO /var/packages/jackett/INFO
2023/04/09 10:34:59	install jackett 0.20.1171-15 End /bin/mv -f /volume1/@tmp/synopkg/install.pLWtjP/INFO /var/packages/jackett/INFO ret=[0]
2023/04/09 10:34:59	install jackett 0.20.1171-15 Begin /bin/rm -rf /var/packages/jackett/scripts
2023/04/09 10:34:59	install jackett 0.20.1171-15 End /bin/rm -rf /var/packages/jackett/scripts ret=[0]
2023/04/09 10:34:59	install jackett 0.20.1171-15 Begin /bin/mv -f /volume1/@tmp/synopkg/install.pLWtjP/scripts /var/packages/jackett/scripts
2023/04/09 10:34:59	install jackett 0.20.1171-15 End /bin/mv -f /volume1/@tmp/synopkg/install.pLWtjP/scripts /var/packages/jackett/scripts ret=[0]
2023/04/09 10:34:59	install jackett 0.20.1171-15 Begin /bin/rm -rf /var/packages/jackett/WIZARD_UIFILES
2023/04/09 10:34:59	install jackett 0.20.1171-15 End /bin/rm -rf /var/packages/jackett/WIZARD_UIFILES ret=[0]
2023/04/09 10:34:59	install jackett 0.20.1171-15 Begin /bin/mv -f /volume1/@tmp/synopkg/install.pLWtjP/WIZARD_UIFILES /var/packages/jackett/WIZARD_UIFILES
2023/04/09 10:34:59	install jackett 0.20.1171-15 End /bin/mv -f /volume1/@tmp/synopkg/install.pLWtjP/WIZARD_UIFILES /var/packages/jackett/WIZARD_UIFILES ret=[0]
2023/04/09 10:34:59	install jackett 0.20.1171-15 Begin /bin/rm -rf /var/packages/jackett/conf
2023/04/09 10:34:59	install jackett 0.20.1171-15 End /bin/rm -rf /var/packages/jackett/conf ret=[0]
2023/04/09 10:34:59	install jackett 0.20.1171-15 Begin /bin/mv -f /volume1/@tmp/synopkg/install.pLWtjP/conf /var/packages/jackett/conf
2023/04/09 10:34:59	install jackett 0.20.1171-15 End /bin/mv -f /volume1/@tmp/synopkg/install.pLWtjP/conf /var/packages/jackett/conf ret=[0]
2023/04/09 10:35:01	install jackett 0.20.1171-15 Begin postinst
2023/04/09 10:35:01	Begin reload_inst_variables
2023/04/09 10:35:01	End reload_inst_variables
2023/04/09 10:35:01	Begin initialize_variables
2023/04/09 10:35:01	End initialize_variables
2023/04/09 10:35:01	===> Step postinst. USER=sc-jackett GROUP= SHARE_PATH=
2023/04/09 10:35:01	Begin save_wizard_variables
2023/04/09 10:35:01	End save_wizard_variables
2023/04/09 10:35:01	Begin syno_sync_var_folder
2023/04/09 10:35:01	Install files from var folder
2023/04/09 10:35:01	/bin/rsync -avh --ignore-existing --remove-source-files /volume1/@appstore/jackett/var/ /volume1/@appdata/jackett
2023/04/09 10:35:01	sending incremental file list
2023/04/09 10:35:01	./
2023/04/09 10:35:01	.config/
2023/04/09 10:35:01	.config/Jackett/
2023/04/09 10:35:01	sent 119 bytes  received 27 bytes  292.00 bytes/sec
2023/04/09 10:35:01	total size is 0  speedup is 0.00
2023/04/09 10:35:01	/bin/rsync -avh --remove-source-files /volume1/@appstore/jackett/var/ /volume1/@appdata/jackett
2023/04/09 10:35:01	sending incremental file list
2023/04/09 10:35:01	sent 106 bytes  received 14 bytes  240.00 bytes/sec
2023/04/09 10:35:01	total size is 0  speedup is 0.00
2023/04/09 10:35:01	End syno_sync_var_folder
2023/04/09 10:35:01	install jackett 0.20.1171-15 End postinst ret=[0]
2023/04/09 10:35:02	install jackett 0.20.1171-15 Begin start-stop-status start
/var/packages/jackett/scripts/start-stop-status: line 115: 27597 Aborted                 (core dumped) ${SERVICE_COMMAND} >> ${OUT} 2>&1
2023/04/09 10:35:22	install jackett 0.20.1171-15 End start-stop-status start ret=[1]
2023/04/09 10:35:22	(system) trigger jackett 0.20.1171-15 Begin start-stop-status stop
2023/04/09 10:35:22	(system) trigger jackett 0.20.1171-15 End start-stop-status stop ret=[0]
```

### Service Log
```
Sun Apr  9 10:35:02 CST 2023
Starting jackett command env HOME=/volume1/@appdata/jackett PATH=/volume1/@appstore/jackett/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin LD_LIBRARY_PATH=/volume1/@appstore/jackett/lib /volume1/@appstore/jackett/share/jackett --PIDFile /volume1/@appdata/jackett/jackett.pid
Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode+Settings..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.get_InvariantCulture()
   at CommandLine.ParserSettings..ctor()
   at CommandLine.Parser..ctor(System.Action`1<CommandLine.ParserSettings>)
   at Jackett.Server.Program.Main(System.String[])
jackett is not running
```

_No response_

### Other Logs
```
2023-04-09T10:35:02+08:00 user coredump[27608]: Process jackett[27597](/volume1/@appstore/jackett/share/jackett) dumped core on signal [6]. Core file [/volume1/@jackett.synology_geminilake_220+.64216.core.gz]. Cmdline [/volume1/@appstore/jackett/share/jackett --PIDFile /volume1/@appdata/jackett/jackett.pid ]
2023-04-09T10:35:02+08:00 user coredump[27608]: Core file [/volume1/@jackett.synology_geminilake_220+.64216.core.gz] size [2782707]
```

```
2023/04/09 10:34:58 install jackett 0.20.1171-15 Begin preinst
2023/04/09 10:34:58 install jackett 0.20.1171-15 End preinst ret=[0]
2023/04/09 10:34:59 install jackett 0.20.1171-15 Begin /bin/mkdir -p /volume1/@appstore/jackett -m 755
2023/04/09 10:34:59 install jackett 0.20.1171-15 End /bin/mkdir -p /volume1/@appstore/jackett -m 755 ret=[0]
2023/04/09 10:34:59 install jackett 0.20.1171-15 Begin /bin/rm -rf /volume1/@appstore/jackett
2023/04/09 10:34:59 install jackett 0.20.1171-15 End /bin/rm -rf /volume1/@appstore/jackett ret=[0]
2023/04/09 10:34:59 install jackett 0.20.1171-15 Begin /bin/mv -f /volume1/@tmp/synopkg/install.pLWtjP/package /volume1/@appstore/jackett
2023/04/09 10:34:59 install jackett 0.20.1171-15 End /bin/mv -f /volume1/@tmp/synopkg/install.pLWtjP/package /volume1/@appstore/jackett ret=[0]
2023/04/09 10:34:59 install jackett 0.20.1171-15 Begin /bin/rm -rf /var/packages/jackett
2023/04/09 10:34:59 install jackett 0.20.1171-15 End /bin/rm -rf /var/packages/jackett ret=[0]
2023/04/09 10:34:59 install jackett 0.20.1171-15 Begin /bin/mkdir -p /var/packages/jackett -m 755
2023/04/09 10:34:59 install jackett 0.20.1171-15 End /bin/mkdir -p /var/packages/jackett -m 755 ret=[0]
2023/04/09 10:34:59 install jackett 0.20.1171-15 Begin /bin/touch /var/packages/jackett/installing
2023/04/09 10:34:59 install jackett 0.20.1171-15 End /bin/touch /var/packages/jackett/installing ret=[0]
2023/04/09 10:34:59 install jackett 0.20.1171-15 Begin /bin/mv -f /volume1/@tmp/synopkg/install.pLWtjP/INFO /var/packages/jackett/INFO
2023/04/09 10:34:59 install jackett 0.20.1171-15 End /bin/mv -f /volume1/@tmp/synopkg/install.pLWtjP/INFO /var/packages/jackett/INFO ret=[0]
2023/04/09 10:34:59 install jackett 0.20.1171-15 Begin /bin/rm -rf /var/packages/jackett/scripts
2023/04/09 10:34:59 install jackett 0.20.1171-15 End /bin/rm -rf /var/packages/jackett/scripts ret=[0]
2023/04/09 10:34:59 install jackett 0.20.1171-15 Begin /bin/mv -f /volume1/@tmp/synopkg/install.pLWtjP/scripts /var/packages/jackett/scripts
2023/04/09 10:34:59 install jackett 0.20.1171-15 End /bin/mv -f /volume1/@tmp/synopkg/install.pLWtjP/scripts /var/packages/jackett/scripts ret=[0]
2023/04/09 10:34:59 install jackett 0.20.1171-15 Begin /bin/rm -rf /var/packages/jackett/WIZARD_UIFILES
2023/04/09 10:34:59 install jackett 0.20.1171-15 End /bin/rm -rf /var/packages/jackett/WIZARD_UIFILES ret=[0]
2023/04/09 10:34:59 install jackett 0.20.1171-15 Begin /bin/mv -f /volume1/@tmp/synopkg/install.pLWtjP/WIZARD_UIFILES /var/packages/jackett/WIZARD_UIFILES
2023/04/09 10:34:59 install jackett 0.20.1171-15 End /bin/mv -f /volume1/@tmp/synopkg/install.pLWtjP/WIZARD_UIFILES /var/packages/jackett/WIZARD_UIFILES ret=[0]
2023/04/09 10:34:59 install jackett 0.20.1171-15 Begin /bin/rm -rf /var/packages/jackett/conf
2023/04/09 10:34:59 install jackett 0.20.1171-15 End /bin/rm -rf /var/packages/jackett/conf ret=[0]
2023/04/09 10:34:59 install jackett 0.20.1171-15 Begin /bin/mv -f /volume1/@tmp/synopkg/install.pLWtjP/conf /var/packages/jackett/conf
2023/04/09 10:34:59 install jackett 0.20.1171-15 End /bin/mv -f /volume1/@tmp/synopkg/install.pLWtjP/conf /var/packages/jackett/conf ret=[0]
2023/04/09 10:35:00 Acquire systemd-unit for jackett when 0x0001 (ready)
2023/04/09 10:35:00 Acquire systemd-unit for jackett when 0x0001 (done)
2023/04/09 10:35:00 Acquire port-config for jackett when 0x0001 (ready)
2023/04/09 10:35:00 Acquire port-config for jackett when 0x0001 (done)
2023/04/09 10:35:01 install jackett 0.20.1171-15 Begin postinst
2023/04/09 10:35:01 install jackett 0.20.1171-15 End postinst ret=[0]
2023/04/09 10:35:01 install jackett: begin to start version 0.20.1171-15
2023/04/09 10:35:01 Acquire port-config for jackett when 0x0001 (ready)
2023/04/09 10:35:01 Acquire port-config for jackett when 0x0001 (done)
2023/04/09 10:35:02 install jackett 0.20.1171-15 Begin start-stop-status start
2023/04/09 10:35:22 install jackett 0.20.1171-15 End start-stop-status start ret=[1]
2023/04/09 10:35:22 Release port-config for jackett when 0x0001 (ready)
2023/04/09 10:35:22 Release port-config for jackett when 0x0001 (done)
2023/04/09 10:35:22 install jackett: start version 0.20.1171-15 failed, result 0
2023/04/09 10:35:22 install jackett 0.20.1171-15 successfully
2023/04/09 10:35:22 (system) trigger jackett 0.20.1171-15 Begin start-stop-status stop
2023/04/09 10:35:22 (system) trigger jackett 0.20.1171-15 End start-stop-status stop ret=[0]
2023/04/09 10:35:22 Release port-config for jackett when 0x0000 (ready)
2023/04/09 10:35:22 Release port-config for jackett when 0x0000 (done)
2023/04/09 10:35:22 enabled flag does not exist, skip apparmor unloading
```

_No response_

**Comment by snakefoot** [comment]
Maybe set `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1`

**Comment by mreid-tt** [comment]
hey @lazeyliu, thanks for the report. The package has not been tested in DSM 7.2 but if you are willing to assist. you can try the following:

1. Connect to your NAS via SSH
2. Enter the following commands (this will backup the setup script and modify the env variables):
```
cd /var/packages/jackett/scripts
sudo rsync -aX service-setup service-setup.bak
sudo sed -i 's|SERVICE_COMMAND="env HOME=${HOME_DIR} PATH=${PATH} LD_LIBRARY_PATH=${SYNOPKG_PKGDEST}/lib ${JACKETT} --PIDFile ${PID_FILE}"|SERVICE_COMMAND="env HOME=${HOME_DIR} DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1 PATH=${PATH} LD_LIBRARY_PATH=${SYNOPKG_PKGDEST}/lib ${JACKETT} --PIDFile ${PID_FILE}"||g' service-setup
```

Let me know if you are able to start the package with that change.

**Comment by Kickunio** [comment]
@mreid-tt I check Jackett (I wanted to try this app) - It worked butr you have to do something also if you have repair option available in DSM.
You need to start the package from SSH (sudo synopkg start jackett) clicking repair won't work.

**Comment by mreid-tt** [comment]
@Kickunio, thanks for the feedback. I've attempted to create a new build which includes the `libicu`. Once it is finished building you can uninstall the currently installed version and install the one for your architecture from the build run at https://github.com/SynoCommunity/spksrc/actions/runs/4676999391.

**Comment by Kickunio** [comment]
@mreid-tt I can say that you're my hero, god, messiah (choose whichever you want ;) ) - the package from the link you provided works flawlessly :)

**Comment by mreid-tt** [comment]
hey @Kickunio, thanks for confirming that the solution worked for you. I'll have some discussions with the senior devs to see if this would be a preferred solution for the ***arr** packages. These also rely on dotnet 6.x so should have similar issues in DSM 7.2 beta.

**Comment by lazeyliu** [comment]
> hey @lazeyliu, thanks for the report. The package has not been tested in DSM 7.2 but if you are willing to assist. you can try the following (as also suggested by @snakefoot):
> 
> 1. Connect to your NAS via SSH
> 2. Enter the following commands (this will backup the setup script and modify the env variables):
> 
> ```
> cd /var/packages/jackett/scripts
> sudo rsync -aX service-setup service-setup.bak
> sudo sed -i 's|SERVICE_COMMAND="env HOME=${HOME_DIR} PATH=${PATH} LD_LIBRARY_PATH=${SYNOPKG_PKGDEST}/lib ${JACKETT} --PIDFile ${PID_FILE}"|SERVICE_COMMAND="env HOME=${HOME_DIR} DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1 PATH=${PATH} LD_LIBRARY_PATH=${SYNOPKG_PKGDEST}/lib ${JACKETT} --PIDFile ${PID_FILE}"|g' service-setup
> ```
> 
> Let me know if you are able to start the package with that change.

Thanks , unfortunately the device is not with me . I can only test it during the holiday on May 1st

**Comment by mreid-tt** [comment]
> Thanks , unfortunately the device is not with me . I can only test it during the holiday on May 1st

Thanks for the update. Looking forward to your feedback. You can also test with a different solution based on a modified build (see below)...

> I've attempted to create a new build which includes the `libicu`. Once it is finished building you can uninstall the currently installed version and install the one for your architecture from the build run at https://github.com/SynoCommunity/spksrc/actions/runs/4685386376.

**Comment by lazeyliu** [comment]
> > Thanks , unfortunately the device is not with me . I can only test it during the holiday on May 1st
> 
> Thanks for the update. Looking forward to your feedback. You can also test with a different solution based on a modified build (see below)...
> 
> > I've attempted to create a new build which includes the `libicu`. Once it is finished building you can uninstall the currently installed version and install the one for your architecture from the build run at https://github.com/SynoCommunity/spksrc/actions/runs/4685386376.

thanks a lot .  I have tested  and  it works now

I am using the build run at  https://github.com/SynoCommunity/spksrc/actions/runs/4690925812
