### ISSUE TITLE
Sonarr V4 installs but can't start on DSM 7.2

### ISSUE THREAD

**Issue by Kickunio** [SynoCommunity/spksrc#5692]
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

sonarr v4

### Package Version

20230404-1

### Device Model

DS920+

### Device Architecture

x86_64

### Firmware Version

DSM 7.2-64216

### What happened?

Sonarr v4 package looks like installed correctly but can't start and shows only repair option or uninstall (sometimes it doesn't show repair and only uninstall)

### Reproduction steps

```bash
1. Install Sonarr v4
```

### Install Log

```log
2023/04/11 18:58:59 Begin load_variables_from_file
2023/04/11 18:58:59 End load_variables_from_file
2023/04/11 18:58:59 Begin initialize_variables
2023/04/11 18:58:59 End initialize_variables
2023/04/11 18:58:59 ===> Step postinst. STATUS=INSTALL USER=sc-sonarr GROUP= SHARE_PATH=
2023/04/11 18:58:59 Begin save_wizard_variables
2023/04/11 18:58:59 End save_wizard_variables
2023/04/11 18:58:59 Begin syno_sync_var_folder
2023/04/11 18:58:59 Install files from var folder
2023/04/11 18:58:59 /bin/rsync -avh --ignore-existing --remove-source-files /volume1/@appstore/sonarr/var/ /volume1/@appdata/sonarr
2023/04/11 18:58:59 sending incremental file list
2023/04/11 18:58:59 .config/Sonarr/
2023/04/11 18:58:59 sent 128 bytes  received 17 bytes  290.00 bytes/sec
2023/04/11 18:58:59 total size is 200  speedup is 1.38
2023/04/11 18:58:59 /bin/rsync -avh --remove-source-files /volume1/@appstore/sonarr/var/ /volume1/@appdata/sonarr
2023/04/11 18:58:59 sending incremental file list
2023/04/11 18:58:59 .config/Sonarr/
2023/04/11 18:58:59 sent 146 bytes  received 25 bytes  342.00 bytes/sec
2023/04/11 18:58:59 total size is 200  speedup is 1.17
2023/04/11 18:58:59 End syno_sync_var_folder
2023/04/11 18:58:59 Begin service_postinst
2023/04/11 18:58:59 Set update required
2023/04/11 18:58:59 End service_postinst
2023/04/11 18:58:59 install sonarr 20230404-1 End postinst ret=[0]
2023/04/11 18:58:59 install sonarr 20230404-1 Begin start-stop-status start
/var/packages/sonarr/scripts/start-stop-status: line 151: 32552 Aborted                 (core dumped) ${service} >> ${OUT} 2>&1
2023/04/11 19:00:30 install sonarr 20230404-1 End start-stop-status start ret=[1]
2023/04/11 19:00:30 (system) trigger sonarr 20230404-1 Begin start-stop-status stop
2023/04/11 19:00:30 (system) trigger sonarr 20230404-1 End start-stop-status stop ret=[0]
```

### Service Log

```log
Starting sonarr command env HOME=/volume1/@appdata/sonarr LD_LIBRARY_PATH=/volume1/@appstore/sonarr/lib /volume1/@appstore/sonarr/share/Sonarr/bin/Sonarr -nobrowser -data=/volume1/@appdata/sonarr/.config/Sonarr
Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode+Settings..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.get_CurrentCulture()
   at System.Text.RegularExpressions.Regex.Init(System.String, System.Text.RegularExpressions.RegexOptions, System.TimeSpan, System.Globalization.CultureInfo)
   at System.Text.RegularExpressions.Regex..ctor(System.String, System.Text.RegularExpressions.RegexOptions, System.TimeSpan, System.Globalization.CultureInfo)
   at System.Text.RegularExpressions.Regex..ctor(System.String, System.Text.RegularExpressions.RegexOptions)
   at NzbDrone.RuntimePatches.MonoRuntimePatchBase..cctor()
   at NzbDrone.RuntimePatches.MonoRuntimePatchBase..ctor()
   at NzbDrone.RuntimePatches.Mono.BoringTLSVerifyFlagsPatch..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean, Boolean)
   at System.Activator.CreateInstance(System.Type, Boolean, Boolean)
   at System.Activator.CreateInstance(System.Type)
   at System.Linq.Enumerable+WhereSelectArrayIterator`2[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Linq.Enumerable+<CastIterator>d__63`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Linq.Enumerable+WhereEnumerableIterator`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ToList()
   at System.Linq.Enumerable.ToList[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at NzbDrone.RuntimePatches.RuntimePatcher.ApplyPatches()
   at NzbDrone.RuntimePatches.RuntimePatcher.Initialize()
   at NzbDrone.Console.ConsoleApp.Main(System.String[])
sonarr is not running
```

**Comment by mreid-tt** [comment]
hey @Kickunio, thanks for the report. The package has not been tested in DSM 7.2 but if you are willing to assist. you can try the following:

1. Connect to your NAS via SSH
2. Enter the following commands (this will backup the setup script and modify the env variables):
```
cd /var/packages/sonarr/scripts
sudo rsync -aX service-setup service-setup.bak
sudo sed -i 's|SERVICE_COMMAND="env HOME=${HOME_DIR} LD_LIBRARY_PATH=${SYNOPKG_PKGDEST}/lib ${SONARR} ${CMD_ARGS}"|SERVICE_COMMAND="env HOME=${HOME_DIR} DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1 LD_LIBRARY_PATH=${SYNOPKG_PKGDEST}/lib ${SONARR} ${CMD_ARGS}"|g' service-setup
```

Let me know if you are able to start the package with that change.

**Comment by mreid-tt** [comment]
hey @Kickunio, thanks for the feedback. Yes, I've posted a modification of the commands which should work with Jackett. Let's see if it is also successful.

**Comment by mreid-tt** [comment]
hey @Kickunio, I've created a new build based on the learnings from Jackett. You can test using one of the packages here: https://github.com/SynoCommunity/spksrc/actions/runs/4707594191.

**Comment by Kickunio** [comment]
@mreid-tt Thanks, Will test it as fast as I can. Would it be possible to do the same for Radarr? There seems to be the same error as in other *arr apps

**Comment by mreid-tt** [comment]
@Kickunio, ideally the issue with Radarr should be under a separate issue number for tracking. I've started the build in the meantime and would be available under: https://github.com/SynoCommunity/spksrc/actions/runs/4707975836
