### ISSUE TITLE
FFmpeg 4: "Exited with code 1" on Jellyfin transcode

### ISSUE THREAD

**Issue by mreid-tt** [SynoCommunity/spksrc#5710]
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

ffmpeg 4.4.3

### Package Version

4.4.3-48

### Device Model

VirtualDSM (DS916+)

### Device Architecture

x86_64

### Firmware Version

6.2.4-25556 Update 6

### What happened?

With a fresh install of ffmpeg 4.4.3 and Jellyfin 10.8.10, on attempting to stream a video, I get the following error:

```
FFmpeg exited with code 1
```

### Reproduction steps

1. Install ffmpeg 4.4.3
2. Install Jellyfin 10.8.10
3. Login and setup media library
4. Play video in browser

### Install Log

```log
N/A
```

### Service Log

```log
Jellyfin service log:

[19:24:38] [ERR] [13] Jellyfin.Api.Helpers.TranscodingJobHelper: FFmpeg exited with code 1
[19:24:38] [ERR] [25] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL GET /videos/b2316185-4e85-b991-8357-548394a0935b/hls1/main/0.ts.
MediaBrowser.Common.FfmpegException: FFmpeg exited with code 1
   at Jellyfin.Api.Helpers.TranscodingJobHelper.StartFfMpeg(StreamState state, String outputPath, String commandLineArguments, HttpRequest request, TranscodingJobType transcodingJobType, CancellationTokenSource cancellationTokenSource, String workingDirectory)
   at Jellyfin.Api.Controllers.DynamicHlsController.GetDynamicSegment(StreamingRequestDto streamingRequest, Int32 segmentId)
   at Jellyfin.Api.Controllers.DynamicHlsController.GetHlsVideoSegment(Guid itemId, String playlistId, Int32 segmentId, String container, Int64 runtimeTicks, Int64 actualSegmentLengthTicks, Nullable`1 static, String params, String tag, String deviceProfileId, String playSessionId, String segmentContainer, Nullable`1 segmentLength, Nullable`1 minSegments, String mediaSourceId, String deviceId, String audioCodec, Nullable`1 enableAutoStreamCopy, Nullable`1 allowVideoStreamCopy, Nullable`1 allowAudioStreamCopy, Nullable`1 breakOnNonKeyFrames, Nullable`1 audioSampleRate, Nullable`1 maxAudioBitDepth, Nullable`1 audioBitRate, Nullable`1 audioChannels, Nullable`1 maxAudioChannels, String profile, String level, Nullable`1 framerate, Nullable`1 maxFramerate, Nullable`1 copyTimestamps, Nullable`1 startTimeTicks, Nullable`1 width, Nullable`1 height, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 videoBitRate, Nullable`1 subtitleStreamIndex, Nullable`1 subtitleMethod, Nullable`1 maxRefFrames, Nullable`1 maxVideoBitDepth, Nullable`1 requireAvc, Nullable`1 deInterlace, Nullable`1 requireNonAnamorphic, Nullable`1 transcodingMaxAudioChannels, Nullable`1 cpuCoreLimit, String liveStreamId, Nullable`1 enableMpegtsM2TsMode, String videoCodec, String subtitleCodec, String transcodeReasons, Nullable`1 audioStreamIndex, Nullable`1 videoStreamIndex, Nullable`1 context, Dictionary`2 streamOptions)
   at lambda_method1454(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

### Other Logs

```log
FFmpeg.DirectStream-* log:

file:/volume1/video/TV Series/Obi-Wan Kenobi/Season 01/Obi-Wan Kenobi - 1x01 - Part I.mkv: Permission denied

[hls @ 0x2229380] Failed to open file '/volume1/@appstore/jellyfin/var/data/transcodes/b46e5a714f6a6f394b119975c45f9d2b0.ts'
av_interleaved_write_frame(): Permission denied
```

```log
ffmpeg permissions:

$ ls -all  /var/packages/ffmpeg/target/bin/ffmpeg
-rwsr-xr-x 1 sc-ffmpeg ffmpeg 270104 Mar 28 23:14 /var/packages/ffmpeg/target/bin/ffmpeg

$ sudo -u sc-ffmpeg touch /volume1/@appstore/jellyfin/var/data/transcodes/test
touch: cannot touch ‘/volume1/@appstore/jellyfin/var/data/transcodes/test’: Permission denied
```

### Known Workaround

```bash
$ sudo chmod u-s+x /var/packages/ffmpeg/target/bin/ffmpeg
$ sudo chmod u-s+x /var/packages/ffmpeg/target/bin/vainfo
```

**Comment by mreid-tt** [comment]
hey @th0ma7, just wanted to let you know that on my DSM 6 setup, your new builds have changed permissions on install which all work with Jellyfin now. See new permissions on install:

```
$ ls -all /var/packages/ffmpeg/target/bin/ffmpeg
-rwsr-xr-x 1 root root 270040 May  3 01:42 /var/packages/ffmpeg/target/bin/ffmpeg
```
```
$ ls -all /var/packages/ffmpeg5/target/bin/ffmpeg
-rwsr-xr-x 1 root root 262624 May  3 00:23 /var/packages/ffmpeg5/target/bin/ffmpeg
```
```
$ ls -all /var/packages/ffmpeg6/target/bin/ffmpeg
-rwsr-xr-x 1 root root 295192 May  2 23:04 /var/packages/ffmpeg6/target/bin/ffmpeg
```

**Comment by th0ma7** [comment]
Thnx, one more fixed.  And is it working OK using all of the ffmpeg versions?

**Comment by mreid-tt** [comment]
> Thnx, one more fixed. And is it working OK using all of the ffmpeg versions?

Yes, I changed the FFmpeg path to each of these in turn and they all worked well.

**Comment by th0ma7** [comment]
Thnx for testing out, this is much appreciated :)
This issue will be closed out once I merge the PR.

**Comment by mreid-tt** [comment]
@th0ma7, I've downloaded and installed the latest builds. I noted a slight permissions change with the ffmpeg4 deployment as follows:

```
$ ls -all /var/packages/ffmpeg/target/bin/ffmpeg
-rwxr-xr-x 1 root root 270040 May  5 14:41 /var/packages/ffmpeg/target/bin/ffmpeg
$ ls -all /var/packages/ffmpeg/target/bin/vainfo
-rwxr-xr-x 1 root root 19920 May  5 14:41 /var/packages/ffmpeg/target/bin/vainfo
```
```
$ ls -all /var/packages/ffmpeg5/target/bin/ffmpeg
-rwsr-xr-x 1 root root 262624 May  5 12:58 /var/packages/ffmpeg5/target/bin/ffmpeg
$ ls -all /var/packages/ffmpeg5/target/bin/vainfo
-rwsr-xr-x 1 root root 19920 May  5 12:58 /var/packages/ffmpeg5/target/bin/vainfo
```
```
$ ls -all /var/packages/ffmpeg6/target/bin/ffmpeg
-rwsr-xr-x 1 root root 295192 May  5 11:16 /var/packages/ffmpeg6/target/bin/ffmpeg
$ ls -all /var/packages/ffmpeg6/target/bin/vainfo
-rwsr-xr-x 1 root root 19920 May  5 11:16 /var/packages/ffmpeg6/target/bin/vainfo
```

Note the `rwx` in ffmpeg4 compared with the `rws` for the other two versions.

As for the commands you wanted me to run:
```
$ /var/packages/ffmpeg/target/bin/vainfo
Trying display: drm
error: failed to initialize display
```
```
$ /var/packages/ffmpeg5/target/bin/vainfo
Trying display: drm
error: failed to initialize display
```
```
$ /var/packages/ffmpeg6/target/bin/vainfo
Trying display: drm
error: failed to initialize display
```
```
$ uname -a
Linux DSM62 4.4.59+ #25556 SMP PREEMPT Tue Mar 21 22:22:49 CST 2023 x86_64 GNU/Linux synology_kvmx64_virtualdsm
```

**Comment by th0ma7** [comment]
Thnx for the heads-up @mreid-tt .  I thought you where testing on a bare-metal intel NAS but you're rather testing on KVM which explains the failure when calling `vainfo`.

I've now fixed the ffmpeg4 setup script which should result in proper permissions.  Again thnx for taking time for testing.

**Comment by mreid-tt** [comment]
You’re welcome. My bare metal is already on DSM 7 so this is the only way to test that for me.

**Comment by mreid-tt** [comment]
> I've now fixed the ffmpeg4 setup script which should result in proper permissions. Again thnx for taking time for testing.

This is confirmed for the permissions on DSM 6. I also like the last change to make the version number just the major version.

**Comment by th0ma7** [comment]
again thnx for testing out :rocket:

**Comment by mreid-tt** [comment]
@th0ma7, as an update, I installed the new version on my production NAS and ran the commands you wanted. Don't know if the error is a concern or not...

```
$ uname -a
Linux Reid-NAS 3.10.108 #42962 SMP Fri Mar 24 12:30:20 CST 2023 x86_64 GNU/Linux synology_braswell_916+
```
```
$ sudo /var/packages/ffmpeg/target/bin/vainfo
Trying display: drm
libva info: VA-API version 1.18.0
libva info: Trying to open /var/packages/ffmpeg/target/lib/iHD_drv_video.so
libva info: va_openDriver() returns -1
libva info: Trying to open /var/packages/ffmpeg/target/lib/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_18
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.18 (libva 2.18.1)
vainfo: Driver version: Intel i965 driver for Intel(R) CherryView - 2.4.1
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264MultiviewHigh      :	VAEntrypointVLD
      VAProfileH264MultiviewHigh      :	VAEntrypointEncSlice
      VAProfileH264StereoHigh         :	VAEntrypointVLD
      VAProfileH264StereoHigh         :	VAEntrypointEncSlice
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileVP8Version0_3          :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
```
