### ISSUE TITLE
Radarr: SSL errors loading cover images

### ISSUE THREAD

**Issue by gingerbeardman** [SynoCommunity/spksrc#5763]
### Is this a new Bug?

- [X] I checked that the bug hasn't been reported before

### Package Name

Radarr

### Package Version

4.4.4.7068 (x64-6.1_20230426-20)

### Device Model

HP N54L

### Device Architecture

x86_64

### Firmware Version

6.2.3-25426 Update 3

### What happened?

- SSL connection errors when trying to download cover images

```
2023-06-01 23:12:25.0|Error|MediaCoverService|Couldn't download media cover for [Stargate: Continuum (2008)][tt0929629, 12914]

[v4.4.4.7068] System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate was rejected by the provided RemoteCertificateValidationCallback.
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellation(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 101
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 124
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 59
   at NzbDrone.Core.MediaCover.CoverAlreadyExistsSpecification.AlreadyExists(String url, String path) in D:\a\1\s\src\NzbDrone.Core\MediaCover\CoverAlreadyExistsSpecification.cs:line 33
   at NzbDrone.Core.MediaCover.MediaCoverService.EnsureCovers(Movie movie) in D:\a\1\s\src\NzbDrone.Core\MediaCover\MediaCoverService.cs:line 154
```

### Reproduction steps

1. Radarr
2. Update all
3. Missing thumbnails
4. Check logs in Radarr interface

Will attach logs when I can SSH into my device.

### Install Log

```log
2022/01/24 23:30:59	install radarr 20210311-15 Begin preinst
2022/01/24 23:30:59	install radarr 20210311-15 End preinst ret=[0]
2022/01/24 23:30:59	install radarr 20210311-15 Begin /bin/rm -rf /volume1/@appstore/radarr
2022/01/24 23:31:02	install radarr 20210311-15 End /bin/rm -rf /volume1/@appstore/radarr ret=[0]
2022/01/24 23:31:02	install radarr 20210311-15 Begin /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/radarr
2022/01/24 23:31:02	install radarr 20210311-15 End /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/radarr ret=[0]
2022/01/24 23:31:02	install radarr 20210311-15 Begin /bin/rm -rf /var/packages/radarr
2022/01/24 23:31:02	install radarr 20210311-15 End /bin/rm -rf /var/packages/radarr ret=[0]
2022/01/24 23:31:03	install radarr 20210311-15 Begin /bin/mkdir -p /var/packages/radarr
2022/01/24 23:31:03	install radarr 20210311-15 End /bin/mkdir -p /var/packages/radarr ret=[0]
2022/01/24 23:31:03	install radarr 20210311-15 Begin /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/radarr/INFO
2022/01/24 23:31:03	install radarr 20210311-15 End /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/radarr/INFO ret=[0]
2022/01/24 23:31:03	install radarr 20210311-15 Begin /bin/rm -rf /var/packages/radarr/scripts
2022/01/24 23:31:03	install radarr 20210311-15 End /bin/rm -rf /var/packages/radarr/scripts ret=[0]
2022/01/24 23:31:03	install radarr 20210311-15 Begin /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/radarr/scripts
2022/01/24 23:31:03	install radarr 20210311-15 End /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/radarr/scripts ret=[0]
2022/01/24 23:31:03	install radarr 20210311-15 Begin /bin/rm -rf /var/packages/radarr/WIZARD_UIFILES
2022/01/24 23:31:03	install radarr 20210311-15 End /bin/rm -rf /var/packages/radarr/WIZARD_UIFILES ret=[0]
2022/01/24 23:31:03	install radarr 20210311-15 Begin /bin/mv -f /volume1/@tmp/pkginstall/WIZARD_UIFILES /var/packages/radarr/WIZARD_UIFILES
2022/01/24 23:31:03	install radarr 20210311-15 End /bin/mv -f /volume1/@tmp/pkginstall/WIZARD_UIFILES /var/packages/radarr/WIZARD_UIFILES ret=[0]
2022/01/24 23:31:03	install radarr 20210311-15 Begin /bin/rm -rf /var/packages/radarr/conf
2022/01/24 23:31:03	install radarr 20210311-15 End /bin/rm -rf /var/packages/radarr/conf ret=[0]
2022/01/24 23:31:03	install radarr 20210311-15 Begin /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/radarr/conf
2022/01/24 23:31:03	install radarr 20210311-15 End /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/radarr/conf ret=[0]
2022/01/24 23:31:03	install radarr 20210311-15 Begin postinst
2022/01/24 23:31:04	install radarr 20210311-15 End postinst ret=[0]
2022/01/24 23:31:04	install radarr 20210311-15 Begin /bin/rm -rf /volume1/@tmp/pkginstall
2022/01/24 23:31:04	install radarr 20210311-15 End /bin/rm -rf /volume1/@tmp/pkginstall ret=[0]
2022/01/24 23:31:04	install radarr 20210311-15 Begin start-stop-status start
Starting radarr ...
2022/01/24 23:31:06	install radarr 20210311-15 End start-stop-status start ret=[0]

[---snip---]

2023/04/30 19:48:40	upgrade radarr 20230216-19 Begin start-stop-status stop
2023/04/30 19:48:41	upgrade radarr 20230216-19 End start-stop-status stop ret=[0]
2023/04/30 19:48:41	upgrade radarr 20230216-19 Begin preupgrade
2023/04/30 19:48:41	Begin load_variables_from_file
2023/04/30 19:48:41	End load_variables_from_file
2023/04/30 19:48:41	Begin initialize_variables
2023/04/30 19:48:41	End initialize_variables
2023/04/30 19:48:41	===> Step preupgrade. STATUS=UPGRADE USER=radarr GROUP=sc-download SHARE_PATH=
2023/04/30 19:48:41	Begin service_preupgrade
2023/04/30 19:48:41	Backup existing distribution to /volume1/@tmp/synopkg.tmp/radarr/backup
2023/04/30 19:48:46	End service_preupgrade
2023/04/30 19:49:01	upgrade radarr 20230216-19 End preupgrade ret=[0]
2023/04/30 19:49:01	upgrade radarr 20230216-19 Begin preuninst
2023/04/30 19:49:01	Begin load_variables_from_file
2023/04/30 19:49:01	End load_variables_from_file
2023/04/30 19:49:01	Begin initialize_variables
2023/04/30 19:49:01	End initialize_variables
2023/04/30 19:49:01	===> Step preuninst. STATUS=UPGRADE USER=radarr GROUP=sc-download SHARE_PATH=
2023/04/30 19:49:01	upgrade radarr 20230216-19 End preuninst ret=[0]
2023/04/30 19:49:01	upgrade radarr 20230216-19 Begin /bin/rm -rf /volume1/@appstore/radarr
2023/04/30 19:49:02	upgrade radarr 20230216-19 End /bin/rm -rf /volume1/@appstore/radarr ret=[0]
2023/04/30 19:49:03	upgrade radarr 20230216-19 Begin postuninst
2023/04/30 19:49:03	Begin load_variables_from_file
2023/04/30 19:49:03	End load_variables_from_file
2023/04/30 19:49:03	Begin initialize_variables
2023/04/30 19:49:03	End initialize_variables
2023/04/30 19:49:03	===> Step postuninst. STATUS=UPGRADE USER=radarr GROUP=sc-download SHARE_PATH=
2023/04/30 19:49:03	upgrade radarr 20230216-19 End postuninst ret=[0]
2023/04/30 19:49:03	upgrade radarr 20230426-20 Begin preinst
2023/04/30 19:49:03	Begin load_variables_from_file
2023/04/30 19:49:03	End load_variables_from_file
2023/04/30 19:49:03	Begin initialize_variables
2023/04/30 19:49:03	End initialize_variables
2023/04/30 19:49:03	===> Step preinst. STATUS=UPGRADE USER=radarr GROUP=sc-download SHARE_PATH=
2023/04/30 19:49:03	upgrade radarr 20230426-20 End preinst ret=[0]
2023/04/30 19:49:03	upgrade radarr 20230426-20 Begin /bin/rm -rf /volume1/@appstore/radarr
2023/04/30 19:49:03	upgrade radarr 20230426-20 End /bin/rm -rf /volume1/@appstore/radarr ret=[0]
2023/04/30 19:49:03	upgrade radarr 20230426-20 Begin /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/radarr
2023/04/30 19:49:03	upgrade radarr 20230426-20 End /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/radarr ret=[0]
2023/04/30 19:49:03	upgrade radarr 20230426-20 Begin /bin/mkdir -p /var/packages/radarr
2023/04/30 19:49:03	upgrade radarr 20230426-20 End /bin/mkdir -p /var/packages/radarr ret=[0]
2023/04/30 19:49:03	upgrade radarr 20230426-20 Begin /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/radarr/INFO
2023/04/30 19:49:03	upgrade radarr 20230426-20 End /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/radarr/INFO ret=[0]
2023/04/30 19:49:03	upgrade radarr 20230426-20 Begin /bin/rm -rf /var/packages/radarr/scripts
2023/04/30 19:49:03	upgrade radarr 20230426-20 End /bin/rm -rf /var/packages/radarr/scripts ret=[0]
2023/04/30 19:49:03	upgrade radarr 20230426-20 Begin /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/radarr/scripts
2023/04/30 19:49:03	upgrade radarr 20230426-20 End /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/radarr/scripts ret=[0]
2023/04/30 19:49:03	upgrade radarr 20230426-20 Begin /bin/rm -rf /var/packages/radarr/WIZARD_UIFILES
2023/04/30 19:49:03	upgrade radarr 20230426-20 End /bin/rm -rf /var/packages/radarr/WIZARD_UIFILES ret=[0]
2023/04/30 19:49:03	upgrade radarr 20230426-20 Begin /bin/mv -f /volume1/@tmp/pkginstall/WIZARD_UIFILES /var/packages/radarr/WIZARD_UIFILES
2023/04/30 19:49:03	upgrade radarr 20230426-20 End /bin/mv -f /volume1/@tmp/pkginstall/WIZARD_UIFILES /var/packages/radarr/WIZARD_UIFILES ret=[0]
2023/04/30 19:49:03	upgrade radarr 20230426-20 Begin /bin/rm -rf /var/packages/radarr/conf
2023/04/30 19:49:03	upgrade radarr 20230426-20 End /bin/rm -rf /var/packages/radarr/conf ret=[0]
2023/04/30 19:49:03	upgrade radarr 20230426-20 Begin /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/radarr/conf
2023/04/30 19:49:04	upgrade radarr 20230426-20 End /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/radarr/conf ret=[0]
2023/04/30 19:49:04	upgrade radarr 20230426-20 Begin postinst
2023/04/30 19:49:04	Begin load_variables_from_file
2023/04/30 19:49:04	End load_variables_from_file
2023/04/30 19:49:04	Begin initialize_variables
2023/04/30 19:49:04	End initialize_variables
2023/04/30 19:49:04	===> Step postinst. STATUS=UPGRADE USER=radarr GROUP=sc-download SHARE_PATH=
2023/04/30 19:49:04	Begin save_wizard_variables
2023/04/30 19:49:04	End save_wizard_variables
2023/04/30 19:49:04	Begin service_postinst
2023/04/30 19:49:04	Set update required
2023/04/30 19:49:04	Granting 'sc-radarr' unix ownership on /volume1/@appstore/radarr/var/.config
2023/04/30 19:49:04	End service_postinst
2023/04/30 19:49:04	Begin service_clean_tmpdir
2023/04/30 19:49:04	End service_clean_tmpdir
2023/04/30 19:49:04	Granting 'sc-radarr' unix ownership on /volume1/@appstore/radarr/var
2023/04/30 19:49:04	upgrade radarr 20230426-20 End postinst ret=[0]
2023/04/30 19:49:04	upgrade radarr 20230426-20 Begin postupgrade
2023/04/30 19:49:04	Begin load_variables_from_file
2023/04/30 19:49:04	End load_variables_from_file
2023/04/30 19:49:04	Begin initialize_variables
2023/04/30 19:49:04	End initialize_variables
2023/04/30 19:49:04	===> Step postupgrade. STATUS=UPGRADE USER=radarr GROUP=sc-download SHARE_PATH=
2023/04/30 19:49:18	Granting 'sc-radarr' unix ownership on /volume1/@appstore/radarr/var
2023/04/30 19:49:19	Begin service_postupgrade
2023/04/30 19:49:19	Restore previous distribution from /volume1/@tmp/synopkg.tmp/radarr/backup
2023/04/30 19:49:23	Granting 'sc-radarr' unix ownership on /volume1/@appstore/radarr/share
2023/04/30 19:49:23	End service_postupgrade
2023/04/30 19:49:23	upgrade radarr 20230426-20 End postupgrade ret=[0]
2023/04/30 19:49:25	upgrade radarr 20230426-20 Begin start-stop-status start
2023/04/30 19:49:28	upgrade radarr 20230426-20 End start-stop-status start ret=[0]
2023/04/30 19:49:28	upgrade radarr 20230426-20 Begin /bin/rm -rf /volume1/@tmp/pkginstall
2023/04/30 19:49:28	upgrade radarr 20230426-20 End /bin/rm -rf /volume1/@tmp/pkginstall ret=[0]
2023/04/30 19:53:45	install radarr 20230426-20 Begin start-stop-status stop
2023/04/30 19:53:46	install radarr 20230426-20 End start-stop-status stop ret=[0]
2023/04/30 19:55:49	(system) trigger radarr 20230426-20 Begin start-stop-status start
2023/04/30 19:56:05	(system) trigger radarr 20230426-20 End start-stop-status start ret=[0]
2023/05/09 21:45:27	(system) trigger radarr 20230426-20 Begin start-stop-status start
2023/05/09 21:45:40	(system) trigger radarr 20230426-20 End start-stop-status start ret=[0]
```

### Service Log

```log
...
[Error] X509CertificateValidationService: Certificate validation for image.tmdb.org failed. RemoteCertificateChainErrors 
[Error] MediaCoverService: Couldn't download media cover for [Wild Strawberries (1957)][tt0050986, 614] 

[v4.4.4.7068] System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate was rejected by the provided RemoteCertificateValidationCallback.
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellation(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 101
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 124
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 59
   at NzbDrone.Core.MediaCover.CoverAlreadyExistsSpecification.AlreadyExists(String url, String path) in D:\a\1\s\src\NzbDrone.Core\MediaCover\CoverAlreadyExistsSpecification.cs:line 33
   at NzbDrone.Core.MediaCover.MediaCoverService.EnsureCovers(Movie movie) in D:\a\1\s\src\NzbDrone.Core\MediaCover\MediaCoverService.cs:line 154

[---snip---]

[Error] X509CertificateValidationService: Certificate validation for radarr.servarr.com failed. RemoteCertificateChainErrors 
[Error] Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware: An unhandled exception has occurred while executing the request. 

[v4.4.4.7068] System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate was rejected by the provided RemoteCertificateValidationCallback.
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellation(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 101
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 124
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 59
   at NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 290
   at NzbDrone.Core.Update.UpdatePackageProvider.GetRecentUpdates(String branch, Version currentVersion, Version previousVersion) in D:\a\1\s\src\NzbDrone.Core\Update\UpdatePackageProvider.cs:line 86
   at NzbDrone.Core.Update.RecentUpdateProvider.GetRecentUpdatePackages() in D:\a\1\s\src\NzbDrone.Core\Update\RecentUpdateProvider.cs:line 33
   at Radarr.Api.V3.Update.UpdateController.GetRecentUpdates() in D:\a\1\s\src\Radarr.Api.V3\Update\UpdateController.cs:line 27
   at lambda_method406(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Radarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\StartingUpMiddleware.cs:line 41
   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

### Other Logs

```log
[---removed---]
```

**Comment by gingerbeardman** [comment]
Logs added

**Comment by mreid-tt** [comment]
Have you considered updating to a later version of DSM 6?

**Comment by gingerbeardman** [comment]
Of course I've considered it, but logistics mean it can't happen for me any time soon.

**Comment by mreid-tt** [comment]
I was looking at this part of the reported error:

```
The SSL connection could not be established, see inner exception.
 ---> The remote certificate was rejected by the provided RemoteCertificateValidationCallback.
```

This got me thinking that there must be something about the SSL certificate it didn't like. Then I remembered this posting on Discord:

> The Let’s Encrypt intermediate certificate expired recently so all you need to do is update your DSM6 version which will update the root trust store and fix the issue. If you want to continue to stay on an old versions (not recommended obviously) you can update the trust store manually by overriding the file with a more recent one, using SSH: `sudo mv /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt.bak && sudo curl -Lko /etc/ssl/certs/ca-certificates.crt https://curl.se/ca/cacert.pem` This will fix the issue, alternatively you can set the clock back. The best solution however is to update to a more recent DSM6 version.
> 
> **You need to update to NAS version 6.2.4-25556 Update 2 or later for the DSM to be able to load our site.**
> 
> > 6.2.4-25556 Update 2 Release Notes:
> > 10. Updated the OpenSSL setting in response to new rules of Let's Encrypt certificates.

Given you are running 6.2.3-25426 Update 3, I would propose upgrading to something newer in the DSM 6 releases. I don't believe that upgrading to DSM 7 is mandatory, as this is a major change.

**Comment by hgy59** [comment]
@gingerbeardman you tell us you model is "HP N54L". This is not a SynologyDSM, I suppose you have installed Xpenology or similar.

You should ask there. But from our perspective, you have to update to at least DSM 6.2.4-25556.


And you can validate the ssl handshare yourself by running the following command in a shell of your system
```
curl -o /dev/null -v  https://www.themoviedb.org
```

If you get an error, you probably can fix this by updating the ca certificates in `/etc/ssl/certs/ca-certificates.crt`

**Comment by gingerbeardman** [comment]
Thanks, I'll try that. 

I only have remote access to my machine since some months. It's a less than ideal situation in many ways. But I'll upgrade it asap

**Comment by gingerbeardman** [comment]
I updated my certs and all is well.

**Comment by mreid-tt** [comment]
You're welcome, will close the issue now.
