### ISSUE TITLE
Python 3.11 fails to build on current master

### ISSUE THREAD

**Issue by hgy59** [SynoCommunity/spksrc#5855]
@th0ma7 The current build of Python 3.11.4 fails for all archs except aarch64.

The error occurred when building wheel maturin for cross env
```
AttributeError: module 'setuptools_rust.setuptools_ext' has no attribute 'pyprojecttoml_config'
```

Extract of build log of https://github.com/SynoCommunity/spksrc/actions/runs/5979605635/job/16224141689

```
2023-08-25T19:35:54.2851531Z Collecting maturin==1.1.0
2023-08-25T19:35:54.2913041Z   Downloading maturin-1.1.0.tar.gz (181 kB)
2023-08-25T19:35:54.2941733Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 181.2/181.2 kB 284.4 MB/s eta 0:00:00
2023-08-25T19:35:54.3187824Z   Installing build dependencies: started
2023-08-25T19:35:56.2675083Z   Installing build dependencies: finished with status 'done'
2023-08-25T19:35:56.2686165Z   Getting requirements to build wheel: started
2023-08-25T19:35:56.6581742Z   Getting requirements to build wheel: finished with status 'done'
2023-08-25T19:35:56.6633377Z   Preparing metadata (pyproject.toml): started
2023-08-25T19:35:57.0492176Z   Preparing metadata (pyproject.toml): finished with status 'error'
2023-08-25T19:35:57.0556002Z   error: subprocess-exited-with-error
2023-08-25T19:35:57.0556423Z 
2023-08-25T19:35:57.0556887Z   × Preparing metadata (pyproject.toml) did not run successfully.
2023-08-25T19:35:57.0557283Z   │ exit code: 1
2023-08-25T19:35:57.0557594Z   ╰─> [34 lines of output]
2023-08-25T19:35:57.0557881Z       Traceback (most recent call last):
2023-08-25T19:35:57.0558603Z         File "/github/workspace/spk/python311/work-x64-6.2.4/crossenv/build/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
2023-08-25T19:35:57.0559327Z           main()
2023-08-25T19:35:57.0559973Z         File "/github/workspace/spk/python311/work-x64-6.2.4/crossenv/build/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
2023-08-25T19:35:57.0560559Z           json_out['return_val'] = hook(**hook_input['kwargs'])
2023-08-25T19:35:57.0560879Z                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-25T19:35:57.0561613Z         File "/github/workspace/spk/python311/work-x64-6.2.4/crossenv/build/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
2023-08-25T19:35:57.0562163Z           return hook(metadata_directory, config_settings)
2023-08-25T19:35:57.0562477Z                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-25T19:35:57.0563223Z         File "/github/workspace/spk/python311/work-x64-6.2.4/crossenv/build/lib/python3.11/site-packages/setuptools/build_meta.py", line 188, in prepare_metadata_for_build_wheel
2023-08-25T19:35:57.0563684Z           self.run_setup()
2023-08-25T19:35:57.0564278Z         File "/github/workspace/spk/python311/work-x64-6.2.4/crossenv/build/lib/python3.11/site-packages/setuptools/build_meta.py", line 174, in run_setup
2023-08-25T19:35:57.0564785Z           exec(code, locals())
2023-08-25T19:35:57.0565067Z         File "<string>", line 53, in <module>
2023-08-25T19:35:57.0565674Z         File "/github/workspace/spk/python311/work-x64-6.2.4/crossenv/build/lib/python3.11/site-packages/setuptools/__init__.py", line 87, in setup
2023-08-25T19:35:57.0566130Z           return distutils.core.setup(**attrs)
2023-08-25T19:35:57.0566430Z                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-25T19:35:57.0567029Z         File "/github/workspace/spk/python311/work-x64-6.2.4/crossenv/build/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 147, in setup
2023-08-25T19:35:57.0567497Z           _setup_distribution = dist = klass(attrs)
2023-08-25T19:35:57.0567783Z                                        ^^^^^^^^^^^^
2023-08-25T19:35:57.0568361Z         File "/github/workspace/spk/python311/work-x64-6.2.4/crossenv/build/lib/python3.11/site-packages/setuptools/dist.py", line 476, in __init__
2023-08-25T19:35:57.0568852Z           _Distribution.__init__(
2023-08-25T19:35:57.0569538Z         File "/github/workspace/spk/python311/work-x64-6.2.4/crossenv/build/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 280, in __init__
2023-08-25T19:35:57.0569980Z           self.finalize_options()
2023-08-25T19:35:57.0570583Z         File "/github/workspace/spk/python311/work-x64-6.2.4/crossenv/build/lib/python3.11/site-packages/setuptools/dist.py", line 899, in finalize_options
2023-08-25T19:35:57.0571053Z           for ep in sorted(loaded, key=by_order):
2023-08-25T19:35:57.0571350Z                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-25T19:35:57.0571938Z         File "/github/workspace/spk/python311/work-x64-6.2.4/crossenv/build/lib/python3.11/site-packages/setuptools/dist.py", line 898, in <lambda>
2023-08-25T19:35:57.0572390Z           loaded = map(lambda e: e.load(), filtered)
2023-08-25T19:35:57.0572681Z                                  ^^^^^^^^
2023-08-25T19:35:57.0573244Z         File "/github/workspace/native/python311/work-native/install/usr/local/lib/python3.11/importlib/metadata/__init__.py", line 204, in load
2023-08-25T19:35:57.0573720Z           return functools.reduce(getattr, attrs, module)
2023-08-25T19:35:57.0574032Z                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-25T19:35:57.0574533Z       AttributeError: module 'setuptools_rust.setuptools_ext' has no attribute 'pyprojecttoml_config'
2023-08-25T19:35:57.0574906Z       [end of output]
2023-08-25T19:35:57.0575125Z   
2023-08-25T19:35:57.0575464Z   note: This error originates from a subprocess, and is likely not a problem with pip.
2023-08-25T19:35:57.0598903Z error: metadata-generation-failed
```

**Comment by th0ma7** [comment]
Maybe reverting to its previous version may help?

**Comment by th0ma7** [comment]
@hgy59 Now back from vacation and will be looking into this.  This is really weird as it was working out all-right when I created py310-311 updated packages?!?  Also, maturin wasn`t update during the last round of PR.

Anyhow, I was able to reproduce.  I'll try to figure out where the issue lies while also updating py310-311 to newest versions.
