### ISSUE TITLE
Home Assistant - Tradfri integration not working after upgrade to 2023.7.3

### ISSUE THREAD

**Issue by RedEarth1** [SynoCommunity/spksrc#5856]
### Is this a new Bug?

- [X] I checked that the bug hasn't been reported before

### Package Name

Home Assistant

### Package Version

2023.7.3

### Device Model

DS214play

### Device Architecture

i686 (evansport)

### Firmware Version

DSM 7.1.1-42962 update 5

### What happened?

I upgraded Home Assistant to 2023.7.3 and the Ikea Tradfri integration is reporting 'Failed to set up' on the integrations screen.

Logger: homeassistant.config_entries
Source: components/tradfri/__init__.py:77
First occurred: 15:30:45 (1 occurrences)
Last logged: 15:30:45

Error setting up entry 192.168.1.198 for tradfri
Traceback (most recent call last):
  File "/volume1/@appstore/homeassistant/env/lib/python3.11/site-packages/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volume1/@appstore/homeassistant/env/lib/python3.11/site-packages/homeassistant/components/tradfri/__init__.py", line 77, in async_setup_entry
    gateway_info = await api(gateway.get_gateway_info(), timeout=TIMEOUT_API)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volume1/@appstore/homeassistant/env/lib/python3.11/site-packages/pytradfri/api/aiocoap_api.py", line 199, in request
    result = await self._execute(api_commands, timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volume1/@appstore/homeassistant/env/lib/python3.11/site-packages/pytradfri/api/aiocoap_api.py", line 167, in _execute
    _, res = await self._get_response(msg, timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volume1/@appstore/homeassistant/env/lib/python3.11/site-packages/pytradfri/api/aiocoap_api.py", line 107, in _get_response
    pr_resp = await asyncio.wait_for(pr_req.response, timeout)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/packages/python311/target/lib/python3.11/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/volume1/@appstore/homeassistant/env/lib/python3.11/site-packages/aiocoap/protocol.py", line 606, in _run_outer
    await cls._run(app_request, response, weak_observation, protocol, log)
  File "/volume1/@appstore/homeassistant/env/lib/python3.11/site-packages/aiocoap/protocol.py", line 631, in _run
    await protocol.find_remote_and_interface(app_request)
  File "/volume1/@appstore/homeassistant/env/lib/python3.11/site-packages/aiocoap/protocol.py", line 336, in find_remote_and_interface
    raise RuntimeError("No request interface could route message")
RuntimeError: No request interface could route message

### Reproduction steps

1. Upgraded to latest version of HA package in the DSM GUI
2. Restarted HA package service
3. 
...

### Install Log

```log
2023/08/26 11:21:19	stop homeassistant 2023.7.3-21 Begin start-stop-status stop
2023/08/26 11:21:40	stop homeassistant 2023.7.3-21 End start-stop-status stop ret=[0]
2023/08/26 11:21:52	start homeassistant 2023.7.3-21 Begin start-stop-status start
2023/08/26 11:21:52	start homeassistant 2023.7.3-21 End start-stop-status start ret=[0]
2023/08/26 15:28:57	stop homeassistant 2023.7.3-21 Begin start-stop-status stop
2023/08/26 15:29:19	stop homeassistant 2023.7.3-21 End start-stop-status stop ret=[0]
2023/08/26 15:29:40	start homeassistant 2023.7.3-21 Begin start-stop-status start
2023/08/26 15:29:40	start homeassistant 2023.7.3-21 End start-stop-status start ret=[0]
```

### Service Log

```log
2023-08-26 15:30:00.189 INFO (SyncWorker_3) [homeassistant.loader] Loaded tradfri from homeassistant.components.tradfri
...
2023-08-26 15:30:00.836 INFO (MainThread) [homeassistant.bootstrap] Domains to be set up: {'hildebrandglow_dcc', 'map', 'stream', 'input_number', 'conversation', 'ifttt', 'nfandroidtv', 'blueprint', 'schedule', 'panasonic_viera', 'dhcp', 'dyson_local', 'aurora', 'bluetooth', 'input_text', 'hacs', 'input_boolean', 'repairs', 'trace', 'config', 'ssdp', 'cloud', 'history', 'tts', 'application_credentials', 'person', 'sensor', 'mqtt_statestream', 'uptime', 'season', 'image_upload', 'file_upload', 'lovelace', 'input_datetime', 'input_button', 'utility_meter', 'persistent_notification', 'http', 'device_tracker', 'sun', 'tradfri', 'hardware', 'auth', 'device_automation', 'mobile_app', 'dlna_dms', 'mqtt', 'dlna_dmr', 'my', 'met', 'ramses_cc', 'spotify', 'cast', 'zeroconf', 'script', 'network', 'rfxtrx', 'usb', 'diagnostics', 'stt', 'workday', 'recorder', 'syncthru', 'websocket_api', 'logbook', 'radio_browser', 'group', 'gdacs', 'co2signal', 'analytics', 'system_health', 'media_source', 'assist_pipeline', 'zone', 'local_calendar', 'timer', 'meross_lan', 'scene', 'tag', 'default_config', 'search', 'counter', 'homeassistant_alerts', 'moon', 'automation', 'denonavr', 'webhook', 'switch_as_x', 'api', 'energy', 'logger', 'frontend', 'input_select', 'system_log', 'onboarding'}
...
2023-08-26 15:30:20.717 INFO (MainThread) [homeassistant.bootstrap] Setting up stage 2: {'mobile_app', 'dlna_dms', 'mqtt', 'dlna_dmr', 'hildebrandglow_dcc', 'map', 'stream', 'my', 'input_number', 'conversation', 'met', 'ifttt', 'ramses_cc', 'spotify', 'cast', 'nfandroidtv', 'blueprint', 'schedule', 'script', 'rfxtrx', 'panasonic_viera', 'diagnostics', 'dyson_local', 'stt', 'workday', 'syncthru', 'aurora', 'input_text', 'hacs', 'logbook', 'input_boolean', 'radio_browser', 'repairs', 'trace', 'config', 'history', 'group', 'tts', 'gdacs', 'co2signal', 'analytics', 'system_health', 'media_source', 'assist_pipeline', 'zone', 'local_calendar', 'timer', 'meross_lan', 'application_credentials', 'scene', 'tag', 'default_config', 'person', 'search', 'sensor', 'counter', 'homeassistant_alerts', 'mqtt_statestream', 'uptime', 'moon', 'season', 'image_upload', 'file_upload', 'lovelace', 'automation', 'denonavr', 'input_datetime', 'input_button', 'switch_as_x', 'utility_meter', 'persistent_notification', 'device_tracker', 'energy', 'sun', 'input_select', 'tradfri', 'hardware', 'auth', 'onboarding', 'device_automation'}
...
2023-08-26 15:30:43.422 INFO (MainThread) [homeassistant.setup] Setting up tradfri
2023-08-26 15:30:43.424 INFO (MainThread) [homeassistant.setup] Setup of domain tradfri took 0.0 seconds
...
2023-08-26 15:30:45.382 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 192.168.1.198 for tradfri
Traceback (most recent call last):
  File "/volume1/@appstore/homeassistant/env/lib/python3.11/site-packages/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volume1/@appstore/homeassistant/env/lib/python3.11/site-packages/homeassistant/components/tradfri/__init__.py", line 77, in async_setup_entry
    gateway_info = await api(gateway.get_gateway_info(), timeout=TIMEOUT_API)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volume1/@appstore/homeassistant/env/lib/python3.11/site-packages/pytradfri/api/aiocoap_api.py", line 199, in request
    result = await self._execute(api_commands, timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volume1/@appstore/homeassistant/env/lib/python3.11/site-packages/pytradfri/api/aiocoap_api.py", line 167, in _execute
    _, res = await self._get_response(msg, timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volume1/@appstore/homeassistant/env/lib/python3.11/site-packages/pytradfri/api/aiocoap_api.py", line 107, in _get_response
    pr_resp = await asyncio.wait_for(pr_req.response, timeout)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/packages/python311/target/lib/python3.11/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/volume1/@appstore/homeassistant/env/lib/python3.11/site-packages/aiocoap/protocol.py", line 606, in _run_outer
    await cls._run(app_request, response, weak_observation, protocol, log)
  File "/volume1/@appstore/homeassistant/env/lib/python3.11/site-packages/aiocoap/protocol.py", line 631, in _run
    await protocol.find_remote_and_interface(app_request)
  File "/volume1/@appstore/homeassistant/env/lib/python3.11/site-packages/aiocoap/protocol.py", line 336, in find_remote_and_interface
    raise RuntimeError("No request interface could route message")
RuntimeError: No request interface could route message
```

**Comment by hgy59** [comment]
oops, sorry, we already had this error with an earlier version in #4403
As dtlssocket is a runtime only dependency, that is not detected by pip, it was unintentionally removed for HA 2023.7.3-21.
