### ISSUE TITLE
Offering info - Jellyfin working on evansport arch CPUs NASes like DS214Play (x86)

### ISSUE THREAD

**Issue by smymm** [SynoCommunity/spksrc#5941]
Hi!
I'm new here. I only registered to try to provide some info here to help with Synology NASes mounting Intel 32 bit processors (x86), like the DS214Play or DS415Play (CPU Intel Atom CE5335 "Evansport") to have Jellyfin working, if someone want to try.

I really wanted Jellyfin working in my DS214Play with DSM6, and I noticed that a package for these evansport CPUs doesn't exist and it's officially not supported, so I tried myself and I succeeded. I don't need transcoding (my players/client devices supports all codecs, so it's OK for me). Did some "quick an dirty" job on the existing Jellyfin spksrc in my Linux box to compile everything, and the result was a working package (For DSM 6.2.4, my DSM version). Finally I have a good media server working in my old NAS! (If you want to try the package in your NAS, I uploaded it here: https://github.com/smymm/miscSpksrcReleases/blob/main/Jellyfin-evansport/jellyfin_evansport-6.2.4_10.8.12-12.spk ). It's working OK if you dont' need transcoding (which is slow).

I don't have a lot of time now to explain everything with details, and someone here with the proper knowledge could add the correct way to do it to the repository (even though I guess it won't be added officially as 32 bit support is not welcome here for JF, and I understand it.), but these are some useful tips for getting this to compile and to get it working if you want to try, to give these old NASes a chance (I compiled Jellyfin v10.8.12):

- The main problem is the lack of DotNet SDK for linux-x86 and the same happens with NodeJS for linux-x86 (jellyfin-web). These unofficial packages solve the problem, as they are close to the originals:

* For DotNet: https://github.com/Servarr/dotnet-linux-x86/releases  (I used all the packages in the version dotnet linux-x86 v6.0.25-72)
* For NodeJS: https://unofficial-builds.nodejs.org/download/release/v18.4.0/ (I used node-v18.4.0-linux-x86.tar.xz , this is the last version suppoting x86 CPUs)

I calculated digests for the digests files required in the spksrc:

dotnet-sdk-6.0.417-linux-x86.tar.gz SHA1 539D2F97A0495A9497737A2EB3C5A5F573224879
dotnet-sdk-6.0.417-linux-x86.tar.gz SHA256 FE192CD9497CE0E66AC2FEFDBD8E3859EA0A84C82C51F544218BD1B230DFD335
dotnet-sdk-6.0.417-linux-x86.tar.gz MD5 975FFC9C3F954E350A15A0A68298C46C

node-v18.4.0-linux-x86.tar.xz SHA1 6E25CE573AE108F5CA9801C8A8B68F73E662EF8C
node-v18.4.0-linux-x86.tar.xz SHA256 EE38A001F25DED65FBBE3043E5884B32479AB7AC6770D8BFECE2BFF030F28F7B
node-v18.4.0-linux-x86.tar.xz MD5 3B2C42D2C4527314FB016C7641C2DA3C

- You will also need (for the Docker of spksrc) some utils required by dotnet x86 in x86 binaries, so if you get errors when the scripts run "dotnet", like libicu, liblldb, others.... you'll need to install them, first adding the arch: dpkg --add-architecture i386 , and then install the required tools with the i386 support: apt install tool:i386

- Makefile files also need to be modified (this is not the right way, but I did a quick and dirty modifications just for my needs)

* For the native dotnet-sdk-6.0 it's like:

PKG_VERS = 6.0.417
PKG_EXT = tar.gz
PKG_DIST_NAME = dotnet-sdk-$(PKG_VERS)-linux-x86.$(PKG_EXT)
PKG_DIST_SITE = https://github.com/Servarr/dotnet-linux-x86/releases/download/v6.0.25-72/

* For the native nodejs, it's like:

PKG_VERS = 18.4.0
PKG_EXT = tar.xz
PKG_DIST_NAME = node-v$(PKG_VERS)-linux-x86.$(PKG_EXT)
PKG_DIST_SITE = https://unofficial-builds.nodejs.org/download/release/v$(PKG_VERS)
PKG_DIR = node-v$(PKG_VERS)-linux-x86

* For the spk/jellyfin:

Comment / remove line: #UNSUPPORTED_ARCHS = $(32bit_ARCHS)

* For the cross-dotnet-env.mk:

Remove $(i686_ARCHS) from the UNSUPPORTED_ARCHS var

- You will also need to add the *.nupkg files to a directory (for example, create /spksrc/native/dotnet-sdk-6.0/nuget) and add a local path for NuGet to get the correct packages for dotnet, because the online official pacakges will not be found, as they don't exist online:

* Add all *.nupkg files from https://github.com/Servarr/dotnet-linux-x86/releases to the desired folder (for example /spksrc/native/dotnet-sdk-6.0/nuget)
* In the Docker just edit /root/.nuget/NuGet/NuGet.Config and add in the packagesoruces section: 

<add key="Local" value="/spksrc/native/dotnet-sdk-6.0/nuget" />

If everything is Ok, it should compile, using the evansport arch, like: make arch-evansport-6.2.4

It worked for me, I'm happy with it using as a server for my iOS, tvOS (and others)... devices' media apps. I don't know if this would be useful for someone like me, with an old NAS but wanting to have a very good media server if you don't need transcoding.

... Smy.

**Comment by ymartin59** [comment]
Thanks for pointing existenc of these DotNet port for x86. We will see how to integrate and reuse in our build chain.

**Comment by hgy59** [comment]
@smymm Thank you letting us know.

Unfortunately Jellyfin 1.9.x requires DSM 7.2, that is not supported on x86 models anymore.
Only x64, aarch64 and some armv7 models have got an update to DSM 7.2

The SynoCommunity Package jellyfin 10.8.13-13 will be the latest for x86 models
It is currently not available in our repository.

**Comment by ElfsRage** [comment]
Hello,
I just tested your jellyfin version for evansport DSM6 on my DSM7.
Overall, it works but I have a lot of errors:
[ERR] [3] Emby.Server.Implementations.Dto.DtoService: Failed to determine primary image aspect ratio for "/volume1/@appdata/jellyfin/data/metadata/library/ea/xxxxxx/poster.jpg"
System.NotImplementedException: The method or operation is not implemented.
   at Emby.Drawing.NullImageEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Dto.DtoService.GetPrimaryImageAspectRatio(BaseItem item)
Could you help me because I am a novice in this field.
Thanks!!

**Comment by hgy59** [comment]
@ElfsRage I suppose you have to abandon this idea, if the jellyfin 10.8.12 spk files provided by @smymm do not work.

Meanwhile we have jellyfin 10.10.x and build with dotnet 8 and nodejs 22.
I have tried to build jellyfin 10.10.6 for evansport-7.1 with x86 dotnet 8 sdk [dotnet-sdk-8.0.204-linux-x86](https://github.com/Servarr/dotnet-linux-x86/releases/download/v8.0.4-90/dotnet-sdk-8.0.204-linux-x86.tar.gz)
and got this error:
```
Failed to create CoreCLR, HRESULT: 0x8007000E
```

**Comment by ElfsRage** [comment]
Hello, thank you for your answer.

For the moment, the jellyfin (@smymm) works despite:
- that I have these errors above.
- that I had to disable the automatic scan and the generation of BIF files.

This is enough for me at least, for now.

Because while waiting to have a NAS with real-time transcoding in AV1, my goal would be to have the most recent jellyfin possible on evansport.
So, if I can test a functional version it would be with pleasure. :)
I would be delighted, if this day could come!
And you have ideas, to achieve my goals, I am a taker.

Thanking you, for all the help you bring to our old NAS. :)
