### ISSUE TITLE
sonarr v4 version bump

### ISSUE THREAD

**Issue by bakerboy448** [SynoCommunity/spksrc#5945]
### Is this a new Bug?

- [X] I checked that the bug hasn't been reported before

### Package Name

Sonarr (v4 beta)

### Package Version

n/a

### Device Model

n/a

### Device Architecture

x86_64

### Firmware Version

n/a

### What happened?

https://forums.sonarr.tv/t/error-parsing-column-when-i-try-to-open-sonarr/32959

due to database migrations the current package is too old and needs a bump

### Reproduction steps

n/a

### Install Log

```log
n/a
```

### Service Log

```log
n/a
```

### Other Logs

```log
n/a
```

**Comment by mreid-tt** [comment]
@bakerboy448, an updated version (20231129-3) has been released and is expected to be accessible within the next 24-48 hours as the caching servers synchronize. For those eager to get it sooner, a manual download option may be available a few hours ahead of schedule at https://synocommunity.com/package/sonarr.

**Comment by mreid-tt** [comment]
@bakerboy448, I was doing a test clean-install of the new package under DSM 6 and I don't think it will solve this issue for users. While an upgrade works, a clean install with a fresh database setup results in the following error:

```
[Info] disable_eztv: Starting migration of Main DB to 74 
[Info] FluentMigrator.Runner.MigrationRunner: ExecuteSqlStatement UPDATE "Indexers" SET "EnableRss" = false, "EnableSearch" = false WHERE "Implementation" = 'Eztv' AND "Settings" LIKE '%ezrss.it%' 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: UPDATE "Indexers" SET "EnableRss" = false, "EnableSearch" = false WHERE "Implementation" = 'Eztv' AND "Settings" LIKE '%ezrss.it%' 
[Error] FluentMigrator.Runner.MigrationRunner: SQL logic error or missing database
no such column: false
While Processing:
"UPDATE "Indexers" SET "EnableRss" = false, "EnableSearch" = false WHERE "Implementation" = 'Eztv' AND "Settings" LIKE '%ezrss.it%'" 

[v4.0.0.733] System.Exception: SQL logic error or missing database
no such column: false
While Processing:
"UPDATE "Indexers" SET "EnableRss" = false, "EnableSearch" = false WHERE "Implementation" = 'Eztv' AND "Settings" LIKE '%ezrss.it%'"
 ---> code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error or missing database
no such column: false
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.ExecuteNonQuery(String sql)
   --- End of inner exception stack trace ---
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.ExecuteNonQuery(String sql)
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.Execute(String template, Object[] args)
   at FluentMigrator.Runner.Processors.ProcessorBase.Execute(String sql)
   at FluentMigrator.Expressions.ExecuteSqlStatementExpression.ExecuteWith(IMigrationProcessor processor)
   at FluentMigrator.Runner.StopWatch.Time(Action action)
   at FluentMigrator.Runner.MigrationRunner.ExecuteExpressions(ICollection`1 expressions)

[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Rolling back transaction 


[Fatal] ConsoleApp: EPIC FAIL! 

[v4.0.0.733] NzbDrone.Common.Exceptions.SonarrStartupException: Sonarr failed to start: Error creating main database
 ---> System.Exception: SQL logic error or missing database
no such column: false
While Processing:
"UPDATE "Indexers" SET "EnableRss" = false, "EnableSearch" = false WHERE "Implementation" = 'Eztv' AND "Settings" LIKE '%ezrss.it%'"
 ---> code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error or missing database
no such column: false
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.ExecuteNonQuery(String sql)
   --- End of inner exception stack trace ---
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.ExecuteNonQuery(String sql)
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.Execute(String template, Object[] args)
   at FluentMigrator.Runner.Processors.ProcessorBase.Execute(String sql)
   at FluentMigrator.Expressions.ExecuteSqlStatementExpression.ExecuteWith(IMigrationProcessor processor)
   at FluentMigrator.Runner.StopWatch.Time(Action action)
   at FluentMigrator.Runner.MigrationRunner.ExecuteExpressions(ICollection`1 expressions)
   at FluentMigrator.Runner.MigrationRunner.ApplyMigrationUp(IMigrationInfo migrationInfo, Boolean useTransaction)
   at FluentMigrator.Runner.MigrationRunner.MigrateUp(Int64 targetVersion, Boolean useAutomaticTransactionManagement)
   at FluentMigrator.Runner.MigrationRunner.MigrateUp(Boolean useAutomaticTransactionManagement)
   at FluentMigrator.Runner.MigrationRunner.MigrateUp()
   at NzbDrone.Core.Datastore.Migration.Framework.MigrationController.Migrate(String connectionString, MigrationContext migrationContext) in ./Sonarr.Core/Datastore/Migration/Framework/MigrationController.cs:line 79
   at NzbDrone.Core.Datastore.DbFactory.CreateMain(String connectionString, MigrationContext migrationContext) in ./Sonarr.Core/Datastore/DbFactory.cs:line 116
   --- End of inner exception stack trace ---
   at NzbDrone.Core.Datastore.DbFactory.CreateMain(String connectionString, MigrationContext migrationContext) in ./Sonarr.Core/Datastore/DbFactory.cs:line 164
   at NzbDrone.Core.Datastore.DbFactory.Create(MigrationContext migrationContext) in ./Sonarr.Core/Datastore/DbFactory.cs:line 71
   at NzbDrone.Core.Datastore.DbFactory.Create(MigrationType migrationType) in ./Sonarr.Core/Datastore/DbFactory.cs:line 59
   at NzbDrone.Core.Datastore.Extensions.CompositionExtensions.<>c.<AddDatabase>b__0_0(IDbFactory f) in ./Sonarr.Core/Datastore/Extensions/CompositionExtensions.cs:line 10
   at DryIoc.Registrator.ToFuncWithObjParams[D1,TService](Func`2 f, Object d1) in /_/src/DryIoc/Container.cs:line 8046
   at DryIoc.Interpreter.TryInterpretFuncInvoke(IResolverContext r, MethodCallExpression e, IParameterProvider paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Object& result) in /_/src/DryIoc/Container.cs:line 3706
   at DryIoc.Interpreter.TryInterpretMethodCall(IResolverContext r, MethodCallExpression callExpr, IParameterProvider paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Object& result) in /_/src/DryIoc/Container.cs:line 3504
   at DryIoc.Interpreter.TryInterpret(IResolverContext r, Expression expr, IParameterProvider paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Object& result) in /_/src/DryIoc/Container.cs:line 3155
   at DryIoc.Interpreter.TryInterpretSingletonAndUnwrapContainerException(IResolverContext r, Expression expr, ImMapEntry`1 itemRef, Object& result) in /_/src/DryIoc/Container.cs:line 3084
   at DryIoc.Factory.ApplyReuse(Expression serviceExpr, Request request) in /_/src/DryIoc/Container.cs:line 11110
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 11029
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 12056
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 11012
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 12056
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 11012
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 12056
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 11012
   at DryIoc.Container.ResolveAndCache(Int32 serviceTypeHash, Type serviceType, IfUnresolved ifUnresolved) in /_/src/DryIoc/Container.cs:line 423
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved) in /_/src/DryIoc/Container.cs:line 389
   at DryIoc.Resolver.Resolve[TService](IResolver resolver, IfUnresolved ifUnresolved) in /_/src/DryIoc/Container.cs:line 8581
   at Sonarr.Http.ClientSchema.SchemaBuilder.Initialize(IContainer container) in ./Sonarr.Http/ClientSchema/SchemaBuilder.cs:line 24
   at NzbDrone.Host.Bootstrap.<>c__DisplayClass3_0.<CreateConsoleHostBuilder>b__2(IContainer c) in ./Sonarr.Host/Bootstrap.cs:line 150
   at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.<>c__DisplayClass10_0`1.<ConfigureContainer>b__0(HostBuilderContext context, TContainerBuilder builder)
   at Microsoft.Extensions.Hosting.Internal.ConfigureContainerAdapter`1.ConfigureContainer(HostBuilderContext hostContext, Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at NzbDrone.Host.Bootstrap.Start(String[] args, Action`1 trayCallback) in ./Sonarr.Host/Bootstrap.cs:line 80
   at NzbDrone.Console.ConsoleApp.Main(String[] args) in ./Sonarr.Console/ConsoleApp.cs:line 45

Press enter to exit...
Non-recoverable failure, waiting for user intervention...
```

I also tried building a new package to upgrade to the main branch v4.0.0.748 (#5980) and got a similar issue. Is this known by the Sonarr folks?

**Comment by bakerboy448** [comment]
Smells like a bug worth reporting to sonarr.

The query is treating a bool as a column

**Comment by bakerboy448** [comment]
This was the query pre-Postgres             Execute.Sql("UPDATE Indexers SET EnableRss = 0, EnableSearch = 0 WHERE Implementation = 'Eztv' AND Settings LIKE '%ezrss.it%'");

So seems perhaps SQLite may not have the value as a bool?

**Comment by mreid-tt** [comment]
Hmm, something must have changed because with a v4.0.0.460 install it had no problem getting past this point.

```
[...]
[Info] FluentMigrator.Runner.MigrationRunner: 74: disable_eztv migrating 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Beginning Transaction 
[Info] disable_eztv: Starting migration of Main DB to 74 
[Info] FluentMigrator.Runner.MigrationRunner: ExecuteSqlStatement UPDATE Indexers SET EnableRss = 0, EnableSearch = 0 WHERE Implementation = 'Eztv' AND Settings LIKE '%ezrss.it%' 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: UPDATE Indexers SET EnableRss = 0, EnableSearch = 0 WHERE Implementation = 'Eztv' AND Settings LIKE '%ezrss.it%' 
[Info] FluentMigrator.Runner.MigrationRunner: => 0.0006231s 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: INSERT INTO "VersionInfo" ("Version", "AppliedOn", "Description") VALUES (74, '2024-01-13T15:12:56', 'disable_eztv') 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Committing Transaction 
[Info] FluentMigrator.Runner.MigrationRunner: 74: disable_eztv migrated 
[Info] FluentMigrator.Runner.MigrationRunner: => 0.138726s 
[Info] FluentMigrator.Runner.MigrationRunner: 75: force_lib_update migrating 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Beginning Transaction 
[Info] force_lib_update: Starting migration of Main DB to 75 
[Info] FluentMigrator.Runner.MigrationRunner: UpdateData  
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: UPDATE "ScheduledTasks" SET "LastExecution" = '2014-01-01 00:00:00' WHERE "TypeName" = 'NzbDrone.Core.Tv.Commands.RefreshSeriesCommand' 
[Info] FluentMigrator.Runner.MigrationRunner: => 0.0007838s 
[Info] FluentMigrator.Runner.MigrationRunner: UpdateData  
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: UPDATE "Series" SET "LastInfoSync" = '2014-01-01 00:00:00' WHERE 1 = 1 
[Info] FluentMigrator.Runner.MigrationRunner: => 0.0006325s 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: INSERT INTO "VersionInfo" ("Version", "AppliedOn", "Description") VALUES (75, '2024-01-13T15:12:56', 'force_lib_update') 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Committing Transaction 
[Info] FluentMigrator.Runner.MigrationRunner: 75: force_lib_update migrated 
[Info] FluentMigrator.Runner.MigrationRunner: => 0.1233904s 
[Info] FluentMigrator.Runner.MigrationRunner: 76: add_users_table migrating 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Beginning Transaction 
[...]
```

**Comment by mreid-tt** [comment]
I've done a clean-install test under DSM 7 and the initial setup goes smoothly so it seems to be restricted to DSM 6 which is why I didn't pick it up in my original testing. I will disable the downloads for v4.0.0.733 for DSM 6 users in the meantime as this will not be a good user experience for them.

**Comment by bakerboy448** [comment]
What sqllite version in dsm6 running?  But certainly interesting it works on dsm7 not dsm6 and worth reporting to the sonarr team

the change between the version is 0 to false in the query when postgresql was added

**Comment by mreid-tt** [comment]
Another thing I noticed is that the database migrations now seem to take place as part of the install process rather than with v4.0.0.460 where the package install completed and the database migrations happened asynchronously. The challenge is that even though the installation completes according to the log, the package installer does not believe the package has completed installation; presumably due to a timeout or because the package stops running when the database migration is complete.

To resolve this a user would have to click repair (if available) or uninstall (not removing content) and re-install at which point the database would already be present and the app ready to run. This is also a poor user experience in my view that I didn't test for thoroughly until now. Any thoughts on why the first-run behaviour is different?

**Comment by bakerboy448** [comment]
Migrations / migration checks always run on app startup that hasn't changed as far as I'm aware

**Comment by mreid-tt** [comment]
> What sqllite version in dsm6 running? But certainly interesting it works on dsm7 not dsm6 and worth reporting to the sonarr team

As for the versions of sqlite3, this is what I could find:

For DSM 7:

```
$ which sqlite3
/bin/sqlite3
$ ls -all /bin/sqlite3
-rwxr-xr-x 1 root root 1489968 Dec 15  2022 /bin/sqlite3
$ /bin/sqlite3
SQLite version 3.40.0 2022-11-16 12:10:08
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> .quit
```

For DSM 6:

```
$ which sqlite3
/bin/sqlite3
$ ls -all /bin/sqlite3
-rwxr-xr-x 1 root root 867008 Mar  1  2021 /bin/sqlite3
$ /bin/sqlite3
SQLite version 3.10.2 2016-01-20 15:27:19
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> .quit
```

**Comment by mreid-tt** [comment]
> the change between the version is 0 to false in the query when postgresql was added

@bakerboy448, after chatting with the sonarr folks they confirmed your suspicion that the older version of sqlite3 was the blame:

> The minimum version is 3.23. But you should go for something a bit newer. 
>> Recognize TRUE and FALSE as constants. (For compatibility, if there exist columns named "true" or "false", then the identifiers refer to the columns rather than Boolean constants.)

I'm going to try a new dependency inclusion to try to address this and test again.
