### ISSUE TITLE
Deluge will auto stop when install completed

### ISSUE THREAD

**Issue by hedandan1989** [SynoCommunity/spksrc#6135]
Deluge not start
DS923+ 
DSM7.2

here is the log
```
root@DS923plus:~# vi /var/log/packages/deluge.log
2024/06/11 21:05:44 install deluge 2.1.1.61-23 Begin preinst
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'certifi'

2024/06/11 21:05:44 Begin load_variables_from_file
2024/06/11 21:05:44 End load_variables_from_file
2024/06/11 21:05:44 Begin initialize_variables
2024/06/11 21:05:44 End initialize_variables
2024/06/11 21:05:44 ===> Step preinst. STATUS=INSTALL USER=sc-deluge GROUP=synocommunity 
SHARE_PATH=/volume3/PT
2024/06/11 21:05:44 install deluge 2.1.1.61-23 End preinst ret=[0]
2024/06/11 21:05:44 install deluge 2.1.1.61-23 Begin /bin/mkdir -p /volume1/@appstore/deluge -m 755
2024/06/11 21:05:44 install deluge 2.1.1.61-23 End /bin/mkdir -p /volume1/@appstore/deluge -m 755 ret=[0]
2024/06/11 21:05:44 install deluge 2.1.1.61-23 Begin /bin/rm -rf /volume1/@appstore/deluge
2024/06/11 21:05:44 install deluge 2.1.1.61-23 End /bin/rm -rf /volume1/@appstore/deluge ret=[0]
2024/06/11 21:05:44 install deluge 2.1.1.61-23 Begin /bin/mv -f /volume1/@tmp/synopkg/install.eAPb00/package 
/volume1/@appstore/deluge
2024/06/11 21:05:44 install deluge 2.1.1.61-23 End /bin/mv -f /volume1/@tmp/synopkg/install.eAPb00/package /volume1/@appstore/deluge ret=[0]
2024/06/11 21:05:44 install deluge 2.1.1.61-23 Begin /bin/rm -rf /var/packages/deluge
2024/06/11 21:05:44 install deluge 2.1.1.61-23 End /bin/rm -rf /var/packages/deluge ret=[0]
2024/06/11 21:05:44 install deluge 2.1.1.61-23 Begin /bin/mkdir -p /var/packages/deluge -m 755
2024/06/11 21:05:44 install deluge 2.1.1.61-23 End /bin/mkdir -p /var/packages/deluge -m 755 ret=[0]
2024/06/11 21:05:44 install deluge 2.1.1.61-23 Begin /bin/touch /var/packages/deluge/installing
2024/06/11 21:05:44 install deluge 2.1.1.61-23 End /bin/touch /var/packages/deluge/installing ret=[0]
2024/06/11 21:05:44 install deluge 2.1.1.61-23 Begin /bin/mv -f /volume1/@tmp/synopkg/install.eAPb00/INFO 
/var/packages/deluge/INFO
2024/06/11 21:05:44 install deluge 2.1.1.61-23 End /bin/mv -f /volume1/@tmp/synopkg/install.eAPb00/INFO /var/packages/deluge/INFO ret=[0]
2024/06/11 21:05:44 install deluge 2.1.1.61-23 Begin /bin/rm -rf /var/packages/deluge/scripts
2024/06/11 21:05:44 install deluge 2.1.1.61-23 End /bin/rm -rf /var/packages/deluge/scripts ret=[0]
2024/06/11 21:05:44 install deluge 2.1.1.61-23 Begin /bin/mv -f /volume1/@tmp/synopkg/install.eAPb00/scripts /var/packages/deluge/scripts
2024/06/11 21:05:44 install deluge 2.1.1.61-23 End /bin/mv -f /volume1/@tmp/synopkg/install.eAPb00/scripts /var/packages/deluge/scripts ret=[0]
2024/06/11 21:05:44 install deluge 2.1.1.61-23 Begin /bin/rm -rf /var/packages/deluge/WIZARD_UIFILES
2024/06/11 21:05:44 install deluge 2.1.1.61-23 End /bin/rm -rf /var/packages/deluge/WIZARD_UIFILES ret=[0]
2024/06/11 21:05:44 install deluge 2.1.1.61-23 Begin /bin/mv -f /volume1/@tmp/synopkg/install.eAPb00/WIZARD_UIFILES /var/packages/deluge/WIZARD_UIFILES
2024/06/11 21:05:44 install deluge 2.1.1.61-23 End /bin/mv -f /volume1/@tmp/synopkg/install.eAPb00/WIZARD_UIFILES /var/packages/deluge/WIZARD_UIFILES ret=[0]
2024/06/11 21:05:44 install deluge 2.1.1.61-23 Begin /bin/rm -rf /var/packages/deluge/conf
2024/06/11 21:05:44 install deluge 2.1.1.61-23 End /bin/rm -rf /var/packages/deluge/conf ret=[0]
2024/06/11 21:05:44 install deluge 2.1.1.61-23 Begin /bin/mv -f /volume1/@tmp/synopkg/install.eAPb00/conf /var/packages/deluge/conf
2024/06/11 21:05:44 install deluge 2.1.1.61-23 End /bin/mv -f /volume1/@tmp/synopkg/install.eAPb00/conf /var/packages/deluge/conf ret=[0]
2024/06/11 21:05:45 install deluge 2.1.1.61-23 Begin postinst
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'certifi'

2024/06/11 21:05:45 Begin load_variables_from_file
2024/06/11 21:05:45 End load_variables_from_file
2024/06/11 21:05:45 Begin initialize_variables
2024/06/11 21:05:45 End initialize_variables
2024/06/11 21:05:45 ===> Step postinst. STATUS=INSTALL USER=sc-deluge GROUP=synocommunity SHARE_PATH=/volume3/PT
2024/06/11 21:05:45 Begin save_wizard_variables
2024/06/11 21:05:45 End save_wizard_variables
2024/06/11 21:05:45 Begin syno_sync_var_folder
2024/06/11 21:05:45 Install files from var folder
2024/06/11 21:05:45 /bin/rsync -avh --ignore-existing --remove-source-files /volume1/@appstore/deluge/var/ /volume1/@appdata/deluge
2024/06/11 21:05:45 sending incremental file list
2024/06/11 21:05:45 ./
2024/06/11 21:05:45 autoadd.conf
2024/06/11 21:05:45 core.conf
2024/06/11 21:05:45 logs/
2024/06/11 21:05:45 sent 4.84K bytes  received 77 bytes  9.83K bytes/sec
2024/06/11 21:05:45 total size is 4.62K  speedup is 0.94
2024/06/11 21:05:45 /bin/rsync -avh --remove-source-files /volume1/@appstore/deluge/var/ /volume1/@appdata/deluge
2024/06/11 21:05:45 sending incremental file list
2024/06/11 21:05:45 ./
2024/06/11 21:05:45 sent 100 bytes  received 20 bytes  240.00 bytes/sec
2024/06/11 21:05:45 total size is 0  speedup is 0.00
2024/06/11 21:05:45 End syno_sync_var_folder
2024/06/11 21:05:45 Begin service_postinst
2024/06/11 21:05:45 Python 3.11.5
2024/06/11 21:05:50 Requirement already satisfied: pip in /volume1/@appstore/deluge/env/lib/python3.11/site-packages (23.2.1)
2024/06/11 21:06:38 WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/pip/
2024/06/11 21:07:21 [notice] A new release of pip is available: 23.2.1 -> 24.0
2024/06/11 21:07:21 [notice] To update, run: pip install --upgrade pip
2024/06/11 21:07:21 Install packages from wheels
2024/06/11 21:07:21 Install packages from wheels [/volume1/@appstore/deluge/share/wheelhouse/requirements.txt]
2024/06/11 21:07:21 Looking in links: /volume1/@appstore/deluge/share/wheelhouse
2024/06/11 21:07:38 WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/automat/
2024/06/11 21:07:56 WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/automat/
2024/06/11 21:08:15 Collecting Automat==22.10.0 (from -r /volume1/@appstore/deluge/share/wheelhouse/requirements.txt (line 12))
2024/06/11 21:08:15   Obtaining dependency information for Automat==22.10.0 from https://files.pythonhosted.org/packages/29/90/64aabce6c1b820395452cc5472b8f11cd98320f40941795b8069aef4e0e0/Automat-22.10.0-py2.py3-none-any.whl.metadata
2024/06/11 21:08:18   Downloading Automat-22.10.0-py2.py3-none-any.whl.metadata (1.0 kB)
2024/06/11 21:08:19 Processing /volume1/@appstore/deluge/share/wheelhouse/GeoIP-1.3.2-cp311-cp311-linux_x86_64.whl (from -r /volume1/@appstore/deluge/share/wheelhouse/requirements.txt (line 13))
2024/06/11 21:08:43 ERROR: Could not find a version that satisfies the requirement Mako==1.2.4 (from versions: none)
2024/06/11 21:08:43 ERROR: No matching distribution found for Mako==1.2.4
2024/06/11 21:08:58 Installed modules:
2024/06/11 21:08:58 End service_postinst
2024/06/11 21:08:58 install deluge 2.1.1.61-23 End postinst ret=[0]
2024/06/11 21:08:59 install deluge 2.1.1.61-23 Begin start-stop-status start
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'certifi'

2024/06/11 21:08:59 install deluge 2.1.1.61-23 End start-stop-status start ret=[0]
```

**Comment by mreid-tt** [comment]
This seems to be a download issue based on this line:
```
ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443)
```
If this is a fresh install perhaps uninstall then reinstall? It may be that there was a temporary download issue at the server 'pypi.org'.

**Comment by hedandan1989** [comment]
> This seems to be a download issue based on this line:
> 
> ```
> ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443)
> ```
> 
> If this is a fresh install perhaps uninstall then reinstall? It may be that there was a temporary download issue at the server 'pypi.org'.

Yes, this is a brand new installation. I uninstalled it several times, installed it several times, and each time it made an error with this timeout message, but each time it was a different package.

I think this may be a network issue. Is there a manually executed script for this issue?

**Comment by mreid-tt** [comment]
Hmm, the default way Python-based packages are constructed they download required files at installation time. There may be ways to manually override this but it may require a new package to be built.

@th0ma7 this is not an area I am deeply familiar with, what's your take on the above?

**Comment by th0ma7** [comment]
It is indeed possible to generate a package containing all the needed python wheels but it requires recompiling and repackaging.  We don't have enough storage on our repository server to do that but one of can probably shared through other means.

Also, just curious, was python311 installed successfully for a start?

**Comment by hedandan1989** [comment]
> It is indeed possible to generate a package containing all the needed python wheels but it requires recompiling and repackaging. We don't have enough storage on our repository server to do that but one of can probably shared through other means.确实可以生成包含所有所需Python轮子的包，但这需要重新编译和打包。 我们的存储服务器没有足够的空间来完成此操作，但我们可以通过其他方式共享其中一个。
> 
> Also, just curious, was python311 installed successfully for a start?顺便问一下，Python 3.11是否已成功安装？

Yes, Python 3.11 has been successfully installed.
I manually executed pip install - r/volumn1/@appstore/xxx/requirement.txt in SSH, but it couldn't be installed because of network issues, I couldn't download the setupxxxx.whl package. I tried to switch to our country's own image source, but some packages were missing.

**Comment by hedandan1989** [comment]
I changed nas dns,and it installed success .  
Thank you.
Pip is often inaccessible on the china network, and I have encountered it several times on my own Ubuntu server.
