### ISSUE TITLE
Ombi v4.44.1 crash on DSM 7.1.1

### ISSUE THREAD

**Issue by mreid-tt** [SynoCommunity/spksrc#6346]
### Is this a new Bug?

- [X] I checked that the bug hasn't been reported before

### Package Name

Ombi

### Package Version

4.44.1-4

### Device Model

DS916+

### Device Architecture

x86_64

### Firmware Version

DSM 7.1.1-42962 Update 6

### What happened?

Installing the latest version of Ombi results in a failed starup.

### Reproduction steps

1. Install Ombi v4.44.1
2. Run program

### Install Log

```log
2024/12/07 21:58:10	install ombi 4.44.1-4 Begin preinst
2024/12/07 21:58:10	Begin initialize_variables
2024/12/07 21:58:10	End initialize_variables
2024/12/07 21:58:10	===> Step preinst. STATUS=INSTALL USER=ombi GROUP= SHARE_PATH=
2024/12/07 21:58:10	install ombi 4.44.1-4 End preinst ret=[0]
2024/12/07 21:58:11	install ombi 4.44.1-4 Begin /bin/mkdir -p /volume1/@appstore/ombi -m 755
2024/12/07 21:58:11	install ombi 4.44.1-4 End /bin/mkdir -p /volume1/@appstore/ombi -m 755 ret=[0]
2024/12/07 21:58:11	install ombi 4.44.1-4 Begin /bin/rm -rf /volume1/@appstore/ombi
2024/12/07 21:58:11	install ombi 4.44.1-4 End /bin/rm -rf /volume1/@appstore/ombi ret=[0]
2024/12/07 21:58:11	install ombi 4.44.1-4 Begin /bin/mv -f /volume1/@tmp/synopkg/install.yfN4kR/package /volume1/@appstore/ombi
2024/12/07 21:58:11	install ombi 4.44.1-4 End /bin/mv -f /volume1/@tmp/synopkg/install.yfN4kR/package /volume1/@appstore/ombi ret=[0]
2024/12/07 21:58:11	install ombi 4.44.1-4 Begin /bin/rm -rf /var/packages/ombi
2024/12/07 21:58:11	install ombi 4.44.1-4 End /bin/rm -rf /var/packages/ombi ret=[0]
2024/12/07 21:58:11	install ombi 4.44.1-4 Begin /bin/mkdir -p /var/packages/ombi -m 755
2024/12/07 21:58:11	install ombi 4.44.1-4 End /bin/mkdir -p /var/packages/ombi -m 755 ret=[0]
2024/12/07 21:58:11	install ombi 4.44.1-4 Begin /bin/touch /var/packages/ombi/installing
2024/12/07 21:58:11	install ombi 4.44.1-4 End /bin/touch /var/packages/ombi/installing ret=[0]
2024/12/07 21:58:11	install ombi 4.44.1-4 Begin /bin/mv -f /volume1/@tmp/synopkg/install.yfN4kR/INFO /var/packages/ombi/INFO
2024/12/07 21:58:11	install ombi 4.44.1-4 End /bin/mv -f /volume1/@tmp/synopkg/install.yfN4kR/INFO /var/packages/ombi/INFO ret=[0]
2024/12/07 21:58:11	install ombi 4.44.1-4 Begin /bin/rm -rf /var/packages/ombi/scripts
2024/12/07 21:58:11	install ombi 4.44.1-4 End /bin/rm -rf /var/packages/ombi/scripts ret=[0]
2024/12/07 21:58:11	install ombi 4.44.1-4 Begin /bin/mv -f /volume1/@tmp/synopkg/install.yfN4kR/scripts /var/packages/ombi/scripts
2024/12/07 21:58:11	install ombi 4.44.1-4 End /bin/mv -f /volume1/@tmp/synopkg/install.yfN4kR/scripts /var/packages/ombi/scripts ret=[0]
2024/12/07 21:58:11	install ombi 4.44.1-4 Begin /bin/rm -rf /var/packages/ombi/WIZARD_UIFILES
2024/12/07 21:58:11	install ombi 4.44.1-4 End /bin/rm -rf /var/packages/ombi/WIZARD_UIFILES ret=[0]
2024/12/07 21:58:11	install ombi 4.44.1-4 Begin /bin/mv -f /volume1/@tmp/synopkg/install.yfN4kR/WIZARD_UIFILES /var/packages/ombi/WIZARD_UIFILES
2024/12/07 21:58:11	install ombi 4.44.1-4 End /bin/mv -f /volume1/@tmp/synopkg/install.yfN4kR/WIZARD_UIFILES /var/packages/ombi/WIZARD_UIFILES ret=[0]
2024/12/07 21:58:11	install ombi 4.44.1-4 Begin /bin/rm -rf /var/packages/ombi/conf
2024/12/07 21:58:11	install ombi 4.44.1-4 End /bin/rm -rf /var/packages/ombi/conf ret=[0]
2024/12/07 21:58:11	install ombi 4.44.1-4 Begin /bin/mv -f /volume1/@tmp/synopkg/install.yfN4kR/conf /var/packages/ombi/conf
2024/12/07 21:58:11	install ombi 4.44.1-4 End /bin/mv -f /volume1/@tmp/synopkg/install.yfN4kR/conf /var/packages/ombi/conf ret=[0]
2024/12/07 21:58:17	install ombi 4.44.1-4 Begin postinst
2024/12/07 21:58:17	Begin initialize_variables
2024/12/07 21:58:17	End initialize_variables
2024/12/07 21:58:17	===> Step postinst. STATUS=INSTALL USER=ombi GROUP= SHARE_PATH=
2024/12/07 21:58:17	Begin save_wizard_variables
2024/12/07 21:58:17	End save_wizard_variables
2024/12/07 21:58:17	Begin syno_sync_var_folder
2024/12/07 21:58:17	End syno_sync_var_folder
2024/12/07 21:58:17	install ombi 4.44.1-4 End postinst ret=[0]
2024/12/07 21:58:18	install ombi 4.44.1-4 Begin start-stop-status start
2024/12/07 21:58:18	install ombi 4.44.1-4 End start-stop-status start ret=[0]
```

### Service Log

```log
Sat Dec  7 21:58:18 -04 2024
Starting ombi command /volume1/@appstore/ombi/shared/Ombi --storage /volume1/@appdata/ombi --host http://*:8822
Hello, welcome to Ombi
Valid options are:
Ombi 4.44.1+1e3bd6377ce64c5d79f8b267f0f190b7b141d8af
Copyright (C) 2024 Ombi

  --host       (Default: http://*:5000) Set to a semicolon-separated (;) list of
               URL prefixes to which the server should respond. For example,
               http://localhost:123. Use "localhost" to indicate that the server
               should listen for requests on any IP address or hostname using
               the specified port and protocol (for example,
               http://localhost:5000). The protocol (http:// or https://) must
               be included with each URL. Supported formats vary between
               servers.

  --storage    Storage path, where we save the logs and database

  --baseurl    The base URL for reverse proxy scenarios

  --demo       Demo mode, you will never need to use this, fuck that fruit
               company...

  --migrate    Will run the migrations then exit the application

  --help       Display this help screen.

  --version    Display version information.



Unhandled exception. System.DllNotFoundException: Unable to load shared library 'e_sqlite3' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/volume1/@appstore/ombi/shared/e_sqlite3.so: cannot open shared object file: No such file or directory
/lib64/libc.so.6: version `GLIBC_2.28' not found (required by /volume1/@appstore/ombi/shared/libe_sqlite3.so)
libe_sqlite3.so: cannot open shared object file: No such file or directory
/volume1/@appstore/ombi/shared/e_sqlite3: cannot open shared object file: No such file or directory
/volume1/@appstore/ombi/shared/libe_sqlite3: cannot open shared object file: No such file or directory

   at SQLitePCL.SQLite3Provider_e_sqlite3.NativeMethods.sqlite3_libversion_number()
   at SQLitePCL.SQLite3Provider_e_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_libversion_number()
   at SQLitePCL.raw.SetProvider(ISQLite3Provider imp)
   at SQLitePCL.Batteries_V2.Init()
   at SQLitePCL.Batteries.Init()
   at Ombi.Extensions.DatabaseExtensions.ConfigureSqlite(DbContextOptionsBuilder options, PerDatabaseConfiguration config) in /home/runner/work/Ombi/Ombi/src/Ombi/Extensions/DatabaseExtensions.cs:line 149
   at Ombi.Extensions.DatabaseExtensions.<>c__DisplayClass3_0.<ConfigureDatabases>b__6(DbContextOptionsBuilder x) in /home/runner/work/Ombi/Ombi/src/Ombi/Extensions/DatabaseExtensions.cs:line 69
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__DisplayClass1_0`2.<AddDbContext>b__0(IServiceProvider _, DbContextOptionsBuilder b)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.CreateDbContextOptions[TContext](IServiceProvider applicationServiceProvider, Action`2 optionsAction)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__DisplayClass17_0`1.<AddCoreServices>b__0(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Ombi.Program.Main(String[] args) in /home/runner/work/Ombi/Ombi/src/Ombi/Program.cs:line 74
   at Ombi.Program.<Main>(String[] args)
```

**Comment by mreid-tt** [comment]
@hgy59, this seems very much like the findings you had in https://github.com/SynoCommunity/spksrc/pull/6101#issuecomment-2142086263. I've tested the earlier version 4.43.5-3 on the same DSM 7.1.1 and that version works.

Looking at the [changes](https://github.com/Ombi-app/Ombi/compare/v4.43.5...v4.44.1) between this version and the last we find the following:

_src/Ombi.Core/Ombi.Core.csproj_
```
 -  <PackageReference Include="Microsoft.AspNetCore.Cryptography.KeyDerivation" Version="6.0.9" />
 -  <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="6.0.9" />
 +  <PackageReference Include="Microsoft.AspNetCore.Cryptography.KeyDerivation" Version="8.0.5" />
 +  <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.5" />
```

_src/Ombi.Store/Ombi.Store.csproj_
```
 -  <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="6.0.9" />
 +  <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.5" />
```

Based on your previous analysis we may need to publish the current Ombi version with `REQUIRED_MIN_DSM = 7.2`.

**Comment by hgy59** [comment]
@mreid-tt I have created libe_sqlite3.so for x64-7.1 and as expected it does not depend on GLIBC 2.28.

I installed ombi on DSM 7.2.2 and replaced the original libe_sqlite3.so in target/shared/ with this one and it still works.

[libe_sqlite3_x64-7.1.zip](https://github.com/user-attachments/files/18053643/libe_sqlite3_x64-7.1.zip)

**Comment by mreid-tt** [comment]
@hgy59, this is brilliant. The service log looks clean now:

```
Sun Dec  8 16:30:52 -04 2024
Starting ombi command /volume1/@appstore/ombi/shared/Ombi --storage /volume1/@appdata/ombi --host http://*:8822
Hello, welcome to Ombi
Valid options are:
Ombi 4.44.1+1e3bd6377ce64c5d79f8b267f0f190b7b141d8af
Copyright (C) 2024 Ombi

  --host       (Default: http://*:5000) Set to a semicolon-separated (;) list of
               URL prefixes to which the server should respond. For example,
               http://localhost:123. Use "localhost" to indicate that the server
               should listen for requests on any IP address or hostname using
               the specified port and protocol (for example,
               http://localhost:5000). The protocol (http:// or https://) must
               be included with each URL. Supported formats vary between
               servers.

  --storage    Storage path, where we save the logs and database

  --baseurl    The base URL for reverse proxy scenarios

  --demo       Demo mode, you will never need to use this, fuck that fruit
               company...

  --migrate    Will run the migrations then exit the application

  --help       Display this help screen.

  --version    Display version information.



Creating new Settings entity
Wrote new baseurl at /volume1/@appstore/ombi/shared/ClientApp/dist/index.html
We are running on http://*:8822
/volume1/@appstore/ombi/shared
```

The old and new files are as follows:
```
$ ls -al /var/packages/ombi/target/shared/libe_sqlite3.so.old 
-rwxr--r-- 1 sc-ombi synocommunity 1249880 Aug 23  2023 /var/packages/ombi/target/shared/libe_sqlite3.so.old
$ ls -al /var/packages/ombi/target/shared/libe_sqlite3.so
-rwxr--r-- 1 sc-ombi synocommunity 1311768 Dec  8 16:28 /var/packages/ombi/target/shared/libe_sqlite3.so
```

**Comment by mreid-tt** [comment]
@hgy59, so will this version work with DSM 6? What are the next steps to integrate a custom build like this into the package for multiple platforms?

**Comment by hgy59** [comment]
I just created cross/libe_sqlite3 with sources from https://github.com/ericsink/cb/tree/master/sqlite3 and https://github.com/ericsink/cb/tree/master/stup and created a package for aarch64-6.2.4

and it works ❤️ 


unfortunately the repo https://github.com/ericsink/cb does not provide releases and the repository it too large to clone (it contains all the native lib*sqlite libraries) so I added the source files to cross/libe_sqlite3.

Will create a PR soon.

With this we can continue to create packages for ombi and jellyfin for DSM 6.2.4 and DSM 7.1.
